import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest'
import { flushPromises, mount } from '@vue/test-utils'
import Dialog from '../UpstreamGroupModelsDialog.vue'
import type { CatalogGroup, ModelSnapshot } from '@/api/admin/upstreamCatalog'

const { getGroupModels, syncGroupModels } = vi.hoisted(() => ({ getGroupModels: vi.fn(), syncGroupModels: vi.fn() }))
vi.mock('@/api/admin/upstreamCatalog', () => ({ getGroupModels, syncGroupModels }))
vi.mock('vue-i18n', () => ({ useI18n: () => ({ t: (key: string) => key }) }))
vi.mock('@/utils/format', () => ({ formatDateTime: (value: string) => value }))
const group = { connection_id: 1, remote_key: 'id:12', name: 'Primary', connection_name: 'Upstream', management_base_url: 'https://example.invalid' } as CatalogGroup
const snapshot: ModelSnapshot = { models: ['gpt-5', 'claude-sonnet-4-6'], auto_tags: ['GPT', 'Claude'], status: 'ready', coverage: 'bound_keys', source: 'bound_keys', error_code: '', observed_at: '2026-09-26T00:00:00Z', fresh_until: '2026-09-26T06:00:00Z' }
const view = (selected: CatalogGroup | null = group) => mount(Dialog, {
  props: { group: selected },
  global: { stubs: { BaseDialog: { props: ['show'], template: '<div v-if="show"><slot /></div>' }, Pagination: true } },
})
beforeEach(() => {
  vi.clearAllMocks()
  getGroupModels.mockReset()
  syncGroupModels.mockReset()
  getGroupModels.mockResolvedValue(snapshot)
  syncGroupModels.mockResolvedValue(snapshot)
})
afterEach(() => { vi.useRealTimers(); vi.restoreAllMocks() })
describe('group models dialog', () => {
  it('keeps old models visible and labels an expired source', async () => {
    getGroupModels.mockResolvedValue({ ...snapshot, status: 'stale', source_count: 1, ready_source_count: 0, stale_source_count: 1 })
    const w = view()
    await flushPromises()
    expect(w.text()).toContain('upstreamWorkspace.modelStatus.stale')
    expect(w.text()).toContain('upstreamWorkspace.modelSourceProgress')
    expect(w.findAll('li')).toHaveLength(2)
    expect(syncGroupModels).not.toHaveBeenCalled()
    w.unmount()
  })
  it('shows pending source progress without reporting a failed refresh', async () => {
    getGroupModels.mockResolvedValue({ ...snapshot, status: 'pending', error_code: 'pending_keys', source_count: 19, ready_source_count: 8, pending_source_count: 11, failed_source_count: 0 })
    const w = view()
    await flushPromises()
    expect(w.text()).toContain('upstreamWorkspace.modelStatus.pending')
    expect(w.text()).toContain('upstreamWorkspace.modelSourceProgress')
    expect(w.text()).not.toContain('upstreamWorkspace.modelsSyncError')
    expect(w.findAll('li')).toHaveLength(2)
    w.unmount()
  })
  it('reads snapshots only when opened and searches exact model IDs', async () => {
    const w = view(null)
    await flushPromises()
    expect(getGroupModels).not.toHaveBeenCalled()
    await w.setProps({ group })
    await flushPromises()
    expect(w.findAll('li')).toHaveLength(2)
    expect(syncGroupModels).not.toHaveBeenCalled()
    await w.get('input').setValue('CLAUDE')
    expect(w.findAll('li')).toHaveLength(1)
    expect(w.get('li').text()).toContain('claude-sonnet-4-6')
    w.unmount()
  })
  it('keeps the successful models visible when refresh fails', async () => {
    syncGroupModels.mockResolvedValue({ ...snapshot, status: 'error', error_code: 'unavailable' })
    const w = view()
    await flushPromises()
    await w.findAll('button').find(b => b.text() === 'upstreamWorkspace.refreshModels')!.trigger('click')
    await flushPromises()
    expect(w.findAll('li')).toHaveLength(2)
    expect(w.text()).toContain('upstreamWorkspace.modelErrors.unavailable')
    expect(w.emitted('updated')).toHaveLength(1)
    w.unmount()
  })
  it('never displays a stale response after switching groups', async () => {
    let resolveOld!: (data: ModelSnapshot) => void
    getGroupModels.mockReturnValueOnce(new Promise<ModelSnapshot>(resolve => { resolveOld = resolve }))
    const w = view()
    await w.setProps({ group: { ...group, remote_key: 'id:13', name: 'Other' } })
    await flushPromises()
    resolveOld({ ...snapshot, models: ['wrong-group-model'] })
    await flushPromises()
    expect(w.text()).not.toContain('wrong-group-model')
    w.unmount()
  })
  it('bounds rendered rows even for very large model catalogs', async () => {
    getGroupModels.mockResolvedValue({ ...snapshot, models: Array.from({ length: 1000 }, (_, i) => `model-${i}`) })
    const w = view()
    await flushPromises()
    expect(w.findAll('li')).toHaveLength(50)
    w.unmount()
  })
  it('polls pending work using GET and stops once all sources finish', async () => {
    vi.useFakeTimers()
    getGroupModels.mockResolvedValueOnce({ ...snapshot, status: 'pending', refresh_in_progress: true, ready_source_count: 8, source_count: 19, pending_source_count: 11 })
      .mockResolvedValue({ ...snapshot, models: ['completed-model'], refresh_in_progress: false })
    const w = view()
    await flushPromises()
    await vi.advanceTimersByTimeAsync(4999)
    expect(getGroupModels).toHaveBeenCalledTimes(1)
    await vi.advanceTimersByTimeAsync(1)
    await flushPromises()
    expect(w.text()).toContain('completed-model')
    expect(w.emitted('updated')).toHaveLength(1)
    await vi.advanceTimersByTimeAsync(600000)
    expect(getGroupModels).toHaveBeenCalledTimes(2)
    expect(syncGroupModels).not.toHaveBeenCalled()
    w.unmount()
  })
  it('continues a partial batch with pending sources but stops on terminal failure', async () => {
    vi.useFakeTimers()
    getGroupModels.mockResolvedValueOnce({ ...snapshot, status: 'partial', refresh_in_progress: true, pending_source_count: 2, failed_source_count: 1 })
      .mockResolvedValue({ ...snapshot, status: 'partial', refresh_in_progress: false, pending_source_count: 0, failed_source_count: 1 })
    const w = view()
    await flushPromises()
    await vi.advanceTimersByTimeAsync(5000)
    await flushPromises()
    await vi.advanceTimersByTimeAsync(60000)
    expect(getGroupModels).toHaveBeenCalledTimes(2)
    expect(w.text()).toContain('upstreamWorkspace.modelStatus.partial')
    w.unmount()
  })
  it('does not poll pending observations when the backend has no running work', async () => {
    vi.useFakeTimers()
    getGroupModels.mockResolvedValue({ ...snapshot, status: 'pending', refresh_in_progress: false })
    const w = view()
    await flushPromises()
    await vi.advanceTimersByTimeAsync(60000)
    expect(getGroupModels).toHaveBeenCalledTimes(1)
    w.unmount()
  })
  it('stops timers when closed and cancels in-flight polling when unmounted', async () => {
    vi.useFakeTimers()
    getGroupModels.mockResolvedValue({ ...snapshot, status: 'pending', refresh_in_progress: true })
    const w = view()
    await flushPromises()
    await w.setProps({ group: null })
    await vi.advanceTimersByTimeAsync(60000)
    expect(getGroupModels).toHaveBeenCalledTimes(1)
    await w.setProps({ group })
    await flushPromises()
    let resolvePoll!: (value: ModelSnapshot) => void
    getGroupModels.mockReturnValueOnce(new Promise<ModelSnapshot>(resolve => { resolvePoll = resolve }))
    await vi.advanceTimersByTimeAsync(5000)
    const signal = getGroupModels.mock.calls.at(-1)![1] as AbortSignal
    w.unmount()
    expect(signal.aborted).toBe(true)
    resolvePoll(snapshot)
    await flushPromises()
    await vi.advanceTimersByTimeAsync(60000)
    expect(getGroupModels).toHaveBeenCalledTimes(3)
  })
  it('suspends polling in hidden tabs and resumes on visibility without starting upstream work', async () => {
    vi.useFakeTimers()
    const hidden = vi.spyOn(document, 'hidden', 'get').mockReturnValue(false)
    getGroupModels.mockResolvedValue({ ...snapshot, status: 'pending', refresh_in_progress: true })
    const w = view()
    await flushPromises()
    hidden.mockReturnValue(true)
    document.dispatchEvent(new Event('visibilitychange'))
    await vi.advanceTimersByTimeAsync(60000)
    expect(getGroupModels).toHaveBeenCalledTimes(1)
    hidden.mockReturnValue(false)
    document.dispatchEvent(new Event('visibilitychange'))
    await vi.advanceTimersByTimeAsync(5000)
    expect(getGroupModels).toHaveBeenCalledTimes(2)
    expect(syncGroupModels).not.toHaveBeenCalled()
    w.unmount()
  })
  it('backs off failed polls, retains results, and exposes a read-only retry', async () => {
    vi.useFakeTimers()
    getGroupModels.mockResolvedValueOnce({ ...snapshot, status: 'pending', refresh_in_progress: true }).mockRejectedValue(new Error('offline'))
    const w = view()
    await flushPromises()
    await vi.advanceTimersByTimeAsync(35000)
    await flushPromises()
    expect(getGroupModels).toHaveBeenCalledTimes(4)
    expect(w.text()).toContain('upstreamWorkspace.modelsPollError')
    expect(w.findAll('li')).toHaveLength(2)
    await vi.advanceTimersByTimeAsync(60000)
    expect(getGroupModels).toHaveBeenCalledTimes(4)
    getGroupModels.mockResolvedValue({ ...snapshot, refresh_in_progress: false })
    await w.findAll('button').find(b => b.text() === 'upstreamWorkspace.retryModelProgress')!.trigger('click')
    await flushPromises()
    expect(w.text()).not.toContain('upstreamWorkspace.modelsPollError')
    expect(syncGroupModels).not.toHaveBeenCalled()
    w.unmount()
  })
  it('never overlaps slow polls or lets an old poll replace a newer manual result', async () => {
    vi.useFakeTimers()
    getGroupModels.mockResolvedValueOnce({ ...snapshot, status: 'pending', refresh_in_progress: true })
    let resolvePoll!: (value: ModelSnapshot) => void
    getGroupModels.mockReturnValueOnce(new Promise<ModelSnapshot>(resolve => { resolvePoll = resolve }))
    const w = view()
    await flushPromises()
    await vi.advanceTimersByTimeAsync(60000)
    expect(getGroupModels).toHaveBeenCalledTimes(2)
    const signal = getGroupModels.mock.calls[1][1] as AbortSignal
    syncGroupModels.mockResolvedValue({ ...snapshot, models: ['new-manual-model'], refresh_in_progress: false })
    await w.findAll('button').find(b => b.text() === 'upstreamWorkspace.refreshModels')!.trigger('click')
    await flushPromises()
    expect(signal.aborted).toBe(true)
    resolvePoll({ ...snapshot, models: ['stale-poll-model'] })
    await flushPromises()
    expect(w.text()).toContain('new-manual-model')
    expect(w.text()).not.toContain('stale-poll-model')
    w.unmount()
  })
})
