// Code generated by ent, DO NOT EDIT.

package referralrelationhistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the referralrelationhistory type in the database.
	Label = "referral_relation_history"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldOldReferrerUserID holds the string denoting the old_referrer_user_id field in the database.
	FieldOldReferrerUserID = "old_referrer_user_id"
	// FieldNewReferrerUserID holds the string denoting the new_referrer_user_id field in the database.
	FieldNewReferrerUserID = "new_referrer_user_id"
	// FieldOldBindCode holds the string denoting the old_bind_code field in the database.
	FieldOldBindCode = "old_bind_code"
	// FieldNewBindCode holds the string denoting the new_bind_code field in the database.
	FieldNewBindCode = "new_bind_code"
	// FieldChangeSource holds the string denoting the change_source field in the database.
	FieldChangeSource = "change_source"
	// FieldChangedBy holds the string denoting the changed_by field in the database.
	FieldChangedBy = "changed_by"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldMetadataJSON holds the string denoting the metadata_json field in the database.
	FieldMetadataJSON = "metadata_json"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the referralrelationhistory in the database.
	Table = "referral_relation_histories"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "referral_relation_histories"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for referralrelationhistory fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldOldReferrerUserID,
	FieldNewReferrerUserID,
	FieldOldBindCode,
	FieldNewBindCode,
	FieldChangeSource,
	FieldChangedBy,
	FieldReason,
	FieldMetadataJSON,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// OldBindCodeValidator is a validator for the "old_bind_code" field. It is called by the builders before save.
	OldBindCodeValidator func(string) error
	// NewBindCodeValidator is a validator for the "new_bind_code" field. It is called by the builders before save.
	NewBindCodeValidator func(string) error
	// ChangeSourceValidator is a validator for the "change_source" field. It is called by the builders before save.
	ChangeSourceValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ReferralRelationHistory queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByOldReferrerUserID orders the results by the old_referrer_user_id field.
func ByOldReferrerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOldReferrerUserID, opts...).ToFunc()
}

// ByNewReferrerUserID orders the results by the new_referrer_user_id field.
func ByNewReferrerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNewReferrerUserID, opts...).ToFunc()
}

// ByOldBindCode orders the results by the old_bind_code field.
func ByOldBindCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOldBindCode, opts...).ToFunc()
}

// ByNewBindCode orders the results by the new_bind_code field.
func ByNewBindCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNewBindCode, opts...).ToFunc()
}

// ByChangeSource orders the results by the change_source field.
func ByChangeSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChangeSource, opts...).ToFunc()
}

// ByChangedBy orders the results by the changed_by field.
func ByChangedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChangedBy, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByMetadataJSON orders the results by the metadata_json field.
func ByMetadataJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataJSON, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
