// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/commissionledger"
	"github.com/Wei-Shaw/sub2api/ent/commissionreward"
	"github.com/Wei-Shaw/sub2api/ent/commissionwithdrawal"
	"github.com/Wei-Shaw/sub2api/ent/commissionwithdrawalitem"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rechargeorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CommissionWithdrawalItemQuery is the builder for querying CommissionWithdrawalItem entities.
type CommissionWithdrawalItemQuery struct {
	config
	ctx                   *QueryContext
	order                 []commissionwithdrawalitem.OrderOption
	inters                []Interceptor
	predicates            []predicate.CommissionWithdrawalItem
	withWithdrawal        *CommissionWithdrawalQuery
	withUser              *UserQuery
	withReward            *CommissionRewardQuery
	withRechargeOrder     *RechargeOrderQuery
	withCommissionLedgers *CommissionLedgerQuery
	modifiers             []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CommissionWithdrawalItemQuery builder.
func (_q *CommissionWithdrawalItemQuery) Where(ps ...predicate.CommissionWithdrawalItem) *CommissionWithdrawalItemQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CommissionWithdrawalItemQuery) Limit(limit int) *CommissionWithdrawalItemQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CommissionWithdrawalItemQuery) Offset(offset int) *CommissionWithdrawalItemQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CommissionWithdrawalItemQuery) Unique(unique bool) *CommissionWithdrawalItemQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CommissionWithdrawalItemQuery) Order(o ...commissionwithdrawalitem.OrderOption) *CommissionWithdrawalItemQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryWithdrawal chains the current query on the "withdrawal" edge.
func (_q *CommissionWithdrawalItemQuery) QueryWithdrawal() *CommissionWithdrawalQuery {
	query := (&CommissionWithdrawalClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commissionwithdrawalitem.Table, commissionwithdrawalitem.FieldID, selector),
			sqlgraph.To(commissionwithdrawal.Table, commissionwithdrawal.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, commissionwithdrawalitem.WithdrawalTable, commissionwithdrawalitem.WithdrawalColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (_q *CommissionWithdrawalItemQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commissionwithdrawalitem.Table, commissionwithdrawalitem.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, commissionwithdrawalitem.UserTable, commissionwithdrawalitem.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryReward chains the current query on the "reward" edge.
func (_q *CommissionWithdrawalItemQuery) QueryReward() *CommissionRewardQuery {
	query := (&CommissionRewardClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commissionwithdrawalitem.Table, commissionwithdrawalitem.FieldID, selector),
			sqlgraph.To(commissionreward.Table, commissionreward.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, commissionwithdrawalitem.RewardTable, commissionwithdrawalitem.RewardColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRechargeOrder chains the current query on the "recharge_order" edge.
func (_q *CommissionWithdrawalItemQuery) QueryRechargeOrder() *RechargeOrderQuery {
	query := (&RechargeOrderClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commissionwithdrawalitem.Table, commissionwithdrawalitem.FieldID, selector),
			sqlgraph.To(rechargeorder.Table, rechargeorder.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, commissionwithdrawalitem.RechargeOrderTable, commissionwithdrawalitem.RechargeOrderColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCommissionLedgers chains the current query on the "commission_ledgers" edge.
func (_q *CommissionWithdrawalItemQuery) QueryCommissionLedgers() *CommissionLedgerQuery {
	query := (&CommissionLedgerClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commissionwithdrawalitem.Table, commissionwithdrawalitem.FieldID, selector),
			sqlgraph.To(commissionledger.Table, commissionledger.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, commissionwithdrawalitem.CommissionLedgersTable, commissionwithdrawalitem.CommissionLedgersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CommissionWithdrawalItem entity from the query.
// Returns a *NotFoundError when no CommissionWithdrawalItem was found.
func (_q *CommissionWithdrawalItemQuery) First(ctx context.Context) (*CommissionWithdrawalItem, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{commissionwithdrawalitem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CommissionWithdrawalItemQuery) FirstX(ctx context.Context) *CommissionWithdrawalItem {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CommissionWithdrawalItem ID from the query.
// Returns a *NotFoundError when no CommissionWithdrawalItem ID was found.
func (_q *CommissionWithdrawalItemQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{commissionwithdrawalitem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CommissionWithdrawalItemQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CommissionWithdrawalItem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CommissionWithdrawalItem entity is found.
// Returns a *NotFoundError when no CommissionWithdrawalItem entities are found.
func (_q *CommissionWithdrawalItemQuery) Only(ctx context.Context) (*CommissionWithdrawalItem, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{commissionwithdrawalitem.Label}
	default:
		return nil, &NotSingularError{commissionwithdrawalitem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CommissionWithdrawalItemQuery) OnlyX(ctx context.Context) *CommissionWithdrawalItem {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CommissionWithdrawalItem ID in the query.
// Returns a *NotSingularError when more than one CommissionWithdrawalItem ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CommissionWithdrawalItemQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{commissionwithdrawalitem.Label}
	default:
		err = &NotSingularError{commissionwithdrawalitem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CommissionWithdrawalItemQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CommissionWithdrawalItems.
func (_q *CommissionWithdrawalItemQuery) All(ctx context.Context) ([]*CommissionWithdrawalItem, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CommissionWithdrawalItem, *CommissionWithdrawalItemQuery]()
	return withInterceptors[[]*CommissionWithdrawalItem](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CommissionWithdrawalItemQuery) AllX(ctx context.Context) []*CommissionWithdrawalItem {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CommissionWithdrawalItem IDs.
func (_q *CommissionWithdrawalItemQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(commissionwithdrawalitem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CommissionWithdrawalItemQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CommissionWithdrawalItemQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CommissionWithdrawalItemQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CommissionWithdrawalItemQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CommissionWithdrawalItemQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CommissionWithdrawalItemQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CommissionWithdrawalItemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CommissionWithdrawalItemQuery) Clone() *CommissionWithdrawalItemQuery {
	if _q == nil {
		return nil
	}
	return &CommissionWithdrawalItemQuery{
		config:                _q.config,
		ctx:                   _q.ctx.Clone(),
		order:                 append([]commissionwithdrawalitem.OrderOption{}, _q.order...),
		inters:                append([]Interceptor{}, _q.inters...),
		predicates:            append([]predicate.CommissionWithdrawalItem{}, _q.predicates...),
		withWithdrawal:        _q.withWithdrawal.Clone(),
		withUser:              _q.withUser.Clone(),
		withReward:            _q.withReward.Clone(),
		withRechargeOrder:     _q.withRechargeOrder.Clone(),
		withCommissionLedgers: _q.withCommissionLedgers.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithWithdrawal tells the query-builder to eager-load the nodes that are connected to
// the "withdrawal" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CommissionWithdrawalItemQuery) WithWithdrawal(opts ...func(*CommissionWithdrawalQuery)) *CommissionWithdrawalItemQuery {
	query := (&CommissionWithdrawalClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWithdrawal = query
	return _q
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CommissionWithdrawalItemQuery) WithUser(opts ...func(*UserQuery)) *CommissionWithdrawalItemQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithReward tells the query-builder to eager-load the nodes that are connected to
// the "reward" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CommissionWithdrawalItemQuery) WithReward(opts ...func(*CommissionRewardQuery)) *CommissionWithdrawalItemQuery {
	query := (&CommissionRewardClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withReward = query
	return _q
}

// WithRechargeOrder tells the query-builder to eager-load the nodes that are connected to
// the "recharge_order" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CommissionWithdrawalItemQuery) WithRechargeOrder(opts ...func(*RechargeOrderQuery)) *CommissionWithdrawalItemQuery {
	query := (&RechargeOrderClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRechargeOrder = query
	return _q
}

// WithCommissionLedgers tells the query-builder to eager-load the nodes that are connected to
// the "commission_ledgers" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CommissionWithdrawalItemQuery) WithCommissionLedgers(opts ...func(*CommissionLedgerQuery)) *CommissionWithdrawalItemQuery {
	query := (&CommissionLedgerClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCommissionLedgers = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CommissionWithdrawalItem.Query().
//		GroupBy(commissionwithdrawalitem.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CommissionWithdrawalItemQuery) GroupBy(field string, fields ...string) *CommissionWithdrawalItemGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CommissionWithdrawalItemGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = commissionwithdrawalitem.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.CommissionWithdrawalItem.Query().
//		Select(commissionwithdrawalitem.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *CommissionWithdrawalItemQuery) Select(fields ...string) *CommissionWithdrawalItemSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CommissionWithdrawalItemSelect{CommissionWithdrawalItemQuery: _q}
	sbuild.label = commissionwithdrawalitem.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CommissionWithdrawalItemSelect configured with the given aggregations.
func (_q *CommissionWithdrawalItemQuery) Aggregate(fns ...AggregateFunc) *CommissionWithdrawalItemSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CommissionWithdrawalItemQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !commissionwithdrawalitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CommissionWithdrawalItemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CommissionWithdrawalItem, error) {
	var (
		nodes       = []*CommissionWithdrawalItem{}
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withWithdrawal != nil,
			_q.withUser != nil,
			_q.withReward != nil,
			_q.withRechargeOrder != nil,
			_q.withCommissionLedgers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CommissionWithdrawalItem).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CommissionWithdrawalItem{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withWithdrawal; query != nil {
		if err := _q.loadWithdrawal(ctx, query, nodes, nil,
			func(n *CommissionWithdrawalItem, e *CommissionWithdrawal) { n.Edges.Withdrawal = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *CommissionWithdrawalItem, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withReward; query != nil {
		if err := _q.loadReward(ctx, query, nodes, nil,
			func(n *CommissionWithdrawalItem, e *CommissionReward) { n.Edges.Reward = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRechargeOrder; query != nil {
		if err := _q.loadRechargeOrder(ctx, query, nodes, nil,
			func(n *CommissionWithdrawalItem, e *RechargeOrder) { n.Edges.RechargeOrder = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCommissionLedgers; query != nil {
		if err := _q.loadCommissionLedgers(ctx, query, nodes,
			func(n *CommissionWithdrawalItem) { n.Edges.CommissionLedgers = []*CommissionLedger{} },
			func(n *CommissionWithdrawalItem, e *CommissionLedger) {
				n.Edges.CommissionLedgers = append(n.Edges.CommissionLedgers, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CommissionWithdrawalItemQuery) loadWithdrawal(ctx context.Context, query *CommissionWithdrawalQuery, nodes []*CommissionWithdrawalItem, init func(*CommissionWithdrawalItem), assign func(*CommissionWithdrawalItem, *CommissionWithdrawal)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CommissionWithdrawalItem)
	for i := range nodes {
		fk := nodes[i].WithdrawalID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(commissionwithdrawal.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "withdrawal_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CommissionWithdrawalItemQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*CommissionWithdrawalItem, init func(*CommissionWithdrawalItem), assign func(*CommissionWithdrawalItem, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CommissionWithdrawalItem)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CommissionWithdrawalItemQuery) loadReward(ctx context.Context, query *CommissionRewardQuery, nodes []*CommissionWithdrawalItem, init func(*CommissionWithdrawalItem), assign func(*CommissionWithdrawalItem, *CommissionReward)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CommissionWithdrawalItem)
	for i := range nodes {
		fk := nodes[i].RewardID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(commissionreward.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "reward_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CommissionWithdrawalItemQuery) loadRechargeOrder(ctx context.Context, query *RechargeOrderQuery, nodes []*CommissionWithdrawalItem, init func(*CommissionWithdrawalItem), assign func(*CommissionWithdrawalItem, *RechargeOrder)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CommissionWithdrawalItem)
	for i := range nodes {
		fk := nodes[i].RechargeOrderID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(rechargeorder.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "recharge_order_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CommissionWithdrawalItemQuery) loadCommissionLedgers(ctx context.Context, query *CommissionLedgerQuery, nodes []*CommissionWithdrawalItem, init func(*CommissionWithdrawalItem), assign func(*CommissionWithdrawalItem, *CommissionLedger)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*CommissionWithdrawalItem)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(commissionledger.FieldWithdrawalItemID)
	}
	query.Where(predicate.CommissionLedger(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(commissionwithdrawalitem.CommissionLedgersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.WithdrawalItemID
		if fk == nil {
			return fmt.Errorf(`foreign-key "withdrawal_item_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "withdrawal_item_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *CommissionWithdrawalItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CommissionWithdrawalItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(commissionwithdrawalitem.Table, commissionwithdrawalitem.Columns, sqlgraph.NewFieldSpec(commissionwithdrawalitem.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, commissionwithdrawalitem.FieldID)
		for i := range fields {
			if fields[i] != commissionwithdrawalitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withWithdrawal != nil {
			_spec.Node.AddColumnOnce(commissionwithdrawalitem.FieldWithdrawalID)
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(commissionwithdrawalitem.FieldUserID)
		}
		if _q.withReward != nil {
			_spec.Node.AddColumnOnce(commissionwithdrawalitem.FieldRewardID)
		}
		if _q.withRechargeOrder != nil {
			_spec.Node.AddColumnOnce(commissionwithdrawalitem.FieldRechargeOrderID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CommissionWithdrawalItemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(commissionwithdrawalitem.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = commissionwithdrawalitem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *CommissionWithdrawalItemQuery) ForUpdate(opts ...sql.LockOption) *CommissionWithdrawalItemQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *CommissionWithdrawalItemQuery) ForShare(opts ...sql.LockOption) *CommissionWithdrawalItemQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// CommissionWithdrawalItemGroupBy is the group-by builder for CommissionWithdrawalItem entities.
type CommissionWithdrawalItemGroupBy struct {
	selector
	build *CommissionWithdrawalItemQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CommissionWithdrawalItemGroupBy) Aggregate(fns ...AggregateFunc) *CommissionWithdrawalItemGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CommissionWithdrawalItemGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CommissionWithdrawalItemQuery, *CommissionWithdrawalItemGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CommissionWithdrawalItemGroupBy) sqlScan(ctx context.Context, root *CommissionWithdrawalItemQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CommissionWithdrawalItemSelect is the builder for selecting fields of CommissionWithdrawalItem entities.
type CommissionWithdrawalItemSelect struct {
	*CommissionWithdrawalItemQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CommissionWithdrawalItemSelect) Aggregate(fns ...AggregateFunc) *CommissionWithdrawalItemSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CommissionWithdrawalItemSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CommissionWithdrawalItemQuery, *CommissionWithdrawalItemSelect](ctx, _s.CommissionWithdrawalItemQuery, _s, _s.inters, v)
}

func (_s *CommissionWithdrawalItemSelect) sqlScan(ctx context.Context, root *CommissionWithdrawalItemQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
