// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/commissionledger"
	"github.com/Wei-Shaw/sub2api/ent/commissionreward"
	"github.com/Wei-Shaw/sub2api/ent/commissionwithdrawal"
	"github.com/Wei-Shaw/sub2api/ent/commissionwithdrawalitem"
	"github.com/Wei-Shaw/sub2api/ent/rechargeorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CommissionLedgerCreate is the builder for creating a CommissionLedger entity.
type CommissionLedgerCreate struct {
	config
	mutation *CommissionLedgerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *CommissionLedgerCreate) SetUserID(v int64) *CommissionLedgerCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRewardID sets the "reward_id" field.
func (_c *CommissionLedgerCreate) SetRewardID(v int64) *CommissionLedgerCreate {
	_c.mutation.SetRewardID(v)
	return _c
}

// SetNillableRewardID sets the "reward_id" field if the given value is not nil.
func (_c *CommissionLedgerCreate) SetNillableRewardID(v *int64) *CommissionLedgerCreate {
	if v != nil {
		_c.SetRewardID(*v)
	}
	return _c
}

// SetRechargeOrderID sets the "recharge_order_id" field.
func (_c *CommissionLedgerCreate) SetRechargeOrderID(v int64) *CommissionLedgerCreate {
	_c.mutation.SetRechargeOrderID(v)
	return _c
}

// SetNillableRechargeOrderID sets the "recharge_order_id" field if the given value is not nil.
func (_c *CommissionLedgerCreate) SetNillableRechargeOrderID(v *int64) *CommissionLedgerCreate {
	if v != nil {
		_c.SetRechargeOrderID(*v)
	}
	return _c
}

// SetWithdrawalID sets the "withdrawal_id" field.
func (_c *CommissionLedgerCreate) SetWithdrawalID(v int64) *CommissionLedgerCreate {
	_c.mutation.SetWithdrawalID(v)
	return _c
}

// SetNillableWithdrawalID sets the "withdrawal_id" field if the given value is not nil.
func (_c *CommissionLedgerCreate) SetNillableWithdrawalID(v *int64) *CommissionLedgerCreate {
	if v != nil {
		_c.SetWithdrawalID(*v)
	}
	return _c
}

// SetWithdrawalItemID sets the "withdrawal_item_id" field.
func (_c *CommissionLedgerCreate) SetWithdrawalItemID(v int64) *CommissionLedgerCreate {
	_c.mutation.SetWithdrawalItemID(v)
	return _c
}

// SetNillableWithdrawalItemID sets the "withdrawal_item_id" field if the given value is not nil.
func (_c *CommissionLedgerCreate) SetNillableWithdrawalItemID(v *int64) *CommissionLedgerCreate {
	if v != nil {
		_c.SetWithdrawalItemID(*v)
	}
	return _c
}

// SetEntryType sets the "entry_type" field.
func (_c *CommissionLedgerCreate) SetEntryType(v string) *CommissionLedgerCreate {
	_c.mutation.SetEntryType(v)
	return _c
}

// SetBucket sets the "bucket" field.
func (_c *CommissionLedgerCreate) SetBucket(v string) *CommissionLedgerCreate {
	_c.mutation.SetBucket(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *CommissionLedgerCreate) SetAmount(v float64) *CommissionLedgerCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *CommissionLedgerCreate) SetNillableAmount(v *float64) *CommissionLedgerCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *CommissionLedgerCreate) SetCurrency(v string) *CommissionLedgerCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *CommissionLedgerCreate) SetNillableCurrency(v *string) *CommissionLedgerCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *CommissionLedgerCreate) SetIdempotencyKey(v string) *CommissionLedgerCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_c *CommissionLedgerCreate) SetNillableIdempotencyKey(v *string) *CommissionLedgerCreate {
	if v != nil {
		_c.SetIdempotencyKey(*v)
	}
	return _c
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_c *CommissionLedgerCreate) SetOperatorUserID(v int64) *CommissionLedgerCreate {
	_c.mutation.SetOperatorUserID(v)
	return _c
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_c *CommissionLedgerCreate) SetNillableOperatorUserID(v *int64) *CommissionLedgerCreate {
	if v != nil {
		_c.SetOperatorUserID(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *CommissionLedgerCreate) SetRemark(v string) *CommissionLedgerCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *CommissionLedgerCreate) SetNillableRemark(v *string) *CommissionLedgerCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetMetadataJSON sets the "metadata_json" field.
func (_c *CommissionLedgerCreate) SetMetadataJSON(v string) *CommissionLedgerCreate {
	_c.mutation.SetMetadataJSON(v)
	return _c
}

// SetNillableMetadataJSON sets the "metadata_json" field if the given value is not nil.
func (_c *CommissionLedgerCreate) SetNillableMetadataJSON(v *string) *CommissionLedgerCreate {
	if v != nil {
		_c.SetMetadataJSON(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CommissionLedgerCreate) SetCreatedAt(v time.Time) *CommissionLedgerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CommissionLedgerCreate) SetNillableCreatedAt(v *time.Time) *CommissionLedgerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *CommissionLedgerCreate) SetUser(v *User) *CommissionLedgerCreate {
	return _c.SetUserID(v.ID)
}

// SetReward sets the "reward" edge to the CommissionReward entity.
func (_c *CommissionLedgerCreate) SetReward(v *CommissionReward) *CommissionLedgerCreate {
	return _c.SetRewardID(v.ID)
}

// SetRechargeOrder sets the "recharge_order" edge to the RechargeOrder entity.
func (_c *CommissionLedgerCreate) SetRechargeOrder(v *RechargeOrder) *CommissionLedgerCreate {
	return _c.SetRechargeOrderID(v.ID)
}

// SetWithdrawal sets the "withdrawal" edge to the CommissionWithdrawal entity.
func (_c *CommissionLedgerCreate) SetWithdrawal(v *CommissionWithdrawal) *CommissionLedgerCreate {
	return _c.SetWithdrawalID(v.ID)
}

// SetWithdrawalItem sets the "withdrawal_item" edge to the CommissionWithdrawalItem entity.
func (_c *CommissionLedgerCreate) SetWithdrawalItem(v *CommissionWithdrawalItem) *CommissionLedgerCreate {
	return _c.SetWithdrawalItemID(v.ID)
}

// Mutation returns the CommissionLedgerMutation object of the builder.
func (_c *CommissionLedgerCreate) Mutation() *CommissionLedgerMutation {
	return _c.mutation
}

// Save creates the CommissionLedger in the database.
func (_c *CommissionLedgerCreate) Save(ctx context.Context) (*CommissionLedger, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CommissionLedgerCreate) SaveX(ctx context.Context) *CommissionLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CommissionLedgerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CommissionLedgerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CommissionLedgerCreate) defaults() {
	if _, ok := _c.mutation.Amount(); !ok {
		v := commissionledger.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := commissionledger.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := commissionledger.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CommissionLedgerCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CommissionLedger.user_id"`)}
	}
	if _, ok := _c.mutation.EntryType(); !ok {
		return &ValidationError{Name: "entry_type", err: errors.New(`ent: missing required field "CommissionLedger.entry_type"`)}
	}
	if v, ok := _c.mutation.EntryType(); ok {
		if err := commissionledger.EntryTypeValidator(v); err != nil {
			return &ValidationError{Name: "entry_type", err: fmt.Errorf(`ent: validator failed for field "CommissionLedger.entry_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Bucket(); !ok {
		return &ValidationError{Name: "bucket", err: errors.New(`ent: missing required field "CommissionLedger.bucket"`)}
	}
	if v, ok := _c.mutation.Bucket(); ok {
		if err := commissionledger.BucketValidator(v); err != nil {
			return &ValidationError{Name: "bucket", err: fmt.Errorf(`ent: validator failed for field "CommissionLedger.bucket": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "CommissionLedger.amount"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "CommissionLedger.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := commissionledger.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "CommissionLedger.currency": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := commissionledger.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "CommissionLedger.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CommissionLedger.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "CommissionLedger.user"`)}
	}
	return nil
}

func (_c *CommissionLedgerCreate) sqlSave(ctx context.Context) (*CommissionLedger, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CommissionLedgerCreate) createSpec() (*CommissionLedger, *sqlgraph.CreateSpec) {
	var (
		_node = &CommissionLedger{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(commissionledger.Table, sqlgraph.NewFieldSpec(commissionledger.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.EntryType(); ok {
		_spec.SetField(commissionledger.FieldEntryType, field.TypeString, value)
		_node.EntryType = value
	}
	if value, ok := _c.mutation.Bucket(); ok {
		_spec.SetField(commissionledger.FieldBucket, field.TypeString, value)
		_node.Bucket = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(commissionledger.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(commissionledger.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(commissionledger.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = &value
	}
	if value, ok := _c.mutation.OperatorUserID(); ok {
		_spec.SetField(commissionledger.FieldOperatorUserID, field.TypeInt64, value)
		_node.OperatorUserID = &value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(commissionledger.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if value, ok := _c.mutation.MetadataJSON(); ok {
		_spec.SetField(commissionledger.FieldMetadataJSON, field.TypeString, value)
		_node.MetadataJSON = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(commissionledger.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.UserTable,
			Columns: []string{commissionledger.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RewardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.RewardTable,
			Columns: []string{commissionledger.RewardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commissionreward.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RewardID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RechargeOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.RechargeOrderTable,
			Columns: []string{commissionledger.RechargeOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RechargeOrderID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WithdrawalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.WithdrawalTable,
			Columns: []string{commissionledger.WithdrawalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commissionwithdrawal.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WithdrawalID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WithdrawalItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.WithdrawalItemTable,
			Columns: []string{commissionledger.WithdrawalItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commissionwithdrawalitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WithdrawalItemID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CommissionLedger.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CommissionLedgerUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *CommissionLedgerCreate) OnConflict(opts ...sql.ConflictOption) *CommissionLedgerUpsertOne {
	_c.conflict = opts
	return &CommissionLedgerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CommissionLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CommissionLedgerCreate) OnConflictColumns(columns ...string) *CommissionLedgerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CommissionLedgerUpsertOne{
		create: _c,
	}
}

type (
	// CommissionLedgerUpsertOne is the builder for "upsert"-ing
	//  one CommissionLedger node.
	CommissionLedgerUpsertOne struct {
		create *CommissionLedgerCreate
	}

	// CommissionLedgerUpsert is the "OnConflict" setter.
	CommissionLedgerUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *CommissionLedgerUpsert) SetUserID(v int64) *CommissionLedgerUpsert {
	u.Set(commissionledger.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CommissionLedgerUpsert) UpdateUserID() *CommissionLedgerUpsert {
	u.SetExcluded(commissionledger.FieldUserID)
	return u
}

// SetRewardID sets the "reward_id" field.
func (u *CommissionLedgerUpsert) SetRewardID(v int64) *CommissionLedgerUpsert {
	u.Set(commissionledger.FieldRewardID, v)
	return u
}

// UpdateRewardID sets the "reward_id" field to the value that was provided on create.
func (u *CommissionLedgerUpsert) UpdateRewardID() *CommissionLedgerUpsert {
	u.SetExcluded(commissionledger.FieldRewardID)
	return u
}

// ClearRewardID clears the value of the "reward_id" field.
func (u *CommissionLedgerUpsert) ClearRewardID() *CommissionLedgerUpsert {
	u.SetNull(commissionledger.FieldRewardID)
	return u
}

// SetRechargeOrderID sets the "recharge_order_id" field.
func (u *CommissionLedgerUpsert) SetRechargeOrderID(v int64) *CommissionLedgerUpsert {
	u.Set(commissionledger.FieldRechargeOrderID, v)
	return u
}

// UpdateRechargeOrderID sets the "recharge_order_id" field to the value that was provided on create.
func (u *CommissionLedgerUpsert) UpdateRechargeOrderID() *CommissionLedgerUpsert {
	u.SetExcluded(commissionledger.FieldRechargeOrderID)
	return u
}

// ClearRechargeOrderID clears the value of the "recharge_order_id" field.
func (u *CommissionLedgerUpsert) ClearRechargeOrderID() *CommissionLedgerUpsert {
	u.SetNull(commissionledger.FieldRechargeOrderID)
	return u
}

// SetWithdrawalID sets the "withdrawal_id" field.
func (u *CommissionLedgerUpsert) SetWithdrawalID(v int64) *CommissionLedgerUpsert {
	u.Set(commissionledger.FieldWithdrawalID, v)
	return u
}

// UpdateWithdrawalID sets the "withdrawal_id" field to the value that was provided on create.
func (u *CommissionLedgerUpsert) UpdateWithdrawalID() *CommissionLedgerUpsert {
	u.SetExcluded(commissionledger.FieldWithdrawalID)
	return u
}

// ClearWithdrawalID clears the value of the "withdrawal_id" field.
func (u *CommissionLedgerUpsert) ClearWithdrawalID() *CommissionLedgerUpsert {
	u.SetNull(commissionledger.FieldWithdrawalID)
	return u
}

// SetWithdrawalItemID sets the "withdrawal_item_id" field.
func (u *CommissionLedgerUpsert) SetWithdrawalItemID(v int64) *CommissionLedgerUpsert {
	u.Set(commissionledger.FieldWithdrawalItemID, v)
	return u
}

// UpdateWithdrawalItemID sets the "withdrawal_item_id" field to the value that was provided on create.
func (u *CommissionLedgerUpsert) UpdateWithdrawalItemID() *CommissionLedgerUpsert {
	u.SetExcluded(commissionledger.FieldWithdrawalItemID)
	return u
}

// ClearWithdrawalItemID clears the value of the "withdrawal_item_id" field.
func (u *CommissionLedgerUpsert) ClearWithdrawalItemID() *CommissionLedgerUpsert {
	u.SetNull(commissionledger.FieldWithdrawalItemID)
	return u
}

// SetEntryType sets the "entry_type" field.
func (u *CommissionLedgerUpsert) SetEntryType(v string) *CommissionLedgerUpsert {
	u.Set(commissionledger.FieldEntryType, v)
	return u
}

// UpdateEntryType sets the "entry_type" field to the value that was provided on create.
func (u *CommissionLedgerUpsert) UpdateEntryType() *CommissionLedgerUpsert {
	u.SetExcluded(commissionledger.FieldEntryType)
	return u
}

// SetBucket sets the "bucket" field.
func (u *CommissionLedgerUpsert) SetBucket(v string) *CommissionLedgerUpsert {
	u.Set(commissionledger.FieldBucket, v)
	return u
}

// UpdateBucket sets the "bucket" field to the value that was provided on create.
func (u *CommissionLedgerUpsert) UpdateBucket() *CommissionLedgerUpsert {
	u.SetExcluded(commissionledger.FieldBucket)
	return u
}

// SetAmount sets the "amount" field.
func (u *CommissionLedgerUpsert) SetAmount(v float64) *CommissionLedgerUpsert {
	u.Set(commissionledger.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CommissionLedgerUpsert) UpdateAmount() *CommissionLedgerUpsert {
	u.SetExcluded(commissionledger.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *CommissionLedgerUpsert) AddAmount(v float64) *CommissionLedgerUpsert {
	u.Add(commissionledger.FieldAmount, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *CommissionLedgerUpsert) SetCurrency(v string) *CommissionLedgerUpsert {
	u.Set(commissionledger.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *CommissionLedgerUpsert) UpdateCurrency() *CommissionLedgerUpsert {
	u.SetExcluded(commissionledger.FieldCurrency)
	return u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *CommissionLedgerUpsert) SetIdempotencyKey(v string) *CommissionLedgerUpsert {
	u.Set(commissionledger.FieldIdempotencyKey, v)
	return u
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *CommissionLedgerUpsert) UpdateIdempotencyKey() *CommissionLedgerUpsert {
	u.SetExcluded(commissionledger.FieldIdempotencyKey)
	return u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *CommissionLedgerUpsert) ClearIdempotencyKey() *CommissionLedgerUpsert {
	u.SetNull(commissionledger.FieldIdempotencyKey)
	return u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (u *CommissionLedgerUpsert) SetOperatorUserID(v int64) *CommissionLedgerUpsert {
	u.Set(commissionledger.FieldOperatorUserID, v)
	return u
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *CommissionLedgerUpsert) UpdateOperatorUserID() *CommissionLedgerUpsert {
	u.SetExcluded(commissionledger.FieldOperatorUserID)
	return u
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *CommissionLedgerUpsert) AddOperatorUserID(v int64) *CommissionLedgerUpsert {
	u.Add(commissionledger.FieldOperatorUserID, v)
	return u
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (u *CommissionLedgerUpsert) ClearOperatorUserID() *CommissionLedgerUpsert {
	u.SetNull(commissionledger.FieldOperatorUserID)
	return u
}

// SetRemark sets the "remark" field.
func (u *CommissionLedgerUpsert) SetRemark(v string) *CommissionLedgerUpsert {
	u.Set(commissionledger.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *CommissionLedgerUpsert) UpdateRemark() *CommissionLedgerUpsert {
	u.SetExcluded(commissionledger.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *CommissionLedgerUpsert) ClearRemark() *CommissionLedgerUpsert {
	u.SetNull(commissionledger.FieldRemark)
	return u
}

// SetMetadataJSON sets the "metadata_json" field.
func (u *CommissionLedgerUpsert) SetMetadataJSON(v string) *CommissionLedgerUpsert {
	u.Set(commissionledger.FieldMetadataJSON, v)
	return u
}

// UpdateMetadataJSON sets the "metadata_json" field to the value that was provided on create.
func (u *CommissionLedgerUpsert) UpdateMetadataJSON() *CommissionLedgerUpsert {
	u.SetExcluded(commissionledger.FieldMetadataJSON)
	return u
}

// ClearMetadataJSON clears the value of the "metadata_json" field.
func (u *CommissionLedgerUpsert) ClearMetadataJSON() *CommissionLedgerUpsert {
	u.SetNull(commissionledger.FieldMetadataJSON)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CommissionLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CommissionLedgerUpsertOne) UpdateNewValues() *CommissionLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(commissionledger.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CommissionLedger.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CommissionLedgerUpsertOne) Ignore() *CommissionLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CommissionLedgerUpsertOne) DoNothing() *CommissionLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CommissionLedgerCreate.OnConflict
// documentation for more info.
func (u *CommissionLedgerUpsertOne) Update(set func(*CommissionLedgerUpsert)) *CommissionLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CommissionLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *CommissionLedgerUpsertOne) SetUserID(v int64) *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CommissionLedgerUpsertOne) UpdateUserID() *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateUserID()
	})
}

// SetRewardID sets the "reward_id" field.
func (u *CommissionLedgerUpsertOne) SetRewardID(v int64) *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetRewardID(v)
	})
}

// UpdateRewardID sets the "reward_id" field to the value that was provided on create.
func (u *CommissionLedgerUpsertOne) UpdateRewardID() *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateRewardID()
	})
}

// ClearRewardID clears the value of the "reward_id" field.
func (u *CommissionLedgerUpsertOne) ClearRewardID() *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.ClearRewardID()
	})
}

// SetRechargeOrderID sets the "recharge_order_id" field.
func (u *CommissionLedgerUpsertOne) SetRechargeOrderID(v int64) *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetRechargeOrderID(v)
	})
}

// UpdateRechargeOrderID sets the "recharge_order_id" field to the value that was provided on create.
func (u *CommissionLedgerUpsertOne) UpdateRechargeOrderID() *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateRechargeOrderID()
	})
}

// ClearRechargeOrderID clears the value of the "recharge_order_id" field.
func (u *CommissionLedgerUpsertOne) ClearRechargeOrderID() *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.ClearRechargeOrderID()
	})
}

// SetWithdrawalID sets the "withdrawal_id" field.
func (u *CommissionLedgerUpsertOne) SetWithdrawalID(v int64) *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetWithdrawalID(v)
	})
}

// UpdateWithdrawalID sets the "withdrawal_id" field to the value that was provided on create.
func (u *CommissionLedgerUpsertOne) UpdateWithdrawalID() *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateWithdrawalID()
	})
}

// ClearWithdrawalID clears the value of the "withdrawal_id" field.
func (u *CommissionLedgerUpsertOne) ClearWithdrawalID() *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.ClearWithdrawalID()
	})
}

// SetWithdrawalItemID sets the "withdrawal_item_id" field.
func (u *CommissionLedgerUpsertOne) SetWithdrawalItemID(v int64) *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetWithdrawalItemID(v)
	})
}

// UpdateWithdrawalItemID sets the "withdrawal_item_id" field to the value that was provided on create.
func (u *CommissionLedgerUpsertOne) UpdateWithdrawalItemID() *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateWithdrawalItemID()
	})
}

// ClearWithdrawalItemID clears the value of the "withdrawal_item_id" field.
func (u *CommissionLedgerUpsertOne) ClearWithdrawalItemID() *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.ClearWithdrawalItemID()
	})
}

// SetEntryType sets the "entry_type" field.
func (u *CommissionLedgerUpsertOne) SetEntryType(v string) *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetEntryType(v)
	})
}

// UpdateEntryType sets the "entry_type" field to the value that was provided on create.
func (u *CommissionLedgerUpsertOne) UpdateEntryType() *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateEntryType()
	})
}

// SetBucket sets the "bucket" field.
func (u *CommissionLedgerUpsertOne) SetBucket(v string) *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetBucket(v)
	})
}

// UpdateBucket sets the "bucket" field to the value that was provided on create.
func (u *CommissionLedgerUpsertOne) UpdateBucket() *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateBucket()
	})
}

// SetAmount sets the "amount" field.
func (u *CommissionLedgerUpsertOne) SetAmount(v float64) *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *CommissionLedgerUpsertOne) AddAmount(v float64) *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CommissionLedgerUpsertOne) UpdateAmount() *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *CommissionLedgerUpsertOne) SetCurrency(v string) *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *CommissionLedgerUpsertOne) UpdateCurrency() *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateCurrency()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *CommissionLedgerUpsertOne) SetIdempotencyKey(v string) *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *CommissionLedgerUpsertOne) UpdateIdempotencyKey() *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *CommissionLedgerUpsertOne) ClearIdempotencyKey() *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.ClearIdempotencyKey()
	})
}

// SetOperatorUserID sets the "operator_user_id" field.
func (u *CommissionLedgerUpsertOne) SetOperatorUserID(v int64) *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetOperatorUserID(v)
	})
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *CommissionLedgerUpsertOne) AddOperatorUserID(v int64) *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.AddOperatorUserID(v)
	})
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *CommissionLedgerUpsertOne) UpdateOperatorUserID() *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateOperatorUserID()
	})
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (u *CommissionLedgerUpsertOne) ClearOperatorUserID() *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.ClearOperatorUserID()
	})
}

// SetRemark sets the "remark" field.
func (u *CommissionLedgerUpsertOne) SetRemark(v string) *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *CommissionLedgerUpsertOne) UpdateRemark() *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *CommissionLedgerUpsertOne) ClearRemark() *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.ClearRemark()
	})
}

// SetMetadataJSON sets the "metadata_json" field.
func (u *CommissionLedgerUpsertOne) SetMetadataJSON(v string) *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetMetadataJSON(v)
	})
}

// UpdateMetadataJSON sets the "metadata_json" field to the value that was provided on create.
func (u *CommissionLedgerUpsertOne) UpdateMetadataJSON() *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateMetadataJSON()
	})
}

// ClearMetadataJSON clears the value of the "metadata_json" field.
func (u *CommissionLedgerUpsertOne) ClearMetadataJSON() *CommissionLedgerUpsertOne {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.ClearMetadataJSON()
	})
}

// Exec executes the query.
func (u *CommissionLedgerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CommissionLedgerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CommissionLedgerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CommissionLedgerUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CommissionLedgerUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CommissionLedgerCreateBulk is the builder for creating many CommissionLedger entities in bulk.
type CommissionLedgerCreateBulk struct {
	config
	err      error
	builders []*CommissionLedgerCreate
	conflict []sql.ConflictOption
}

// Save creates the CommissionLedger entities in the database.
func (_c *CommissionLedgerCreateBulk) Save(ctx context.Context) ([]*CommissionLedger, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CommissionLedger, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CommissionLedgerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CommissionLedgerCreateBulk) SaveX(ctx context.Context) []*CommissionLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CommissionLedgerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CommissionLedgerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CommissionLedger.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CommissionLedgerUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *CommissionLedgerCreateBulk) OnConflict(opts ...sql.ConflictOption) *CommissionLedgerUpsertBulk {
	_c.conflict = opts
	return &CommissionLedgerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CommissionLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CommissionLedgerCreateBulk) OnConflictColumns(columns ...string) *CommissionLedgerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CommissionLedgerUpsertBulk{
		create: _c,
	}
}

// CommissionLedgerUpsertBulk is the builder for "upsert"-ing
// a bulk of CommissionLedger nodes.
type CommissionLedgerUpsertBulk struct {
	create *CommissionLedgerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CommissionLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CommissionLedgerUpsertBulk) UpdateNewValues() *CommissionLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(commissionledger.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CommissionLedger.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CommissionLedgerUpsertBulk) Ignore() *CommissionLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CommissionLedgerUpsertBulk) DoNothing() *CommissionLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CommissionLedgerCreateBulk.OnConflict
// documentation for more info.
func (u *CommissionLedgerUpsertBulk) Update(set func(*CommissionLedgerUpsert)) *CommissionLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CommissionLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *CommissionLedgerUpsertBulk) SetUserID(v int64) *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CommissionLedgerUpsertBulk) UpdateUserID() *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateUserID()
	})
}

// SetRewardID sets the "reward_id" field.
func (u *CommissionLedgerUpsertBulk) SetRewardID(v int64) *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetRewardID(v)
	})
}

// UpdateRewardID sets the "reward_id" field to the value that was provided on create.
func (u *CommissionLedgerUpsertBulk) UpdateRewardID() *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateRewardID()
	})
}

// ClearRewardID clears the value of the "reward_id" field.
func (u *CommissionLedgerUpsertBulk) ClearRewardID() *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.ClearRewardID()
	})
}

// SetRechargeOrderID sets the "recharge_order_id" field.
func (u *CommissionLedgerUpsertBulk) SetRechargeOrderID(v int64) *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetRechargeOrderID(v)
	})
}

// UpdateRechargeOrderID sets the "recharge_order_id" field to the value that was provided on create.
func (u *CommissionLedgerUpsertBulk) UpdateRechargeOrderID() *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateRechargeOrderID()
	})
}

// ClearRechargeOrderID clears the value of the "recharge_order_id" field.
func (u *CommissionLedgerUpsertBulk) ClearRechargeOrderID() *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.ClearRechargeOrderID()
	})
}

// SetWithdrawalID sets the "withdrawal_id" field.
func (u *CommissionLedgerUpsertBulk) SetWithdrawalID(v int64) *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetWithdrawalID(v)
	})
}

// UpdateWithdrawalID sets the "withdrawal_id" field to the value that was provided on create.
func (u *CommissionLedgerUpsertBulk) UpdateWithdrawalID() *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateWithdrawalID()
	})
}

// ClearWithdrawalID clears the value of the "withdrawal_id" field.
func (u *CommissionLedgerUpsertBulk) ClearWithdrawalID() *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.ClearWithdrawalID()
	})
}

// SetWithdrawalItemID sets the "withdrawal_item_id" field.
func (u *CommissionLedgerUpsertBulk) SetWithdrawalItemID(v int64) *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetWithdrawalItemID(v)
	})
}

// UpdateWithdrawalItemID sets the "withdrawal_item_id" field to the value that was provided on create.
func (u *CommissionLedgerUpsertBulk) UpdateWithdrawalItemID() *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateWithdrawalItemID()
	})
}

// ClearWithdrawalItemID clears the value of the "withdrawal_item_id" field.
func (u *CommissionLedgerUpsertBulk) ClearWithdrawalItemID() *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.ClearWithdrawalItemID()
	})
}

// SetEntryType sets the "entry_type" field.
func (u *CommissionLedgerUpsertBulk) SetEntryType(v string) *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetEntryType(v)
	})
}

// UpdateEntryType sets the "entry_type" field to the value that was provided on create.
func (u *CommissionLedgerUpsertBulk) UpdateEntryType() *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateEntryType()
	})
}

// SetBucket sets the "bucket" field.
func (u *CommissionLedgerUpsertBulk) SetBucket(v string) *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetBucket(v)
	})
}

// UpdateBucket sets the "bucket" field to the value that was provided on create.
func (u *CommissionLedgerUpsertBulk) UpdateBucket() *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateBucket()
	})
}

// SetAmount sets the "amount" field.
func (u *CommissionLedgerUpsertBulk) SetAmount(v float64) *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *CommissionLedgerUpsertBulk) AddAmount(v float64) *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CommissionLedgerUpsertBulk) UpdateAmount() *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *CommissionLedgerUpsertBulk) SetCurrency(v string) *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *CommissionLedgerUpsertBulk) UpdateCurrency() *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateCurrency()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *CommissionLedgerUpsertBulk) SetIdempotencyKey(v string) *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *CommissionLedgerUpsertBulk) UpdateIdempotencyKey() *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *CommissionLedgerUpsertBulk) ClearIdempotencyKey() *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.ClearIdempotencyKey()
	})
}

// SetOperatorUserID sets the "operator_user_id" field.
func (u *CommissionLedgerUpsertBulk) SetOperatorUserID(v int64) *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetOperatorUserID(v)
	})
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *CommissionLedgerUpsertBulk) AddOperatorUserID(v int64) *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.AddOperatorUserID(v)
	})
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *CommissionLedgerUpsertBulk) UpdateOperatorUserID() *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateOperatorUserID()
	})
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (u *CommissionLedgerUpsertBulk) ClearOperatorUserID() *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.ClearOperatorUserID()
	})
}

// SetRemark sets the "remark" field.
func (u *CommissionLedgerUpsertBulk) SetRemark(v string) *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *CommissionLedgerUpsertBulk) UpdateRemark() *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *CommissionLedgerUpsertBulk) ClearRemark() *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.ClearRemark()
	})
}

// SetMetadataJSON sets the "metadata_json" field.
func (u *CommissionLedgerUpsertBulk) SetMetadataJSON(v string) *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.SetMetadataJSON(v)
	})
}

// UpdateMetadataJSON sets the "metadata_json" field to the value that was provided on create.
func (u *CommissionLedgerUpsertBulk) UpdateMetadataJSON() *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.UpdateMetadataJSON()
	})
}

// ClearMetadataJSON clears the value of the "metadata_json" field.
func (u *CommissionLedgerUpsertBulk) ClearMetadataJSON() *CommissionLedgerUpsertBulk {
	return u.Update(func(s *CommissionLedgerUpsert) {
		s.ClearMetadataJSON()
	})
}

// Exec executes the query.
func (u *CommissionLedgerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CommissionLedgerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CommissionLedgerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CommissionLedgerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
