// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/commissionledger"
	"github.com/Wei-Shaw/sub2api/ent/commissionreward"
	"github.com/Wei-Shaw/sub2api/ent/commissionwithdrawal"
	"github.com/Wei-Shaw/sub2api/ent/commissionwithdrawalitem"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rechargeorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CommissionLedgerQuery is the builder for querying CommissionLedger entities.
type CommissionLedgerQuery struct {
	config
	ctx                *QueryContext
	order              []commissionledger.OrderOption
	inters             []Interceptor
	predicates         []predicate.CommissionLedger
	withUser           *UserQuery
	withReward         *CommissionRewardQuery
	withRechargeOrder  *RechargeOrderQuery
	withWithdrawal     *CommissionWithdrawalQuery
	withWithdrawalItem *CommissionWithdrawalItemQuery
	modifiers          []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CommissionLedgerQuery builder.
func (_q *CommissionLedgerQuery) Where(ps ...predicate.CommissionLedger) *CommissionLedgerQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CommissionLedgerQuery) Limit(limit int) *CommissionLedgerQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CommissionLedgerQuery) Offset(offset int) *CommissionLedgerQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CommissionLedgerQuery) Unique(unique bool) *CommissionLedgerQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CommissionLedgerQuery) Order(o ...commissionledger.OrderOption) *CommissionLedgerQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *CommissionLedgerQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commissionledger.Table, commissionledger.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, commissionledger.UserTable, commissionledger.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryReward chains the current query on the "reward" edge.
func (_q *CommissionLedgerQuery) QueryReward() *CommissionRewardQuery {
	query := (&CommissionRewardClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commissionledger.Table, commissionledger.FieldID, selector),
			sqlgraph.To(commissionreward.Table, commissionreward.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, commissionledger.RewardTable, commissionledger.RewardColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRechargeOrder chains the current query on the "recharge_order" edge.
func (_q *CommissionLedgerQuery) QueryRechargeOrder() *RechargeOrderQuery {
	query := (&RechargeOrderClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commissionledger.Table, commissionledger.FieldID, selector),
			sqlgraph.To(rechargeorder.Table, rechargeorder.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, commissionledger.RechargeOrderTable, commissionledger.RechargeOrderColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWithdrawal chains the current query on the "withdrawal" edge.
func (_q *CommissionLedgerQuery) QueryWithdrawal() *CommissionWithdrawalQuery {
	query := (&CommissionWithdrawalClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commissionledger.Table, commissionledger.FieldID, selector),
			sqlgraph.To(commissionwithdrawal.Table, commissionwithdrawal.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, commissionledger.WithdrawalTable, commissionledger.WithdrawalColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWithdrawalItem chains the current query on the "withdrawal_item" edge.
func (_q *CommissionLedgerQuery) QueryWithdrawalItem() *CommissionWithdrawalItemQuery {
	query := (&CommissionWithdrawalItemClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commissionledger.Table, commissionledger.FieldID, selector),
			sqlgraph.To(commissionwithdrawalitem.Table, commissionwithdrawalitem.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, commissionledger.WithdrawalItemTable, commissionledger.WithdrawalItemColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CommissionLedger entity from the query.
// Returns a *NotFoundError when no CommissionLedger was found.
func (_q *CommissionLedgerQuery) First(ctx context.Context) (*CommissionLedger, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{commissionledger.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CommissionLedgerQuery) FirstX(ctx context.Context) *CommissionLedger {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CommissionLedger ID from the query.
// Returns a *NotFoundError when no CommissionLedger ID was found.
func (_q *CommissionLedgerQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{commissionledger.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CommissionLedgerQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CommissionLedger entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CommissionLedger entity is found.
// Returns a *NotFoundError when no CommissionLedger entities are found.
func (_q *CommissionLedgerQuery) Only(ctx context.Context) (*CommissionLedger, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{commissionledger.Label}
	default:
		return nil, &NotSingularError{commissionledger.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CommissionLedgerQuery) OnlyX(ctx context.Context) *CommissionLedger {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CommissionLedger ID in the query.
// Returns a *NotSingularError when more than one CommissionLedger ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CommissionLedgerQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{commissionledger.Label}
	default:
		err = &NotSingularError{commissionledger.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CommissionLedgerQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CommissionLedgers.
func (_q *CommissionLedgerQuery) All(ctx context.Context) ([]*CommissionLedger, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CommissionLedger, *CommissionLedgerQuery]()
	return withInterceptors[[]*CommissionLedger](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CommissionLedgerQuery) AllX(ctx context.Context) []*CommissionLedger {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CommissionLedger IDs.
func (_q *CommissionLedgerQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(commissionledger.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CommissionLedgerQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CommissionLedgerQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CommissionLedgerQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CommissionLedgerQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CommissionLedgerQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CommissionLedgerQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CommissionLedgerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CommissionLedgerQuery) Clone() *CommissionLedgerQuery {
	if _q == nil {
		return nil
	}
	return &CommissionLedgerQuery{
		config:             _q.config,
		ctx:                _q.ctx.Clone(),
		order:              append([]commissionledger.OrderOption{}, _q.order...),
		inters:             append([]Interceptor{}, _q.inters...),
		predicates:         append([]predicate.CommissionLedger{}, _q.predicates...),
		withUser:           _q.withUser.Clone(),
		withReward:         _q.withReward.Clone(),
		withRechargeOrder:  _q.withRechargeOrder.Clone(),
		withWithdrawal:     _q.withWithdrawal.Clone(),
		withWithdrawalItem: _q.withWithdrawalItem.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CommissionLedgerQuery) WithUser(opts ...func(*UserQuery)) *CommissionLedgerQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithReward tells the query-builder to eager-load the nodes that are connected to
// the "reward" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CommissionLedgerQuery) WithReward(opts ...func(*CommissionRewardQuery)) *CommissionLedgerQuery {
	query := (&CommissionRewardClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withReward = query
	return _q
}

// WithRechargeOrder tells the query-builder to eager-load the nodes that are connected to
// the "recharge_order" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CommissionLedgerQuery) WithRechargeOrder(opts ...func(*RechargeOrderQuery)) *CommissionLedgerQuery {
	query := (&RechargeOrderClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRechargeOrder = query
	return _q
}

// WithWithdrawal tells the query-builder to eager-load the nodes that are connected to
// the "withdrawal" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CommissionLedgerQuery) WithWithdrawal(opts ...func(*CommissionWithdrawalQuery)) *CommissionLedgerQuery {
	query := (&CommissionWithdrawalClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWithdrawal = query
	return _q
}

// WithWithdrawalItem tells the query-builder to eager-load the nodes that are connected to
// the "withdrawal_item" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CommissionLedgerQuery) WithWithdrawalItem(opts ...func(*CommissionWithdrawalItemQuery)) *CommissionLedgerQuery {
	query := (&CommissionWithdrawalItemClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWithdrawalItem = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CommissionLedger.Query().
//		GroupBy(commissionledger.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CommissionLedgerQuery) GroupBy(field string, fields ...string) *CommissionLedgerGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CommissionLedgerGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = commissionledger.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//	}
//
//	client.CommissionLedger.Query().
//		Select(commissionledger.FieldUserID).
//		Scan(ctx, &v)
func (_q *CommissionLedgerQuery) Select(fields ...string) *CommissionLedgerSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CommissionLedgerSelect{CommissionLedgerQuery: _q}
	sbuild.label = commissionledger.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CommissionLedgerSelect configured with the given aggregations.
func (_q *CommissionLedgerQuery) Aggregate(fns ...AggregateFunc) *CommissionLedgerSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CommissionLedgerQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !commissionledger.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CommissionLedgerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CommissionLedger, error) {
	var (
		nodes       = []*CommissionLedger{}
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withUser != nil,
			_q.withReward != nil,
			_q.withRechargeOrder != nil,
			_q.withWithdrawal != nil,
			_q.withWithdrawalItem != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CommissionLedger).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CommissionLedger{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *CommissionLedger, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withReward; query != nil {
		if err := _q.loadReward(ctx, query, nodes, nil,
			func(n *CommissionLedger, e *CommissionReward) { n.Edges.Reward = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRechargeOrder; query != nil {
		if err := _q.loadRechargeOrder(ctx, query, nodes, nil,
			func(n *CommissionLedger, e *RechargeOrder) { n.Edges.RechargeOrder = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withWithdrawal; query != nil {
		if err := _q.loadWithdrawal(ctx, query, nodes, nil,
			func(n *CommissionLedger, e *CommissionWithdrawal) { n.Edges.Withdrawal = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withWithdrawalItem; query != nil {
		if err := _q.loadWithdrawalItem(ctx, query, nodes, nil,
			func(n *CommissionLedger, e *CommissionWithdrawalItem) { n.Edges.WithdrawalItem = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CommissionLedgerQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*CommissionLedger, init func(*CommissionLedger), assign func(*CommissionLedger, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CommissionLedger)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CommissionLedgerQuery) loadReward(ctx context.Context, query *CommissionRewardQuery, nodes []*CommissionLedger, init func(*CommissionLedger), assign func(*CommissionLedger, *CommissionReward)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CommissionLedger)
	for i := range nodes {
		if nodes[i].RewardID == nil {
			continue
		}
		fk := *nodes[i].RewardID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(commissionreward.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "reward_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CommissionLedgerQuery) loadRechargeOrder(ctx context.Context, query *RechargeOrderQuery, nodes []*CommissionLedger, init func(*CommissionLedger), assign func(*CommissionLedger, *RechargeOrder)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CommissionLedger)
	for i := range nodes {
		if nodes[i].RechargeOrderID == nil {
			continue
		}
		fk := *nodes[i].RechargeOrderID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(rechargeorder.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "recharge_order_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CommissionLedgerQuery) loadWithdrawal(ctx context.Context, query *CommissionWithdrawalQuery, nodes []*CommissionLedger, init func(*CommissionLedger), assign func(*CommissionLedger, *CommissionWithdrawal)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CommissionLedger)
	for i := range nodes {
		if nodes[i].WithdrawalID == nil {
			continue
		}
		fk := *nodes[i].WithdrawalID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(commissionwithdrawal.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "withdrawal_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CommissionLedgerQuery) loadWithdrawalItem(ctx context.Context, query *CommissionWithdrawalItemQuery, nodes []*CommissionLedger, init func(*CommissionLedger), assign func(*CommissionLedger, *CommissionWithdrawalItem)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CommissionLedger)
	for i := range nodes {
		if nodes[i].WithdrawalItemID == nil {
			continue
		}
		fk := *nodes[i].WithdrawalItemID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(commissionwithdrawalitem.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "withdrawal_item_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *CommissionLedgerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CommissionLedgerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(commissionledger.Table, commissionledger.Columns, sqlgraph.NewFieldSpec(commissionledger.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, commissionledger.FieldID)
		for i := range fields {
			if fields[i] != commissionledger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(commissionledger.FieldUserID)
		}
		if _q.withReward != nil {
			_spec.Node.AddColumnOnce(commissionledger.FieldRewardID)
		}
		if _q.withRechargeOrder != nil {
			_spec.Node.AddColumnOnce(commissionledger.FieldRechargeOrderID)
		}
		if _q.withWithdrawal != nil {
			_spec.Node.AddColumnOnce(commissionledger.FieldWithdrawalID)
		}
		if _q.withWithdrawalItem != nil {
			_spec.Node.AddColumnOnce(commissionledger.FieldWithdrawalItemID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CommissionLedgerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(commissionledger.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = commissionledger.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *CommissionLedgerQuery) ForUpdate(opts ...sql.LockOption) *CommissionLedgerQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *CommissionLedgerQuery) ForShare(opts ...sql.LockOption) *CommissionLedgerQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// CommissionLedgerGroupBy is the group-by builder for CommissionLedger entities.
type CommissionLedgerGroupBy struct {
	selector
	build *CommissionLedgerQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CommissionLedgerGroupBy) Aggregate(fns ...AggregateFunc) *CommissionLedgerGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CommissionLedgerGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CommissionLedgerQuery, *CommissionLedgerGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CommissionLedgerGroupBy) sqlScan(ctx context.Context, root *CommissionLedgerQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CommissionLedgerSelect is the builder for selecting fields of CommissionLedger entities.
type CommissionLedgerSelect struct {
	*CommissionLedgerQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CommissionLedgerSelect) Aggregate(fns ...AggregateFunc) *CommissionLedgerSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CommissionLedgerSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CommissionLedgerQuery, *CommissionLedgerSelect](ctx, _s.CommissionLedgerQuery, _s, _s.inters, v)
}

func (_s *CommissionLedgerSelect) sqlScan(ctx context.Context, root *CommissionLedgerQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
