// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/commissionledger"
	"github.com/Wei-Shaw/sub2api/ent/commissionreward"
	"github.com/Wei-Shaw/sub2api/ent/commissionwithdrawal"
	"github.com/Wei-Shaw/sub2api/ent/commissionwithdrawalitem"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rechargeorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CommissionLedgerUpdate is the builder for updating CommissionLedger entities.
type CommissionLedgerUpdate struct {
	config
	hooks    []Hook
	mutation *CommissionLedgerMutation
}

// Where appends a list predicates to the CommissionLedgerUpdate builder.
func (_u *CommissionLedgerUpdate) Where(ps ...predicate.CommissionLedger) *CommissionLedgerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CommissionLedgerUpdate) SetUserID(v int64) *CommissionLedgerUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CommissionLedgerUpdate) SetNillableUserID(v *int64) *CommissionLedgerUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRewardID sets the "reward_id" field.
func (_u *CommissionLedgerUpdate) SetRewardID(v int64) *CommissionLedgerUpdate {
	_u.mutation.SetRewardID(v)
	return _u
}

// SetNillableRewardID sets the "reward_id" field if the given value is not nil.
func (_u *CommissionLedgerUpdate) SetNillableRewardID(v *int64) *CommissionLedgerUpdate {
	if v != nil {
		_u.SetRewardID(*v)
	}
	return _u
}

// ClearRewardID clears the value of the "reward_id" field.
func (_u *CommissionLedgerUpdate) ClearRewardID() *CommissionLedgerUpdate {
	_u.mutation.ClearRewardID()
	return _u
}

// SetRechargeOrderID sets the "recharge_order_id" field.
func (_u *CommissionLedgerUpdate) SetRechargeOrderID(v int64) *CommissionLedgerUpdate {
	_u.mutation.SetRechargeOrderID(v)
	return _u
}

// SetNillableRechargeOrderID sets the "recharge_order_id" field if the given value is not nil.
func (_u *CommissionLedgerUpdate) SetNillableRechargeOrderID(v *int64) *CommissionLedgerUpdate {
	if v != nil {
		_u.SetRechargeOrderID(*v)
	}
	return _u
}

// ClearRechargeOrderID clears the value of the "recharge_order_id" field.
func (_u *CommissionLedgerUpdate) ClearRechargeOrderID() *CommissionLedgerUpdate {
	_u.mutation.ClearRechargeOrderID()
	return _u
}

// SetWithdrawalID sets the "withdrawal_id" field.
func (_u *CommissionLedgerUpdate) SetWithdrawalID(v int64) *CommissionLedgerUpdate {
	_u.mutation.SetWithdrawalID(v)
	return _u
}

// SetNillableWithdrawalID sets the "withdrawal_id" field if the given value is not nil.
func (_u *CommissionLedgerUpdate) SetNillableWithdrawalID(v *int64) *CommissionLedgerUpdate {
	if v != nil {
		_u.SetWithdrawalID(*v)
	}
	return _u
}

// ClearWithdrawalID clears the value of the "withdrawal_id" field.
func (_u *CommissionLedgerUpdate) ClearWithdrawalID() *CommissionLedgerUpdate {
	_u.mutation.ClearWithdrawalID()
	return _u
}

// SetWithdrawalItemID sets the "withdrawal_item_id" field.
func (_u *CommissionLedgerUpdate) SetWithdrawalItemID(v int64) *CommissionLedgerUpdate {
	_u.mutation.SetWithdrawalItemID(v)
	return _u
}

// SetNillableWithdrawalItemID sets the "withdrawal_item_id" field if the given value is not nil.
func (_u *CommissionLedgerUpdate) SetNillableWithdrawalItemID(v *int64) *CommissionLedgerUpdate {
	if v != nil {
		_u.SetWithdrawalItemID(*v)
	}
	return _u
}

// ClearWithdrawalItemID clears the value of the "withdrawal_item_id" field.
func (_u *CommissionLedgerUpdate) ClearWithdrawalItemID() *CommissionLedgerUpdate {
	_u.mutation.ClearWithdrawalItemID()
	return _u
}

// SetEntryType sets the "entry_type" field.
func (_u *CommissionLedgerUpdate) SetEntryType(v string) *CommissionLedgerUpdate {
	_u.mutation.SetEntryType(v)
	return _u
}

// SetNillableEntryType sets the "entry_type" field if the given value is not nil.
func (_u *CommissionLedgerUpdate) SetNillableEntryType(v *string) *CommissionLedgerUpdate {
	if v != nil {
		_u.SetEntryType(*v)
	}
	return _u
}

// SetBucket sets the "bucket" field.
func (_u *CommissionLedgerUpdate) SetBucket(v string) *CommissionLedgerUpdate {
	_u.mutation.SetBucket(v)
	return _u
}

// SetNillableBucket sets the "bucket" field if the given value is not nil.
func (_u *CommissionLedgerUpdate) SetNillableBucket(v *string) *CommissionLedgerUpdate {
	if v != nil {
		_u.SetBucket(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *CommissionLedgerUpdate) SetAmount(v float64) *CommissionLedgerUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *CommissionLedgerUpdate) SetNillableAmount(v *float64) *CommissionLedgerUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *CommissionLedgerUpdate) AddAmount(v float64) *CommissionLedgerUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *CommissionLedgerUpdate) SetCurrency(v string) *CommissionLedgerUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *CommissionLedgerUpdate) SetNillableCurrency(v *string) *CommissionLedgerUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *CommissionLedgerUpdate) SetIdempotencyKey(v string) *CommissionLedgerUpdate {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *CommissionLedgerUpdate) SetNillableIdempotencyKey(v *string) *CommissionLedgerUpdate {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *CommissionLedgerUpdate) ClearIdempotencyKey() *CommissionLedgerUpdate {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_u *CommissionLedgerUpdate) SetOperatorUserID(v int64) *CommissionLedgerUpdate {
	_u.mutation.ResetOperatorUserID()
	_u.mutation.SetOperatorUserID(v)
	return _u
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_u *CommissionLedgerUpdate) SetNillableOperatorUserID(v *int64) *CommissionLedgerUpdate {
	if v != nil {
		_u.SetOperatorUserID(*v)
	}
	return _u
}

// AddOperatorUserID adds value to the "operator_user_id" field.
func (_u *CommissionLedgerUpdate) AddOperatorUserID(v int64) *CommissionLedgerUpdate {
	_u.mutation.AddOperatorUserID(v)
	return _u
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (_u *CommissionLedgerUpdate) ClearOperatorUserID() *CommissionLedgerUpdate {
	_u.mutation.ClearOperatorUserID()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *CommissionLedgerUpdate) SetRemark(v string) *CommissionLedgerUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *CommissionLedgerUpdate) SetNillableRemark(v *string) *CommissionLedgerUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *CommissionLedgerUpdate) ClearRemark() *CommissionLedgerUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetMetadataJSON sets the "metadata_json" field.
func (_u *CommissionLedgerUpdate) SetMetadataJSON(v string) *CommissionLedgerUpdate {
	_u.mutation.SetMetadataJSON(v)
	return _u
}

// SetNillableMetadataJSON sets the "metadata_json" field if the given value is not nil.
func (_u *CommissionLedgerUpdate) SetNillableMetadataJSON(v *string) *CommissionLedgerUpdate {
	if v != nil {
		_u.SetMetadataJSON(*v)
	}
	return _u
}

// ClearMetadataJSON clears the value of the "metadata_json" field.
func (_u *CommissionLedgerUpdate) ClearMetadataJSON() *CommissionLedgerUpdate {
	_u.mutation.ClearMetadataJSON()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CommissionLedgerUpdate) SetUser(v *User) *CommissionLedgerUpdate {
	return _u.SetUserID(v.ID)
}

// SetReward sets the "reward" edge to the CommissionReward entity.
func (_u *CommissionLedgerUpdate) SetReward(v *CommissionReward) *CommissionLedgerUpdate {
	return _u.SetRewardID(v.ID)
}

// SetRechargeOrder sets the "recharge_order" edge to the RechargeOrder entity.
func (_u *CommissionLedgerUpdate) SetRechargeOrder(v *RechargeOrder) *CommissionLedgerUpdate {
	return _u.SetRechargeOrderID(v.ID)
}

// SetWithdrawal sets the "withdrawal" edge to the CommissionWithdrawal entity.
func (_u *CommissionLedgerUpdate) SetWithdrawal(v *CommissionWithdrawal) *CommissionLedgerUpdate {
	return _u.SetWithdrawalID(v.ID)
}

// SetWithdrawalItem sets the "withdrawal_item" edge to the CommissionWithdrawalItem entity.
func (_u *CommissionLedgerUpdate) SetWithdrawalItem(v *CommissionWithdrawalItem) *CommissionLedgerUpdate {
	return _u.SetWithdrawalItemID(v.ID)
}

// Mutation returns the CommissionLedgerMutation object of the builder.
func (_u *CommissionLedgerUpdate) Mutation() *CommissionLedgerMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CommissionLedgerUpdate) ClearUser() *CommissionLedgerUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearReward clears the "reward" edge to the CommissionReward entity.
func (_u *CommissionLedgerUpdate) ClearReward() *CommissionLedgerUpdate {
	_u.mutation.ClearReward()
	return _u
}

// ClearRechargeOrder clears the "recharge_order" edge to the RechargeOrder entity.
func (_u *CommissionLedgerUpdate) ClearRechargeOrder() *CommissionLedgerUpdate {
	_u.mutation.ClearRechargeOrder()
	return _u
}

// ClearWithdrawal clears the "withdrawal" edge to the CommissionWithdrawal entity.
func (_u *CommissionLedgerUpdate) ClearWithdrawal() *CommissionLedgerUpdate {
	_u.mutation.ClearWithdrawal()
	return _u
}

// ClearWithdrawalItem clears the "withdrawal_item" edge to the CommissionWithdrawalItem entity.
func (_u *CommissionLedgerUpdate) ClearWithdrawalItem() *CommissionLedgerUpdate {
	_u.mutation.ClearWithdrawalItem()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CommissionLedgerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommissionLedgerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CommissionLedgerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommissionLedgerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CommissionLedgerUpdate) check() error {
	if v, ok := _u.mutation.EntryType(); ok {
		if err := commissionledger.EntryTypeValidator(v); err != nil {
			return &ValidationError{Name: "entry_type", err: fmt.Errorf(`ent: validator failed for field "CommissionLedger.entry_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bucket(); ok {
		if err := commissionledger.BucketValidator(v); err != nil {
			return &ValidationError{Name: "bucket", err: fmt.Errorf(`ent: validator failed for field "CommissionLedger.bucket": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := commissionledger.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "CommissionLedger.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := commissionledger.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "CommissionLedger.idempotency_key": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CommissionLedger.user"`)
	}
	return nil
}

func (_u *CommissionLedgerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(commissionledger.Table, commissionledger.Columns, sqlgraph.NewFieldSpec(commissionledger.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EntryType(); ok {
		_spec.SetField(commissionledger.FieldEntryType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bucket(); ok {
		_spec.SetField(commissionledger.FieldBucket, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(commissionledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(commissionledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(commissionledger.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(commissionledger.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(commissionledger.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.OperatorUserID(); ok {
		_spec.SetField(commissionledger.FieldOperatorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorUserID(); ok {
		_spec.AddField(commissionledger.FieldOperatorUserID, field.TypeInt64, value)
	}
	if _u.mutation.OperatorUserIDCleared() {
		_spec.ClearField(commissionledger.FieldOperatorUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(commissionledger.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(commissionledger.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.MetadataJSON(); ok {
		_spec.SetField(commissionledger.FieldMetadataJSON, field.TypeString, value)
	}
	if _u.mutation.MetadataJSONCleared() {
		_spec.ClearField(commissionledger.FieldMetadataJSON, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.UserTable,
			Columns: []string{commissionledger.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.UserTable,
			Columns: []string{commissionledger.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RewardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.RewardTable,
			Columns: []string{commissionledger.RewardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commissionreward.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RewardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.RewardTable,
			Columns: []string{commissionledger.RewardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commissionreward.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RechargeOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.RechargeOrderTable,
			Columns: []string{commissionledger.RechargeOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RechargeOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.RechargeOrderTable,
			Columns: []string{commissionledger.RechargeOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WithdrawalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.WithdrawalTable,
			Columns: []string{commissionledger.WithdrawalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commissionwithdrawal.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WithdrawalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.WithdrawalTable,
			Columns: []string{commissionledger.WithdrawalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commissionwithdrawal.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WithdrawalItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.WithdrawalItemTable,
			Columns: []string{commissionledger.WithdrawalItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commissionwithdrawalitem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WithdrawalItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.WithdrawalItemTable,
			Columns: []string{commissionledger.WithdrawalItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commissionwithdrawalitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{commissionledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CommissionLedgerUpdateOne is the builder for updating a single CommissionLedger entity.
type CommissionLedgerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CommissionLedgerMutation
}

// SetUserID sets the "user_id" field.
func (_u *CommissionLedgerUpdateOne) SetUserID(v int64) *CommissionLedgerUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CommissionLedgerUpdateOne) SetNillableUserID(v *int64) *CommissionLedgerUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRewardID sets the "reward_id" field.
func (_u *CommissionLedgerUpdateOne) SetRewardID(v int64) *CommissionLedgerUpdateOne {
	_u.mutation.SetRewardID(v)
	return _u
}

// SetNillableRewardID sets the "reward_id" field if the given value is not nil.
func (_u *CommissionLedgerUpdateOne) SetNillableRewardID(v *int64) *CommissionLedgerUpdateOne {
	if v != nil {
		_u.SetRewardID(*v)
	}
	return _u
}

// ClearRewardID clears the value of the "reward_id" field.
func (_u *CommissionLedgerUpdateOne) ClearRewardID() *CommissionLedgerUpdateOne {
	_u.mutation.ClearRewardID()
	return _u
}

// SetRechargeOrderID sets the "recharge_order_id" field.
func (_u *CommissionLedgerUpdateOne) SetRechargeOrderID(v int64) *CommissionLedgerUpdateOne {
	_u.mutation.SetRechargeOrderID(v)
	return _u
}

// SetNillableRechargeOrderID sets the "recharge_order_id" field if the given value is not nil.
func (_u *CommissionLedgerUpdateOne) SetNillableRechargeOrderID(v *int64) *CommissionLedgerUpdateOne {
	if v != nil {
		_u.SetRechargeOrderID(*v)
	}
	return _u
}

// ClearRechargeOrderID clears the value of the "recharge_order_id" field.
func (_u *CommissionLedgerUpdateOne) ClearRechargeOrderID() *CommissionLedgerUpdateOne {
	_u.mutation.ClearRechargeOrderID()
	return _u
}

// SetWithdrawalID sets the "withdrawal_id" field.
func (_u *CommissionLedgerUpdateOne) SetWithdrawalID(v int64) *CommissionLedgerUpdateOne {
	_u.mutation.SetWithdrawalID(v)
	return _u
}

// SetNillableWithdrawalID sets the "withdrawal_id" field if the given value is not nil.
func (_u *CommissionLedgerUpdateOne) SetNillableWithdrawalID(v *int64) *CommissionLedgerUpdateOne {
	if v != nil {
		_u.SetWithdrawalID(*v)
	}
	return _u
}

// ClearWithdrawalID clears the value of the "withdrawal_id" field.
func (_u *CommissionLedgerUpdateOne) ClearWithdrawalID() *CommissionLedgerUpdateOne {
	_u.mutation.ClearWithdrawalID()
	return _u
}

// SetWithdrawalItemID sets the "withdrawal_item_id" field.
func (_u *CommissionLedgerUpdateOne) SetWithdrawalItemID(v int64) *CommissionLedgerUpdateOne {
	_u.mutation.SetWithdrawalItemID(v)
	return _u
}

// SetNillableWithdrawalItemID sets the "withdrawal_item_id" field if the given value is not nil.
func (_u *CommissionLedgerUpdateOne) SetNillableWithdrawalItemID(v *int64) *CommissionLedgerUpdateOne {
	if v != nil {
		_u.SetWithdrawalItemID(*v)
	}
	return _u
}

// ClearWithdrawalItemID clears the value of the "withdrawal_item_id" field.
func (_u *CommissionLedgerUpdateOne) ClearWithdrawalItemID() *CommissionLedgerUpdateOne {
	_u.mutation.ClearWithdrawalItemID()
	return _u
}

// SetEntryType sets the "entry_type" field.
func (_u *CommissionLedgerUpdateOne) SetEntryType(v string) *CommissionLedgerUpdateOne {
	_u.mutation.SetEntryType(v)
	return _u
}

// SetNillableEntryType sets the "entry_type" field if the given value is not nil.
func (_u *CommissionLedgerUpdateOne) SetNillableEntryType(v *string) *CommissionLedgerUpdateOne {
	if v != nil {
		_u.SetEntryType(*v)
	}
	return _u
}

// SetBucket sets the "bucket" field.
func (_u *CommissionLedgerUpdateOne) SetBucket(v string) *CommissionLedgerUpdateOne {
	_u.mutation.SetBucket(v)
	return _u
}

// SetNillableBucket sets the "bucket" field if the given value is not nil.
func (_u *CommissionLedgerUpdateOne) SetNillableBucket(v *string) *CommissionLedgerUpdateOne {
	if v != nil {
		_u.SetBucket(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *CommissionLedgerUpdateOne) SetAmount(v float64) *CommissionLedgerUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *CommissionLedgerUpdateOne) SetNillableAmount(v *float64) *CommissionLedgerUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *CommissionLedgerUpdateOne) AddAmount(v float64) *CommissionLedgerUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *CommissionLedgerUpdateOne) SetCurrency(v string) *CommissionLedgerUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *CommissionLedgerUpdateOne) SetNillableCurrency(v *string) *CommissionLedgerUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *CommissionLedgerUpdateOne) SetIdempotencyKey(v string) *CommissionLedgerUpdateOne {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *CommissionLedgerUpdateOne) SetNillableIdempotencyKey(v *string) *CommissionLedgerUpdateOne {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *CommissionLedgerUpdateOne) ClearIdempotencyKey() *CommissionLedgerUpdateOne {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_u *CommissionLedgerUpdateOne) SetOperatorUserID(v int64) *CommissionLedgerUpdateOne {
	_u.mutation.ResetOperatorUserID()
	_u.mutation.SetOperatorUserID(v)
	return _u
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_u *CommissionLedgerUpdateOne) SetNillableOperatorUserID(v *int64) *CommissionLedgerUpdateOne {
	if v != nil {
		_u.SetOperatorUserID(*v)
	}
	return _u
}

// AddOperatorUserID adds value to the "operator_user_id" field.
func (_u *CommissionLedgerUpdateOne) AddOperatorUserID(v int64) *CommissionLedgerUpdateOne {
	_u.mutation.AddOperatorUserID(v)
	return _u
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (_u *CommissionLedgerUpdateOne) ClearOperatorUserID() *CommissionLedgerUpdateOne {
	_u.mutation.ClearOperatorUserID()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *CommissionLedgerUpdateOne) SetRemark(v string) *CommissionLedgerUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *CommissionLedgerUpdateOne) SetNillableRemark(v *string) *CommissionLedgerUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *CommissionLedgerUpdateOne) ClearRemark() *CommissionLedgerUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetMetadataJSON sets the "metadata_json" field.
func (_u *CommissionLedgerUpdateOne) SetMetadataJSON(v string) *CommissionLedgerUpdateOne {
	_u.mutation.SetMetadataJSON(v)
	return _u
}

// SetNillableMetadataJSON sets the "metadata_json" field if the given value is not nil.
func (_u *CommissionLedgerUpdateOne) SetNillableMetadataJSON(v *string) *CommissionLedgerUpdateOne {
	if v != nil {
		_u.SetMetadataJSON(*v)
	}
	return _u
}

// ClearMetadataJSON clears the value of the "metadata_json" field.
func (_u *CommissionLedgerUpdateOne) ClearMetadataJSON() *CommissionLedgerUpdateOne {
	_u.mutation.ClearMetadataJSON()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CommissionLedgerUpdateOne) SetUser(v *User) *CommissionLedgerUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetReward sets the "reward" edge to the CommissionReward entity.
func (_u *CommissionLedgerUpdateOne) SetReward(v *CommissionReward) *CommissionLedgerUpdateOne {
	return _u.SetRewardID(v.ID)
}

// SetRechargeOrder sets the "recharge_order" edge to the RechargeOrder entity.
func (_u *CommissionLedgerUpdateOne) SetRechargeOrder(v *RechargeOrder) *CommissionLedgerUpdateOne {
	return _u.SetRechargeOrderID(v.ID)
}

// SetWithdrawal sets the "withdrawal" edge to the CommissionWithdrawal entity.
func (_u *CommissionLedgerUpdateOne) SetWithdrawal(v *CommissionWithdrawal) *CommissionLedgerUpdateOne {
	return _u.SetWithdrawalID(v.ID)
}

// SetWithdrawalItem sets the "withdrawal_item" edge to the CommissionWithdrawalItem entity.
func (_u *CommissionLedgerUpdateOne) SetWithdrawalItem(v *CommissionWithdrawalItem) *CommissionLedgerUpdateOne {
	return _u.SetWithdrawalItemID(v.ID)
}

// Mutation returns the CommissionLedgerMutation object of the builder.
func (_u *CommissionLedgerUpdateOne) Mutation() *CommissionLedgerMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CommissionLedgerUpdateOne) ClearUser() *CommissionLedgerUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearReward clears the "reward" edge to the CommissionReward entity.
func (_u *CommissionLedgerUpdateOne) ClearReward() *CommissionLedgerUpdateOne {
	_u.mutation.ClearReward()
	return _u
}

// ClearRechargeOrder clears the "recharge_order" edge to the RechargeOrder entity.
func (_u *CommissionLedgerUpdateOne) ClearRechargeOrder() *CommissionLedgerUpdateOne {
	_u.mutation.ClearRechargeOrder()
	return _u
}

// ClearWithdrawal clears the "withdrawal" edge to the CommissionWithdrawal entity.
func (_u *CommissionLedgerUpdateOne) ClearWithdrawal() *CommissionLedgerUpdateOne {
	_u.mutation.ClearWithdrawal()
	return _u
}

// ClearWithdrawalItem clears the "withdrawal_item" edge to the CommissionWithdrawalItem entity.
func (_u *CommissionLedgerUpdateOne) ClearWithdrawalItem() *CommissionLedgerUpdateOne {
	_u.mutation.ClearWithdrawalItem()
	return _u
}

// Where appends a list predicates to the CommissionLedgerUpdate builder.
func (_u *CommissionLedgerUpdateOne) Where(ps ...predicate.CommissionLedger) *CommissionLedgerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CommissionLedgerUpdateOne) Select(field string, fields ...string) *CommissionLedgerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CommissionLedger entity.
func (_u *CommissionLedgerUpdateOne) Save(ctx context.Context) (*CommissionLedger, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommissionLedgerUpdateOne) SaveX(ctx context.Context) *CommissionLedger {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CommissionLedgerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommissionLedgerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CommissionLedgerUpdateOne) check() error {
	if v, ok := _u.mutation.EntryType(); ok {
		if err := commissionledger.EntryTypeValidator(v); err != nil {
			return &ValidationError{Name: "entry_type", err: fmt.Errorf(`ent: validator failed for field "CommissionLedger.entry_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bucket(); ok {
		if err := commissionledger.BucketValidator(v); err != nil {
			return &ValidationError{Name: "bucket", err: fmt.Errorf(`ent: validator failed for field "CommissionLedger.bucket": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := commissionledger.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "CommissionLedger.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := commissionledger.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "CommissionLedger.idempotency_key": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CommissionLedger.user"`)
	}
	return nil
}

func (_u *CommissionLedgerUpdateOne) sqlSave(ctx context.Context) (_node *CommissionLedger, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(commissionledger.Table, commissionledger.Columns, sqlgraph.NewFieldSpec(commissionledger.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CommissionLedger.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, commissionledger.FieldID)
		for _, f := range fields {
			if !commissionledger.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != commissionledger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EntryType(); ok {
		_spec.SetField(commissionledger.FieldEntryType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bucket(); ok {
		_spec.SetField(commissionledger.FieldBucket, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(commissionledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(commissionledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(commissionledger.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(commissionledger.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(commissionledger.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.OperatorUserID(); ok {
		_spec.SetField(commissionledger.FieldOperatorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorUserID(); ok {
		_spec.AddField(commissionledger.FieldOperatorUserID, field.TypeInt64, value)
	}
	if _u.mutation.OperatorUserIDCleared() {
		_spec.ClearField(commissionledger.FieldOperatorUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(commissionledger.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(commissionledger.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.MetadataJSON(); ok {
		_spec.SetField(commissionledger.FieldMetadataJSON, field.TypeString, value)
	}
	if _u.mutation.MetadataJSONCleared() {
		_spec.ClearField(commissionledger.FieldMetadataJSON, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.UserTable,
			Columns: []string{commissionledger.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.UserTable,
			Columns: []string{commissionledger.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RewardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.RewardTable,
			Columns: []string{commissionledger.RewardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commissionreward.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RewardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.RewardTable,
			Columns: []string{commissionledger.RewardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commissionreward.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RechargeOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.RechargeOrderTable,
			Columns: []string{commissionledger.RechargeOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RechargeOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.RechargeOrderTable,
			Columns: []string{commissionledger.RechargeOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WithdrawalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.WithdrawalTable,
			Columns: []string{commissionledger.WithdrawalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commissionwithdrawal.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WithdrawalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.WithdrawalTable,
			Columns: []string{commissionledger.WithdrawalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commissionwithdrawal.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WithdrawalItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.WithdrawalItemTable,
			Columns: []string{commissionledger.WithdrawalItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commissionwithdrawalitem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WithdrawalItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commissionledger.WithdrawalItemTable,
			Columns: []string{commissionledger.WithdrawalItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commissionwithdrawalitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CommissionLedger{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{commissionledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
