// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplan"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplanexternalmapping"
)

// SubscriptionPlanExternalMappingCreate is the builder for creating a SubscriptionPlanExternalMapping entity.
type SubscriptionPlanExternalMappingCreate struct {
	config
	mutation *SubscriptionPlanExternalMappingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSource sets the "source" field.
func (_c *SubscriptionPlanExternalMappingCreate) SetSource(v string) *SubscriptionPlanExternalMappingCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *SubscriptionPlanExternalMappingCreate) SetNillableSource(v *string) *SubscriptionPlanExternalMappingCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetLegacyGroupID sets the "legacy_group_id" field.
func (_c *SubscriptionPlanExternalMappingCreate) SetLegacyGroupID(v int64) *SubscriptionPlanExternalMappingCreate {
	_c.mutation.SetLegacyGroupID(v)
	return _c
}

// SetLegacyValidityDays sets the "legacy_validity_days" field.
func (_c *SubscriptionPlanExternalMappingCreate) SetLegacyValidityDays(v int) *SubscriptionPlanExternalMappingCreate {
	_c.mutation.SetLegacyValidityDays(v)
	return _c
}

// SetLegacyValue sets the "legacy_value" field.
func (_c *SubscriptionPlanExternalMappingCreate) SetLegacyValue(v float64) *SubscriptionPlanExternalMappingCreate {
	_c.mutation.SetLegacyValue(v)
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *SubscriptionPlanExternalMappingCreate) SetPlanID(v int64) *SubscriptionPlanExternalMappingCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *SubscriptionPlanExternalMappingCreate) SetEnabled(v bool) *SubscriptionPlanExternalMappingCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *SubscriptionPlanExternalMappingCreate) SetNillableEnabled(v *bool) *SubscriptionPlanExternalMappingCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *SubscriptionPlanExternalMappingCreate) SetPriority(v int) *SubscriptionPlanExternalMappingCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *SubscriptionPlanExternalMappingCreate) SetNillablePriority(v *int) *SubscriptionPlanExternalMappingCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *SubscriptionPlanExternalMappingCreate) SetNotes(v string) *SubscriptionPlanExternalMappingCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *SubscriptionPlanExternalMappingCreate) SetNillableNotes(v *string) *SubscriptionPlanExternalMappingCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionPlanExternalMappingCreate) SetCreatedAt(v time.Time) *SubscriptionPlanExternalMappingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionPlanExternalMappingCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionPlanExternalMappingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubscriptionPlanExternalMappingCreate) SetUpdatedAt(v time.Time) *SubscriptionPlanExternalMappingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubscriptionPlanExternalMappingCreate) SetNillableUpdatedAt(v *time.Time) *SubscriptionPlanExternalMappingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SubscriptionPlanExternalMappingCreate) SetDeletedAt(v time.Time) *SubscriptionPlanExternalMappingCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SubscriptionPlanExternalMappingCreate) SetNillableDeletedAt(v *time.Time) *SubscriptionPlanExternalMappingCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetLegacyGroup sets the "legacy_group" edge to the Group entity.
func (_c *SubscriptionPlanExternalMappingCreate) SetLegacyGroup(v *Group) *SubscriptionPlanExternalMappingCreate {
	return _c.SetLegacyGroupID(v.ID)
}

// SetPlan sets the "plan" edge to the SubscriptionPlan entity.
func (_c *SubscriptionPlanExternalMappingCreate) SetPlan(v *SubscriptionPlan) *SubscriptionPlanExternalMappingCreate {
	return _c.SetPlanID(v.ID)
}

// Mutation returns the SubscriptionPlanExternalMappingMutation object of the builder.
func (_c *SubscriptionPlanExternalMappingCreate) Mutation() *SubscriptionPlanExternalMappingMutation {
	return _c.mutation
}

// Save creates the SubscriptionPlanExternalMapping in the database.
func (_c *SubscriptionPlanExternalMappingCreate) Save(ctx context.Context) (*SubscriptionPlanExternalMapping, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionPlanExternalMappingCreate) SaveX(ctx context.Context) *SubscriptionPlanExternalMapping {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionPlanExternalMappingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionPlanExternalMappingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionPlanExternalMappingCreate) defaults() {
	if _, ok := _c.mutation.Source(); !ok {
		v := subscriptionplanexternalmapping.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := subscriptionplanexternalmapping.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := subscriptionplanexternalmapping.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subscriptionplanexternalmapping.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := subscriptionplanexternalmapping.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionPlanExternalMappingCreate) check() error {
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "SubscriptionPlanExternalMapping.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := subscriptionplanexternalmapping.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlanExternalMapping.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LegacyGroupID(); !ok {
		return &ValidationError{Name: "legacy_group_id", err: errors.New(`ent: missing required field "SubscriptionPlanExternalMapping.legacy_group_id"`)}
	}
	if _, ok := _c.mutation.LegacyValidityDays(); !ok {
		return &ValidationError{Name: "legacy_validity_days", err: errors.New(`ent: missing required field "SubscriptionPlanExternalMapping.legacy_validity_days"`)}
	}
	if _, ok := _c.mutation.LegacyValue(); !ok {
		return &ValidationError{Name: "legacy_value", err: errors.New(`ent: missing required field "SubscriptionPlanExternalMapping.legacy_value"`)}
	}
	if _, ok := _c.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "SubscriptionPlanExternalMapping.plan_id"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "SubscriptionPlanExternalMapping.enabled"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "SubscriptionPlanExternalMapping.priority"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubscriptionPlanExternalMapping.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SubscriptionPlanExternalMapping.updated_at"`)}
	}
	if len(_c.mutation.LegacyGroupIDs()) == 0 {
		return &ValidationError{Name: "legacy_group", err: errors.New(`ent: missing required edge "SubscriptionPlanExternalMapping.legacy_group"`)}
	}
	if len(_c.mutation.PlanIDs()) == 0 {
		return &ValidationError{Name: "plan", err: errors.New(`ent: missing required edge "SubscriptionPlanExternalMapping.plan"`)}
	}
	return nil
}

func (_c *SubscriptionPlanExternalMappingCreate) sqlSave(ctx context.Context) (*SubscriptionPlanExternalMapping, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionPlanExternalMappingCreate) createSpec() (*SubscriptionPlanExternalMapping, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionPlanExternalMapping{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionplanexternalmapping.Table, sqlgraph.NewFieldSpec(subscriptionplanexternalmapping.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(subscriptionplanexternalmapping.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.LegacyValidityDays(); ok {
		_spec.SetField(subscriptionplanexternalmapping.FieldLegacyValidityDays, field.TypeInt, value)
		_node.LegacyValidityDays = value
	}
	if value, ok := _c.mutation.LegacyValue(); ok {
		_spec.SetField(subscriptionplanexternalmapping.FieldLegacyValue, field.TypeFloat64, value)
		_node.LegacyValue = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(subscriptionplanexternalmapping.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(subscriptionplanexternalmapping.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(subscriptionplanexternalmapping.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionplanexternalmapping.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionplanexternalmapping.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(subscriptionplanexternalmapping.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if nodes := _c.mutation.LegacyGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionplanexternalmapping.LegacyGroupTable,
			Columns: []string{subscriptionplanexternalmapping.LegacyGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LegacyGroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionplanexternalmapping.PlanTable,
			Columns: []string{subscriptionplanexternalmapping.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlanID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionPlanExternalMapping.Create().
//		SetSource(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionPlanExternalMappingUpsert) {
//			SetSource(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionPlanExternalMappingCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionPlanExternalMappingUpsertOne {
	_c.conflict = opts
	return &SubscriptionPlanExternalMappingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionPlanExternalMapping.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionPlanExternalMappingCreate) OnConflictColumns(columns ...string) *SubscriptionPlanExternalMappingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionPlanExternalMappingUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionPlanExternalMappingUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionPlanExternalMapping node.
	SubscriptionPlanExternalMappingUpsertOne struct {
		create *SubscriptionPlanExternalMappingCreate
	}

	// SubscriptionPlanExternalMappingUpsert is the "OnConflict" setter.
	SubscriptionPlanExternalMappingUpsert struct {
		*sql.UpdateSet
	}
)

// SetSource sets the "source" field.
func (u *SubscriptionPlanExternalMappingUpsert) SetSource(v string) *SubscriptionPlanExternalMappingUpsert {
	u.Set(subscriptionplanexternalmapping.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsert) UpdateSource() *SubscriptionPlanExternalMappingUpsert {
	u.SetExcluded(subscriptionplanexternalmapping.FieldSource)
	return u
}

// SetLegacyGroupID sets the "legacy_group_id" field.
func (u *SubscriptionPlanExternalMappingUpsert) SetLegacyGroupID(v int64) *SubscriptionPlanExternalMappingUpsert {
	u.Set(subscriptionplanexternalmapping.FieldLegacyGroupID, v)
	return u
}

// UpdateLegacyGroupID sets the "legacy_group_id" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsert) UpdateLegacyGroupID() *SubscriptionPlanExternalMappingUpsert {
	u.SetExcluded(subscriptionplanexternalmapping.FieldLegacyGroupID)
	return u
}

// SetLegacyValidityDays sets the "legacy_validity_days" field.
func (u *SubscriptionPlanExternalMappingUpsert) SetLegacyValidityDays(v int) *SubscriptionPlanExternalMappingUpsert {
	u.Set(subscriptionplanexternalmapping.FieldLegacyValidityDays, v)
	return u
}

// UpdateLegacyValidityDays sets the "legacy_validity_days" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsert) UpdateLegacyValidityDays() *SubscriptionPlanExternalMappingUpsert {
	u.SetExcluded(subscriptionplanexternalmapping.FieldLegacyValidityDays)
	return u
}

// AddLegacyValidityDays adds v to the "legacy_validity_days" field.
func (u *SubscriptionPlanExternalMappingUpsert) AddLegacyValidityDays(v int) *SubscriptionPlanExternalMappingUpsert {
	u.Add(subscriptionplanexternalmapping.FieldLegacyValidityDays, v)
	return u
}

// SetLegacyValue sets the "legacy_value" field.
func (u *SubscriptionPlanExternalMappingUpsert) SetLegacyValue(v float64) *SubscriptionPlanExternalMappingUpsert {
	u.Set(subscriptionplanexternalmapping.FieldLegacyValue, v)
	return u
}

// UpdateLegacyValue sets the "legacy_value" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsert) UpdateLegacyValue() *SubscriptionPlanExternalMappingUpsert {
	u.SetExcluded(subscriptionplanexternalmapping.FieldLegacyValue)
	return u
}

// AddLegacyValue adds v to the "legacy_value" field.
func (u *SubscriptionPlanExternalMappingUpsert) AddLegacyValue(v float64) *SubscriptionPlanExternalMappingUpsert {
	u.Add(subscriptionplanexternalmapping.FieldLegacyValue, v)
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *SubscriptionPlanExternalMappingUpsert) SetPlanID(v int64) *SubscriptionPlanExternalMappingUpsert {
	u.Set(subscriptionplanexternalmapping.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsert) UpdatePlanID() *SubscriptionPlanExternalMappingUpsert {
	u.SetExcluded(subscriptionplanexternalmapping.FieldPlanID)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *SubscriptionPlanExternalMappingUpsert) SetEnabled(v bool) *SubscriptionPlanExternalMappingUpsert {
	u.Set(subscriptionplanexternalmapping.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsert) UpdateEnabled() *SubscriptionPlanExternalMappingUpsert {
	u.SetExcluded(subscriptionplanexternalmapping.FieldEnabled)
	return u
}

// SetPriority sets the "priority" field.
func (u *SubscriptionPlanExternalMappingUpsert) SetPriority(v int) *SubscriptionPlanExternalMappingUpsert {
	u.Set(subscriptionplanexternalmapping.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsert) UpdatePriority() *SubscriptionPlanExternalMappingUpsert {
	u.SetExcluded(subscriptionplanexternalmapping.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *SubscriptionPlanExternalMappingUpsert) AddPriority(v int) *SubscriptionPlanExternalMappingUpsert {
	u.Add(subscriptionplanexternalmapping.FieldPriority, v)
	return u
}

// SetNotes sets the "notes" field.
func (u *SubscriptionPlanExternalMappingUpsert) SetNotes(v string) *SubscriptionPlanExternalMappingUpsert {
	u.Set(subscriptionplanexternalmapping.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsert) UpdateNotes() *SubscriptionPlanExternalMappingUpsert {
	u.SetExcluded(subscriptionplanexternalmapping.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *SubscriptionPlanExternalMappingUpsert) ClearNotes() *SubscriptionPlanExternalMappingUpsert {
	u.SetNull(subscriptionplanexternalmapping.FieldNotes)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionPlanExternalMappingUpsert) SetUpdatedAt(v time.Time) *SubscriptionPlanExternalMappingUpsert {
	u.Set(subscriptionplanexternalmapping.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsert) UpdateUpdatedAt() *SubscriptionPlanExternalMappingUpsert {
	u.SetExcluded(subscriptionplanexternalmapping.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SubscriptionPlanExternalMappingUpsert) SetDeletedAt(v time.Time) *SubscriptionPlanExternalMappingUpsert {
	u.Set(subscriptionplanexternalmapping.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsert) UpdateDeletedAt() *SubscriptionPlanExternalMappingUpsert {
	u.SetExcluded(subscriptionplanexternalmapping.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SubscriptionPlanExternalMappingUpsert) ClearDeletedAt() *SubscriptionPlanExternalMappingUpsert {
	u.SetNull(subscriptionplanexternalmapping.FieldDeletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionPlanExternalMapping.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionPlanExternalMappingUpsertOne) UpdateNewValues() *SubscriptionPlanExternalMappingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscriptionplanexternalmapping.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionPlanExternalMapping.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionPlanExternalMappingUpsertOne) Ignore() *SubscriptionPlanExternalMappingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionPlanExternalMappingUpsertOne) DoNothing() *SubscriptionPlanExternalMappingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionPlanExternalMappingCreate.OnConflict
// documentation for more info.
func (u *SubscriptionPlanExternalMappingUpsertOne) Update(set func(*SubscriptionPlanExternalMappingUpsert)) *SubscriptionPlanExternalMappingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionPlanExternalMappingUpsert{UpdateSet: update})
	}))
	return u
}

// SetSource sets the "source" field.
func (u *SubscriptionPlanExternalMappingUpsertOne) SetSource(v string) *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsertOne) UpdateSource() *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.UpdateSource()
	})
}

// SetLegacyGroupID sets the "legacy_group_id" field.
func (u *SubscriptionPlanExternalMappingUpsertOne) SetLegacyGroupID(v int64) *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.SetLegacyGroupID(v)
	})
}

// UpdateLegacyGroupID sets the "legacy_group_id" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsertOne) UpdateLegacyGroupID() *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.UpdateLegacyGroupID()
	})
}

// SetLegacyValidityDays sets the "legacy_validity_days" field.
func (u *SubscriptionPlanExternalMappingUpsertOne) SetLegacyValidityDays(v int) *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.SetLegacyValidityDays(v)
	})
}

// AddLegacyValidityDays adds v to the "legacy_validity_days" field.
func (u *SubscriptionPlanExternalMappingUpsertOne) AddLegacyValidityDays(v int) *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.AddLegacyValidityDays(v)
	})
}

// UpdateLegacyValidityDays sets the "legacy_validity_days" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsertOne) UpdateLegacyValidityDays() *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.UpdateLegacyValidityDays()
	})
}

// SetLegacyValue sets the "legacy_value" field.
func (u *SubscriptionPlanExternalMappingUpsertOne) SetLegacyValue(v float64) *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.SetLegacyValue(v)
	})
}

// AddLegacyValue adds v to the "legacy_value" field.
func (u *SubscriptionPlanExternalMappingUpsertOne) AddLegacyValue(v float64) *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.AddLegacyValue(v)
	})
}

// UpdateLegacyValue sets the "legacy_value" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsertOne) UpdateLegacyValue() *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.UpdateLegacyValue()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *SubscriptionPlanExternalMappingUpsertOne) SetPlanID(v int64) *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsertOne) UpdatePlanID() *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.UpdatePlanID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *SubscriptionPlanExternalMappingUpsertOne) SetEnabled(v bool) *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsertOne) UpdateEnabled() *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.UpdateEnabled()
	})
}

// SetPriority sets the "priority" field.
func (u *SubscriptionPlanExternalMappingUpsertOne) SetPriority(v int) *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *SubscriptionPlanExternalMappingUpsertOne) AddPriority(v int) *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsertOne) UpdatePriority() *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.UpdatePriority()
	})
}

// SetNotes sets the "notes" field.
func (u *SubscriptionPlanExternalMappingUpsertOne) SetNotes(v string) *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsertOne) UpdateNotes() *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *SubscriptionPlanExternalMappingUpsertOne) ClearNotes() *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.ClearNotes()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionPlanExternalMappingUpsertOne) SetUpdatedAt(v time.Time) *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsertOne) UpdateUpdatedAt() *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SubscriptionPlanExternalMappingUpsertOne) SetDeletedAt(v time.Time) *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsertOne) UpdateDeletedAt() *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SubscriptionPlanExternalMappingUpsertOne) ClearDeletedAt() *SubscriptionPlanExternalMappingUpsertOne {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *SubscriptionPlanExternalMappingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionPlanExternalMappingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionPlanExternalMappingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionPlanExternalMappingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionPlanExternalMappingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionPlanExternalMappingCreateBulk is the builder for creating many SubscriptionPlanExternalMapping entities in bulk.
type SubscriptionPlanExternalMappingCreateBulk struct {
	config
	err      error
	builders []*SubscriptionPlanExternalMappingCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionPlanExternalMapping entities in the database.
func (_c *SubscriptionPlanExternalMappingCreateBulk) Save(ctx context.Context) ([]*SubscriptionPlanExternalMapping, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionPlanExternalMapping, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionPlanExternalMappingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionPlanExternalMappingCreateBulk) SaveX(ctx context.Context) []*SubscriptionPlanExternalMapping {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionPlanExternalMappingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionPlanExternalMappingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionPlanExternalMapping.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionPlanExternalMappingUpsert) {
//			SetSource(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionPlanExternalMappingCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionPlanExternalMappingUpsertBulk {
	_c.conflict = opts
	return &SubscriptionPlanExternalMappingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionPlanExternalMapping.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionPlanExternalMappingCreateBulk) OnConflictColumns(columns ...string) *SubscriptionPlanExternalMappingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionPlanExternalMappingUpsertBulk{
		create: _c,
	}
}

// SubscriptionPlanExternalMappingUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionPlanExternalMapping nodes.
type SubscriptionPlanExternalMappingUpsertBulk struct {
	create *SubscriptionPlanExternalMappingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionPlanExternalMapping.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionPlanExternalMappingUpsertBulk) UpdateNewValues() *SubscriptionPlanExternalMappingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscriptionplanexternalmapping.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionPlanExternalMapping.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionPlanExternalMappingUpsertBulk) Ignore() *SubscriptionPlanExternalMappingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionPlanExternalMappingUpsertBulk) DoNothing() *SubscriptionPlanExternalMappingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionPlanExternalMappingCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionPlanExternalMappingUpsertBulk) Update(set func(*SubscriptionPlanExternalMappingUpsert)) *SubscriptionPlanExternalMappingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionPlanExternalMappingUpsert{UpdateSet: update})
	}))
	return u
}

// SetSource sets the "source" field.
func (u *SubscriptionPlanExternalMappingUpsertBulk) SetSource(v string) *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsertBulk) UpdateSource() *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.UpdateSource()
	})
}

// SetLegacyGroupID sets the "legacy_group_id" field.
func (u *SubscriptionPlanExternalMappingUpsertBulk) SetLegacyGroupID(v int64) *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.SetLegacyGroupID(v)
	})
}

// UpdateLegacyGroupID sets the "legacy_group_id" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsertBulk) UpdateLegacyGroupID() *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.UpdateLegacyGroupID()
	})
}

// SetLegacyValidityDays sets the "legacy_validity_days" field.
func (u *SubscriptionPlanExternalMappingUpsertBulk) SetLegacyValidityDays(v int) *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.SetLegacyValidityDays(v)
	})
}

// AddLegacyValidityDays adds v to the "legacy_validity_days" field.
func (u *SubscriptionPlanExternalMappingUpsertBulk) AddLegacyValidityDays(v int) *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.AddLegacyValidityDays(v)
	})
}

// UpdateLegacyValidityDays sets the "legacy_validity_days" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsertBulk) UpdateLegacyValidityDays() *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.UpdateLegacyValidityDays()
	})
}

// SetLegacyValue sets the "legacy_value" field.
func (u *SubscriptionPlanExternalMappingUpsertBulk) SetLegacyValue(v float64) *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.SetLegacyValue(v)
	})
}

// AddLegacyValue adds v to the "legacy_value" field.
func (u *SubscriptionPlanExternalMappingUpsertBulk) AddLegacyValue(v float64) *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.AddLegacyValue(v)
	})
}

// UpdateLegacyValue sets the "legacy_value" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsertBulk) UpdateLegacyValue() *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.UpdateLegacyValue()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *SubscriptionPlanExternalMappingUpsertBulk) SetPlanID(v int64) *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsertBulk) UpdatePlanID() *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.UpdatePlanID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *SubscriptionPlanExternalMappingUpsertBulk) SetEnabled(v bool) *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsertBulk) UpdateEnabled() *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.UpdateEnabled()
	})
}

// SetPriority sets the "priority" field.
func (u *SubscriptionPlanExternalMappingUpsertBulk) SetPriority(v int) *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *SubscriptionPlanExternalMappingUpsertBulk) AddPriority(v int) *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsertBulk) UpdatePriority() *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.UpdatePriority()
	})
}

// SetNotes sets the "notes" field.
func (u *SubscriptionPlanExternalMappingUpsertBulk) SetNotes(v string) *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsertBulk) UpdateNotes() *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *SubscriptionPlanExternalMappingUpsertBulk) ClearNotes() *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.ClearNotes()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionPlanExternalMappingUpsertBulk) SetUpdatedAt(v time.Time) *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsertBulk) UpdateUpdatedAt() *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SubscriptionPlanExternalMappingUpsertBulk) SetDeletedAt(v time.Time) *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SubscriptionPlanExternalMappingUpsertBulk) UpdateDeletedAt() *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SubscriptionPlanExternalMappingUpsertBulk) ClearDeletedAt() *SubscriptionPlanExternalMappingUpsertBulk {
	return u.Update(func(s *SubscriptionPlanExternalMappingUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *SubscriptionPlanExternalMappingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionPlanExternalMappingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionPlanExternalMappingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionPlanExternalMappingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
