// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionentitlement"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionentitlementgroup"
)

// SubscriptionEntitlementGroup is the model entity for the SubscriptionEntitlementGroup schema.
type SubscriptionEntitlementGroup struct {
	config `json:"-"`
	// EntitlementID holds the value of the "entitlement_id" field.
	EntitlementID int64 `json:"entitlement_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubscriptionEntitlementGroupQuery when eager-loading is set.
	Edges        SubscriptionEntitlementGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubscriptionEntitlementGroupEdges holds the relations/edges for other nodes in the graph.
type SubscriptionEntitlementGroupEdges struct {
	// Entitlement holds the value of the entitlement edge.
	Entitlement *SubscriptionEntitlement `json:"entitlement,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// EntitlementOrErr returns the Entitlement value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionEntitlementGroupEdges) EntitlementOrErr() (*SubscriptionEntitlement, error) {
	if e.Entitlement != nil {
		return e.Entitlement, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: subscriptionentitlement.Label}
	}
	return nil, &NotLoadedError{edge: "entitlement"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionEntitlementGroupEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionEntitlementGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionentitlementgroup.FieldEnabled:
			values[i] = new(sql.NullBool)
		case subscriptionentitlementgroup.FieldEntitlementID, subscriptionentitlementgroup.FieldGroupID, subscriptionentitlementgroup.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case subscriptionentitlementgroup.FieldCreatedAt, subscriptionentitlementgroup.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionEntitlementGroup fields.
func (_m *SubscriptionEntitlementGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionentitlementgroup.FieldEntitlementID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field entitlement_id", values[i])
			} else if value.Valid {
				_m.EntitlementID = value.Int64
			}
		case subscriptionentitlementgroup.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case subscriptionentitlementgroup.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case subscriptionentitlementgroup.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case subscriptionentitlementgroup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case subscriptionentitlementgroup.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionEntitlementGroup.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionEntitlementGroup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEntitlement queries the "entitlement" edge of the SubscriptionEntitlementGroup entity.
func (_m *SubscriptionEntitlementGroup) QueryEntitlement() *SubscriptionEntitlementQuery {
	return NewSubscriptionEntitlementGroupClient(_m.config).QueryEntitlement(_m)
}

// QueryGroup queries the "group" edge of the SubscriptionEntitlementGroup entity.
func (_m *SubscriptionEntitlementGroup) QueryGroup() *GroupQuery {
	return NewSubscriptionEntitlementGroupClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this SubscriptionEntitlementGroup.
// Note that you need to call SubscriptionEntitlementGroup.Unwrap() before calling this method if this SubscriptionEntitlementGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionEntitlementGroup) Update() *SubscriptionEntitlementGroupUpdateOne {
	return NewSubscriptionEntitlementGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionEntitlementGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionEntitlementGroup) Unwrap() *SubscriptionEntitlementGroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionEntitlementGroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionEntitlementGroup) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionEntitlementGroup(")
	builder.WriteString("entitlement_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EntitlementID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionEntitlementGroups is a parsable slice of SubscriptionEntitlementGroup.
type SubscriptionEntitlementGroups []*SubscriptionEntitlementGroup
