// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionentitlementevent"
)

// SubscriptionEntitlementEventUpdate is the builder for updating SubscriptionEntitlementEvent entities.
type SubscriptionEntitlementEventUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionEntitlementEventMutation
}

// Where appends a list predicates to the SubscriptionEntitlementEventUpdate builder.
func (_u *SubscriptionEntitlementEventUpdate) Where(ps ...predicate.SubscriptionEntitlementEvent) *SubscriptionEntitlementEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEntitlementID sets the "entitlement_id" field.
func (_u *SubscriptionEntitlementEventUpdate) SetEntitlementID(v int64) *SubscriptionEntitlementEventUpdate {
	_u.mutation.ResetEntitlementID()
	_u.mutation.SetEntitlementID(v)
	return _u
}

// SetNillableEntitlementID sets the "entitlement_id" field if the given value is not nil.
func (_u *SubscriptionEntitlementEventUpdate) SetNillableEntitlementID(v *int64) *SubscriptionEntitlementEventUpdate {
	if v != nil {
		_u.SetEntitlementID(*v)
	}
	return _u
}

// AddEntitlementID adds value to the "entitlement_id" field.
func (_u *SubscriptionEntitlementEventUpdate) AddEntitlementID(v int64) *SubscriptionEntitlementEventUpdate {
	_u.mutation.AddEntitlementID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionEntitlementEventUpdate) SetUserID(v int64) *SubscriptionEntitlementEventUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionEntitlementEventUpdate) SetNillableUserID(v *int64) *SubscriptionEntitlementEventUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SubscriptionEntitlementEventUpdate) AddUserID(v int64) *SubscriptionEntitlementEventUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *SubscriptionEntitlementEventUpdate) SetKind(v string) *SubscriptionEntitlementEventUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *SubscriptionEntitlementEventUpdate) SetNillableKind(v *string) *SubscriptionEntitlementEventUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *SubscriptionEntitlementEventUpdate) SetSourceType(v string) *SubscriptionEntitlementEventUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *SubscriptionEntitlementEventUpdate) SetNillableSourceType(v *string) *SubscriptionEntitlementEventUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetPreviousExpiresAt sets the "previous_expires_at" field.
func (_u *SubscriptionEntitlementEventUpdate) SetPreviousExpiresAt(v time.Time) *SubscriptionEntitlementEventUpdate {
	_u.mutation.SetPreviousExpiresAt(v)
	return _u
}

// SetNillablePreviousExpiresAt sets the "previous_expires_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementEventUpdate) SetNillablePreviousExpiresAt(v *time.Time) *SubscriptionEntitlementEventUpdate {
	if v != nil {
		_u.SetPreviousExpiresAt(*v)
	}
	return _u
}

// ClearPreviousExpiresAt clears the value of the "previous_expires_at" field.
func (_u *SubscriptionEntitlementEventUpdate) ClearPreviousExpiresAt() *SubscriptionEntitlementEventUpdate {
	_u.mutation.ClearPreviousExpiresAt()
	return _u
}

// SetNewExpiresAt sets the "new_expires_at" field.
func (_u *SubscriptionEntitlementEventUpdate) SetNewExpiresAt(v time.Time) *SubscriptionEntitlementEventUpdate {
	_u.mutation.SetNewExpiresAt(v)
	return _u
}

// SetNillableNewExpiresAt sets the "new_expires_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementEventUpdate) SetNillableNewExpiresAt(v *time.Time) *SubscriptionEntitlementEventUpdate {
	if v != nil {
		_u.SetNewExpiresAt(*v)
	}
	return _u
}

// SetValiditySeconds sets the "validity_seconds" field.
func (_u *SubscriptionEntitlementEventUpdate) SetValiditySeconds(v int64) *SubscriptionEntitlementEventUpdate {
	_u.mutation.ResetValiditySeconds()
	_u.mutation.SetValiditySeconds(v)
	return _u
}

// SetNillableValiditySeconds sets the "validity_seconds" field if the given value is not nil.
func (_u *SubscriptionEntitlementEventUpdate) SetNillableValiditySeconds(v *int64) *SubscriptionEntitlementEventUpdate {
	if v != nil {
		_u.SetValiditySeconds(*v)
	}
	return _u
}

// AddValiditySeconds adds value to the "validity_seconds" field.
func (_u *SubscriptionEntitlementEventUpdate) AddValiditySeconds(v int64) *SubscriptionEntitlementEventUpdate {
	_u.mutation.AddValiditySeconds(v)
	return _u
}

// Mutation returns the SubscriptionEntitlementEventMutation object of the builder.
func (_u *SubscriptionEntitlementEventUpdate) Mutation() *SubscriptionEntitlementEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionEntitlementEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionEntitlementEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionEntitlementEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionEntitlementEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionEntitlementEventUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := subscriptionentitlementevent.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEntitlementEvent.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := subscriptionentitlementevent.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEntitlementEvent.source_type": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionEntitlementEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionentitlementevent.Table, subscriptionentitlementevent.Columns, sqlgraph.NewFieldSpec(subscriptionentitlementevent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EntitlementID(); ok {
		_spec.SetField(subscriptionentitlementevent.FieldEntitlementID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEntitlementID(); ok {
		_spec.AddField(subscriptionentitlementevent.FieldEntitlementID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(subscriptionentitlementevent.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(subscriptionentitlementevent.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(subscriptionentitlementevent.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(subscriptionentitlementevent.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PreviousExpiresAt(); ok {
		_spec.SetField(subscriptionentitlementevent.FieldPreviousExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.PreviousExpiresAtCleared() {
		_spec.ClearField(subscriptionentitlementevent.FieldPreviousExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NewExpiresAt(); ok {
		_spec.SetField(subscriptionentitlementevent.FieldNewExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ValiditySeconds(); ok {
		_spec.SetField(subscriptionentitlementevent.FieldValiditySeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedValiditySeconds(); ok {
		_spec.AddField(subscriptionentitlementevent.FieldValiditySeconds, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionentitlementevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionEntitlementEventUpdateOne is the builder for updating a single SubscriptionEntitlementEvent entity.
type SubscriptionEntitlementEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionEntitlementEventMutation
}

// SetEntitlementID sets the "entitlement_id" field.
func (_u *SubscriptionEntitlementEventUpdateOne) SetEntitlementID(v int64) *SubscriptionEntitlementEventUpdateOne {
	_u.mutation.ResetEntitlementID()
	_u.mutation.SetEntitlementID(v)
	return _u
}

// SetNillableEntitlementID sets the "entitlement_id" field if the given value is not nil.
func (_u *SubscriptionEntitlementEventUpdateOne) SetNillableEntitlementID(v *int64) *SubscriptionEntitlementEventUpdateOne {
	if v != nil {
		_u.SetEntitlementID(*v)
	}
	return _u
}

// AddEntitlementID adds value to the "entitlement_id" field.
func (_u *SubscriptionEntitlementEventUpdateOne) AddEntitlementID(v int64) *SubscriptionEntitlementEventUpdateOne {
	_u.mutation.AddEntitlementID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionEntitlementEventUpdateOne) SetUserID(v int64) *SubscriptionEntitlementEventUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionEntitlementEventUpdateOne) SetNillableUserID(v *int64) *SubscriptionEntitlementEventUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SubscriptionEntitlementEventUpdateOne) AddUserID(v int64) *SubscriptionEntitlementEventUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *SubscriptionEntitlementEventUpdateOne) SetKind(v string) *SubscriptionEntitlementEventUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *SubscriptionEntitlementEventUpdateOne) SetNillableKind(v *string) *SubscriptionEntitlementEventUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *SubscriptionEntitlementEventUpdateOne) SetSourceType(v string) *SubscriptionEntitlementEventUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *SubscriptionEntitlementEventUpdateOne) SetNillableSourceType(v *string) *SubscriptionEntitlementEventUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetPreviousExpiresAt sets the "previous_expires_at" field.
func (_u *SubscriptionEntitlementEventUpdateOne) SetPreviousExpiresAt(v time.Time) *SubscriptionEntitlementEventUpdateOne {
	_u.mutation.SetPreviousExpiresAt(v)
	return _u
}

// SetNillablePreviousExpiresAt sets the "previous_expires_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementEventUpdateOne) SetNillablePreviousExpiresAt(v *time.Time) *SubscriptionEntitlementEventUpdateOne {
	if v != nil {
		_u.SetPreviousExpiresAt(*v)
	}
	return _u
}

// ClearPreviousExpiresAt clears the value of the "previous_expires_at" field.
func (_u *SubscriptionEntitlementEventUpdateOne) ClearPreviousExpiresAt() *SubscriptionEntitlementEventUpdateOne {
	_u.mutation.ClearPreviousExpiresAt()
	return _u
}

// SetNewExpiresAt sets the "new_expires_at" field.
func (_u *SubscriptionEntitlementEventUpdateOne) SetNewExpiresAt(v time.Time) *SubscriptionEntitlementEventUpdateOne {
	_u.mutation.SetNewExpiresAt(v)
	return _u
}

// SetNillableNewExpiresAt sets the "new_expires_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementEventUpdateOne) SetNillableNewExpiresAt(v *time.Time) *SubscriptionEntitlementEventUpdateOne {
	if v != nil {
		_u.SetNewExpiresAt(*v)
	}
	return _u
}

// SetValiditySeconds sets the "validity_seconds" field.
func (_u *SubscriptionEntitlementEventUpdateOne) SetValiditySeconds(v int64) *SubscriptionEntitlementEventUpdateOne {
	_u.mutation.ResetValiditySeconds()
	_u.mutation.SetValiditySeconds(v)
	return _u
}

// SetNillableValiditySeconds sets the "validity_seconds" field if the given value is not nil.
func (_u *SubscriptionEntitlementEventUpdateOne) SetNillableValiditySeconds(v *int64) *SubscriptionEntitlementEventUpdateOne {
	if v != nil {
		_u.SetValiditySeconds(*v)
	}
	return _u
}

// AddValiditySeconds adds value to the "validity_seconds" field.
func (_u *SubscriptionEntitlementEventUpdateOne) AddValiditySeconds(v int64) *SubscriptionEntitlementEventUpdateOne {
	_u.mutation.AddValiditySeconds(v)
	return _u
}

// Mutation returns the SubscriptionEntitlementEventMutation object of the builder.
func (_u *SubscriptionEntitlementEventUpdateOne) Mutation() *SubscriptionEntitlementEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the SubscriptionEntitlementEventUpdate builder.
func (_u *SubscriptionEntitlementEventUpdateOne) Where(ps ...predicate.SubscriptionEntitlementEvent) *SubscriptionEntitlementEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionEntitlementEventUpdateOne) Select(field string, fields ...string) *SubscriptionEntitlementEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionEntitlementEvent entity.
func (_u *SubscriptionEntitlementEventUpdateOne) Save(ctx context.Context) (*SubscriptionEntitlementEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionEntitlementEventUpdateOne) SaveX(ctx context.Context) *SubscriptionEntitlementEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionEntitlementEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionEntitlementEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionEntitlementEventUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := subscriptionentitlementevent.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEntitlementEvent.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := subscriptionentitlementevent.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEntitlementEvent.source_type": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionEntitlementEventUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionEntitlementEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionentitlementevent.Table, subscriptionentitlementevent.Columns, sqlgraph.NewFieldSpec(subscriptionentitlementevent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionEntitlementEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionentitlementevent.FieldID)
		for _, f := range fields {
			if !subscriptionentitlementevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionentitlementevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EntitlementID(); ok {
		_spec.SetField(subscriptionentitlementevent.FieldEntitlementID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEntitlementID(); ok {
		_spec.AddField(subscriptionentitlementevent.FieldEntitlementID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(subscriptionentitlementevent.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(subscriptionentitlementevent.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(subscriptionentitlementevent.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(subscriptionentitlementevent.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PreviousExpiresAt(); ok {
		_spec.SetField(subscriptionentitlementevent.FieldPreviousExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.PreviousExpiresAtCleared() {
		_spec.ClearField(subscriptionentitlementevent.FieldPreviousExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NewExpiresAt(); ok {
		_spec.SetField(subscriptionentitlementevent.FieldNewExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ValiditySeconds(); ok {
		_spec.SetField(subscriptionentitlementevent.FieldValiditySeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedValiditySeconds(); ok {
		_spec.AddField(subscriptionentitlementevent.FieldValiditySeconds, field.TypeInt64, value)
	}
	_node = &SubscriptionEntitlementEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionentitlementevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
