// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/supportissue"
	"github.com/Wei-Shaw/sub2api/ent/supportissueevent"
)

// SupportIssueEvent is the model entity for the SupportIssueEvent schema.
type SupportIssueEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// IssueID holds the value of the "issue_id" field.
	IssueID int64 `json:"issue_id,omitempty"`
	// ActorUserID holds the value of the "actor_user_id" field.
	ActorUserID *int64 `json:"actor_user_id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// FromStatus holds the value of the "from_status" field.
	FromStatus *string `json:"from_status,omitempty"`
	// ToStatus holds the value of the "to_status" field.
	ToStatus *string `json:"to_status,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SupportIssueEventQuery when eager-loading is set.
	Edges        SupportIssueEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SupportIssueEventEdges holds the relations/edges for other nodes in the graph.
type SupportIssueEventEdges struct {
	// Issue holds the value of the issue edge.
	Issue *SupportIssue `json:"issue,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// IssueOrErr returns the Issue value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SupportIssueEventEdges) IssueOrErr() (*SupportIssue, error) {
	if e.Issue != nil {
		return e.Issue, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: supportissue.Label}
	}
	return nil, &NotLoadedError{edge: "issue"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SupportIssueEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case supportissueevent.FieldMetadata:
			values[i] = new([]byte)
		case supportissueevent.FieldID, supportissueevent.FieldIssueID, supportissueevent.FieldActorUserID:
			values[i] = new(sql.NullInt64)
		case supportissueevent.FieldEventType, supportissueevent.FieldFromStatus, supportissueevent.FieldToStatus:
			values[i] = new(sql.NullString)
		case supportissueevent.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SupportIssueEvent fields.
func (_m *SupportIssueEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case supportissueevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case supportissueevent.FieldIssueID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field issue_id", values[i])
			} else if value.Valid {
				_m.IssueID = value.Int64
			}
		case supportissueevent.FieldActorUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field actor_user_id", values[i])
			} else if value.Valid {
				_m.ActorUserID = new(int64)
				*_m.ActorUserID = value.Int64
			}
		case supportissueevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case supportissueevent.FieldFromStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_status", values[i])
			} else if value.Valid {
				_m.FromStatus = new(string)
				*_m.FromStatus = value.String
			}
		case supportissueevent.FieldToStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field to_status", values[i])
			} else if value.Valid {
				_m.ToStatus = new(string)
				*_m.ToStatus = value.String
			}
		case supportissueevent.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case supportissueevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SupportIssueEvent.
// This includes values selected through modifiers, order, etc.
func (_m *SupportIssueEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryIssue queries the "issue" edge of the SupportIssueEvent entity.
func (_m *SupportIssueEvent) QueryIssue() *SupportIssueQuery {
	return NewSupportIssueEventClient(_m.config).QueryIssue(_m)
}

// Update returns a builder for updating this SupportIssueEvent.
// Note that you need to call SupportIssueEvent.Unwrap() before calling this method if this SupportIssueEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SupportIssueEvent) Update() *SupportIssueEventUpdateOne {
	return NewSupportIssueEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SupportIssueEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SupportIssueEvent) Unwrap() *SupportIssueEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SupportIssueEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SupportIssueEvent) String() string {
	var builder strings.Builder
	builder.WriteString("SupportIssueEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("issue_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.IssueID))
	builder.WriteString(", ")
	if v := _m.ActorUserID; v != nil {
		builder.WriteString("actor_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	if v := _m.FromStatus; v != nil {
		builder.WriteString("from_status=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ToStatus; v != nil {
		builder.WriteString("to_status=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SupportIssueEvents is a parsable slice of SupportIssueEvent.
type SupportIssueEvents []*SupportIssueEvent
