// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supportissue"
	"github.com/Wei-Shaw/sub2api/ent/supportissuecomment"
)

// SupportIssueCommentUpdate is the builder for updating SupportIssueComment entities.
type SupportIssueCommentUpdate struct {
	config
	hooks    []Hook
	mutation *SupportIssueCommentMutation
}

// Where appends a list predicates to the SupportIssueCommentUpdate builder.
func (_u *SupportIssueCommentUpdate) Where(ps ...predicate.SupportIssueComment) *SupportIssueCommentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetIssueID sets the "issue_id" field.
func (_u *SupportIssueCommentUpdate) SetIssueID(v int64) *SupportIssueCommentUpdate {
	_u.mutation.SetIssueID(v)
	return _u
}

// SetNillableIssueID sets the "issue_id" field if the given value is not nil.
func (_u *SupportIssueCommentUpdate) SetNillableIssueID(v *int64) *SupportIssueCommentUpdate {
	if v != nil {
		_u.SetIssueID(*v)
	}
	return _u
}

// SetAuthorUserID sets the "author_user_id" field.
func (_u *SupportIssueCommentUpdate) SetAuthorUserID(v int64) *SupportIssueCommentUpdate {
	_u.mutation.ResetAuthorUserID()
	_u.mutation.SetAuthorUserID(v)
	return _u
}

// SetNillableAuthorUserID sets the "author_user_id" field if the given value is not nil.
func (_u *SupportIssueCommentUpdate) SetNillableAuthorUserID(v *int64) *SupportIssueCommentUpdate {
	if v != nil {
		_u.SetAuthorUserID(*v)
	}
	return _u
}

// AddAuthorUserID adds value to the "author_user_id" field.
func (_u *SupportIssueCommentUpdate) AddAuthorUserID(v int64) *SupportIssueCommentUpdate {
	_u.mutation.AddAuthorUserID(v)
	return _u
}

// ClearAuthorUserID clears the value of the "author_user_id" field.
func (_u *SupportIssueCommentUpdate) ClearAuthorUserID() *SupportIssueCommentUpdate {
	_u.mutation.ClearAuthorUserID()
	return _u
}

// SetAuthorRole sets the "author_role" field.
func (_u *SupportIssueCommentUpdate) SetAuthorRole(v string) *SupportIssueCommentUpdate {
	_u.mutation.SetAuthorRole(v)
	return _u
}

// SetNillableAuthorRole sets the "author_role" field if the given value is not nil.
func (_u *SupportIssueCommentUpdate) SetNillableAuthorRole(v *string) *SupportIssueCommentUpdate {
	if v != nil {
		_u.SetAuthorRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *SupportIssueCommentUpdate) SetContent(v string) *SupportIssueCommentUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SupportIssueCommentUpdate) SetNillableContent(v *string) *SupportIssueCommentUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetRelatedIssueID sets the "related_issue_id" field.
func (_u *SupportIssueCommentUpdate) SetRelatedIssueID(v int64) *SupportIssueCommentUpdate {
	_u.mutation.ResetRelatedIssueID()
	_u.mutation.SetRelatedIssueID(v)
	return _u
}

// SetNillableRelatedIssueID sets the "related_issue_id" field if the given value is not nil.
func (_u *SupportIssueCommentUpdate) SetNillableRelatedIssueID(v *int64) *SupportIssueCommentUpdate {
	if v != nil {
		_u.SetRelatedIssueID(*v)
	}
	return _u
}

// AddRelatedIssueID adds value to the "related_issue_id" field.
func (_u *SupportIssueCommentUpdate) AddRelatedIssueID(v int64) *SupportIssueCommentUpdate {
	_u.mutation.AddRelatedIssueID(v)
	return _u
}

// ClearRelatedIssueID clears the value of the "related_issue_id" field.
func (_u *SupportIssueCommentUpdate) ClearRelatedIssueID() *SupportIssueCommentUpdate {
	_u.mutation.ClearRelatedIssueID()
	return _u
}

// SetHiddenAt sets the "hidden_at" field.
func (_u *SupportIssueCommentUpdate) SetHiddenAt(v time.Time) *SupportIssueCommentUpdate {
	_u.mutation.SetHiddenAt(v)
	return _u
}

// SetNillableHiddenAt sets the "hidden_at" field if the given value is not nil.
func (_u *SupportIssueCommentUpdate) SetNillableHiddenAt(v *time.Time) *SupportIssueCommentUpdate {
	if v != nil {
		_u.SetHiddenAt(*v)
	}
	return _u
}

// ClearHiddenAt clears the value of the "hidden_at" field.
func (_u *SupportIssueCommentUpdate) ClearHiddenAt() *SupportIssueCommentUpdate {
	_u.mutation.ClearHiddenAt()
	return _u
}

// SetHiddenByUserID sets the "hidden_by_user_id" field.
func (_u *SupportIssueCommentUpdate) SetHiddenByUserID(v int64) *SupportIssueCommentUpdate {
	_u.mutation.ResetHiddenByUserID()
	_u.mutation.SetHiddenByUserID(v)
	return _u
}

// SetNillableHiddenByUserID sets the "hidden_by_user_id" field if the given value is not nil.
func (_u *SupportIssueCommentUpdate) SetNillableHiddenByUserID(v *int64) *SupportIssueCommentUpdate {
	if v != nil {
		_u.SetHiddenByUserID(*v)
	}
	return _u
}

// AddHiddenByUserID adds value to the "hidden_by_user_id" field.
func (_u *SupportIssueCommentUpdate) AddHiddenByUserID(v int64) *SupportIssueCommentUpdate {
	_u.mutation.AddHiddenByUserID(v)
	return _u
}

// ClearHiddenByUserID clears the value of the "hidden_by_user_id" field.
func (_u *SupportIssueCommentUpdate) ClearHiddenByUserID() *SupportIssueCommentUpdate {
	_u.mutation.ClearHiddenByUserID()
	return _u
}

// SetHideReason sets the "hide_reason" field.
func (_u *SupportIssueCommentUpdate) SetHideReason(v string) *SupportIssueCommentUpdate {
	_u.mutation.SetHideReason(v)
	return _u
}

// SetNillableHideReason sets the "hide_reason" field if the given value is not nil.
func (_u *SupportIssueCommentUpdate) SetNillableHideReason(v *string) *SupportIssueCommentUpdate {
	if v != nil {
		_u.SetHideReason(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportIssueCommentUpdate) SetUpdatedAt(v time.Time) *SupportIssueCommentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetIssue sets the "issue" edge to the SupportIssue entity.
func (_u *SupportIssueCommentUpdate) SetIssue(v *SupportIssue) *SupportIssueCommentUpdate {
	return _u.SetIssueID(v.ID)
}

// Mutation returns the SupportIssueCommentMutation object of the builder.
func (_u *SupportIssueCommentUpdate) Mutation() *SupportIssueCommentMutation {
	return _u.mutation
}

// ClearIssue clears the "issue" edge to the SupportIssue entity.
func (_u *SupportIssueCommentUpdate) ClearIssue() *SupportIssueCommentUpdate {
	_u.mutation.ClearIssue()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupportIssueCommentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportIssueCommentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupportIssueCommentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportIssueCommentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportIssueCommentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportissuecomment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportIssueCommentUpdate) check() error {
	if v, ok := _u.mutation.AuthorRole(); ok {
		if err := supportissuecomment.AuthorRoleValidator(v); err != nil {
			return &ValidationError{Name: "author_role", err: fmt.Errorf(`ent: validator failed for field "SupportIssueComment.author_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := supportissuecomment.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "SupportIssueComment.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HideReason(); ok {
		if err := supportissuecomment.HideReasonValidator(v); err != nil {
			return &ValidationError{Name: "hide_reason", err: fmt.Errorf(`ent: validator failed for field "SupportIssueComment.hide_reason": %w`, err)}
		}
	}
	if _u.mutation.IssueCleared() && len(_u.mutation.IssueIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportIssueComment.issue"`)
	}
	return nil
}

func (_u *SupportIssueCommentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportissuecomment.Table, supportissuecomment.Columns, sqlgraph.NewFieldSpec(supportissuecomment.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AuthorUserID(); ok {
		_spec.SetField(supportissuecomment.FieldAuthorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAuthorUserID(); ok {
		_spec.AddField(supportissuecomment.FieldAuthorUserID, field.TypeInt64, value)
	}
	if _u.mutation.AuthorUserIDCleared() {
		_spec.ClearField(supportissuecomment.FieldAuthorUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AuthorRole(); ok {
		_spec.SetField(supportissuecomment.FieldAuthorRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(supportissuecomment.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.RelatedIssueID(); ok {
		_spec.SetField(supportissuecomment.FieldRelatedIssueID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRelatedIssueID(); ok {
		_spec.AddField(supportissuecomment.FieldRelatedIssueID, field.TypeInt64, value)
	}
	if _u.mutation.RelatedIssueIDCleared() {
		_spec.ClearField(supportissuecomment.FieldRelatedIssueID, field.TypeInt64)
	}
	if value, ok := _u.mutation.HiddenAt(); ok {
		_spec.SetField(supportissuecomment.FieldHiddenAt, field.TypeTime, value)
	}
	if _u.mutation.HiddenAtCleared() {
		_spec.ClearField(supportissuecomment.FieldHiddenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HiddenByUserID(); ok {
		_spec.SetField(supportissuecomment.FieldHiddenByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedHiddenByUserID(); ok {
		_spec.AddField(supportissuecomment.FieldHiddenByUserID, field.TypeInt64, value)
	}
	if _u.mutation.HiddenByUserIDCleared() {
		_spec.ClearField(supportissuecomment.FieldHiddenByUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.HideReason(); ok {
		_spec.SetField(supportissuecomment.FieldHideReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportissuecomment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.IssueCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportissuecomment.IssueTable,
			Columns: []string{supportissuecomment.IssueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissue.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IssueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportissuecomment.IssueTable,
			Columns: []string{supportissuecomment.IssueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissue.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportissuecomment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupportIssueCommentUpdateOne is the builder for updating a single SupportIssueComment entity.
type SupportIssueCommentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupportIssueCommentMutation
}

// SetIssueID sets the "issue_id" field.
func (_u *SupportIssueCommentUpdateOne) SetIssueID(v int64) *SupportIssueCommentUpdateOne {
	_u.mutation.SetIssueID(v)
	return _u
}

// SetNillableIssueID sets the "issue_id" field if the given value is not nil.
func (_u *SupportIssueCommentUpdateOne) SetNillableIssueID(v *int64) *SupportIssueCommentUpdateOne {
	if v != nil {
		_u.SetIssueID(*v)
	}
	return _u
}

// SetAuthorUserID sets the "author_user_id" field.
func (_u *SupportIssueCommentUpdateOne) SetAuthorUserID(v int64) *SupportIssueCommentUpdateOne {
	_u.mutation.ResetAuthorUserID()
	_u.mutation.SetAuthorUserID(v)
	return _u
}

// SetNillableAuthorUserID sets the "author_user_id" field if the given value is not nil.
func (_u *SupportIssueCommentUpdateOne) SetNillableAuthorUserID(v *int64) *SupportIssueCommentUpdateOne {
	if v != nil {
		_u.SetAuthorUserID(*v)
	}
	return _u
}

// AddAuthorUserID adds value to the "author_user_id" field.
func (_u *SupportIssueCommentUpdateOne) AddAuthorUserID(v int64) *SupportIssueCommentUpdateOne {
	_u.mutation.AddAuthorUserID(v)
	return _u
}

// ClearAuthorUserID clears the value of the "author_user_id" field.
func (_u *SupportIssueCommentUpdateOne) ClearAuthorUserID() *SupportIssueCommentUpdateOne {
	_u.mutation.ClearAuthorUserID()
	return _u
}

// SetAuthorRole sets the "author_role" field.
func (_u *SupportIssueCommentUpdateOne) SetAuthorRole(v string) *SupportIssueCommentUpdateOne {
	_u.mutation.SetAuthorRole(v)
	return _u
}

// SetNillableAuthorRole sets the "author_role" field if the given value is not nil.
func (_u *SupportIssueCommentUpdateOne) SetNillableAuthorRole(v *string) *SupportIssueCommentUpdateOne {
	if v != nil {
		_u.SetAuthorRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *SupportIssueCommentUpdateOne) SetContent(v string) *SupportIssueCommentUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SupportIssueCommentUpdateOne) SetNillableContent(v *string) *SupportIssueCommentUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetRelatedIssueID sets the "related_issue_id" field.
func (_u *SupportIssueCommentUpdateOne) SetRelatedIssueID(v int64) *SupportIssueCommentUpdateOne {
	_u.mutation.ResetRelatedIssueID()
	_u.mutation.SetRelatedIssueID(v)
	return _u
}

// SetNillableRelatedIssueID sets the "related_issue_id" field if the given value is not nil.
func (_u *SupportIssueCommentUpdateOne) SetNillableRelatedIssueID(v *int64) *SupportIssueCommentUpdateOne {
	if v != nil {
		_u.SetRelatedIssueID(*v)
	}
	return _u
}

// AddRelatedIssueID adds value to the "related_issue_id" field.
func (_u *SupportIssueCommentUpdateOne) AddRelatedIssueID(v int64) *SupportIssueCommentUpdateOne {
	_u.mutation.AddRelatedIssueID(v)
	return _u
}

// ClearRelatedIssueID clears the value of the "related_issue_id" field.
func (_u *SupportIssueCommentUpdateOne) ClearRelatedIssueID() *SupportIssueCommentUpdateOne {
	_u.mutation.ClearRelatedIssueID()
	return _u
}

// SetHiddenAt sets the "hidden_at" field.
func (_u *SupportIssueCommentUpdateOne) SetHiddenAt(v time.Time) *SupportIssueCommentUpdateOne {
	_u.mutation.SetHiddenAt(v)
	return _u
}

// SetNillableHiddenAt sets the "hidden_at" field if the given value is not nil.
func (_u *SupportIssueCommentUpdateOne) SetNillableHiddenAt(v *time.Time) *SupportIssueCommentUpdateOne {
	if v != nil {
		_u.SetHiddenAt(*v)
	}
	return _u
}

// ClearHiddenAt clears the value of the "hidden_at" field.
func (_u *SupportIssueCommentUpdateOne) ClearHiddenAt() *SupportIssueCommentUpdateOne {
	_u.mutation.ClearHiddenAt()
	return _u
}

// SetHiddenByUserID sets the "hidden_by_user_id" field.
func (_u *SupportIssueCommentUpdateOne) SetHiddenByUserID(v int64) *SupportIssueCommentUpdateOne {
	_u.mutation.ResetHiddenByUserID()
	_u.mutation.SetHiddenByUserID(v)
	return _u
}

// SetNillableHiddenByUserID sets the "hidden_by_user_id" field if the given value is not nil.
func (_u *SupportIssueCommentUpdateOne) SetNillableHiddenByUserID(v *int64) *SupportIssueCommentUpdateOne {
	if v != nil {
		_u.SetHiddenByUserID(*v)
	}
	return _u
}

// AddHiddenByUserID adds value to the "hidden_by_user_id" field.
func (_u *SupportIssueCommentUpdateOne) AddHiddenByUserID(v int64) *SupportIssueCommentUpdateOne {
	_u.mutation.AddHiddenByUserID(v)
	return _u
}

// ClearHiddenByUserID clears the value of the "hidden_by_user_id" field.
func (_u *SupportIssueCommentUpdateOne) ClearHiddenByUserID() *SupportIssueCommentUpdateOne {
	_u.mutation.ClearHiddenByUserID()
	return _u
}

// SetHideReason sets the "hide_reason" field.
func (_u *SupportIssueCommentUpdateOne) SetHideReason(v string) *SupportIssueCommentUpdateOne {
	_u.mutation.SetHideReason(v)
	return _u
}

// SetNillableHideReason sets the "hide_reason" field if the given value is not nil.
func (_u *SupportIssueCommentUpdateOne) SetNillableHideReason(v *string) *SupportIssueCommentUpdateOne {
	if v != nil {
		_u.SetHideReason(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportIssueCommentUpdateOne) SetUpdatedAt(v time.Time) *SupportIssueCommentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetIssue sets the "issue" edge to the SupportIssue entity.
func (_u *SupportIssueCommentUpdateOne) SetIssue(v *SupportIssue) *SupportIssueCommentUpdateOne {
	return _u.SetIssueID(v.ID)
}

// Mutation returns the SupportIssueCommentMutation object of the builder.
func (_u *SupportIssueCommentUpdateOne) Mutation() *SupportIssueCommentMutation {
	return _u.mutation
}

// ClearIssue clears the "issue" edge to the SupportIssue entity.
func (_u *SupportIssueCommentUpdateOne) ClearIssue() *SupportIssueCommentUpdateOne {
	_u.mutation.ClearIssue()
	return _u
}

// Where appends a list predicates to the SupportIssueCommentUpdate builder.
func (_u *SupportIssueCommentUpdateOne) Where(ps ...predicate.SupportIssueComment) *SupportIssueCommentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupportIssueCommentUpdateOne) Select(field string, fields ...string) *SupportIssueCommentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupportIssueComment entity.
func (_u *SupportIssueCommentUpdateOne) Save(ctx context.Context) (*SupportIssueComment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportIssueCommentUpdateOne) SaveX(ctx context.Context) *SupportIssueComment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupportIssueCommentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportIssueCommentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportIssueCommentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportissuecomment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportIssueCommentUpdateOne) check() error {
	if v, ok := _u.mutation.AuthorRole(); ok {
		if err := supportissuecomment.AuthorRoleValidator(v); err != nil {
			return &ValidationError{Name: "author_role", err: fmt.Errorf(`ent: validator failed for field "SupportIssueComment.author_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := supportissuecomment.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "SupportIssueComment.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HideReason(); ok {
		if err := supportissuecomment.HideReasonValidator(v); err != nil {
			return &ValidationError{Name: "hide_reason", err: fmt.Errorf(`ent: validator failed for field "SupportIssueComment.hide_reason": %w`, err)}
		}
	}
	if _u.mutation.IssueCleared() && len(_u.mutation.IssueIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportIssueComment.issue"`)
	}
	return nil
}

func (_u *SupportIssueCommentUpdateOne) sqlSave(ctx context.Context) (_node *SupportIssueComment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportissuecomment.Table, supportissuecomment.Columns, sqlgraph.NewFieldSpec(supportissuecomment.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupportIssueComment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportissuecomment.FieldID)
		for _, f := range fields {
			if !supportissuecomment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supportissuecomment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AuthorUserID(); ok {
		_spec.SetField(supportissuecomment.FieldAuthorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAuthorUserID(); ok {
		_spec.AddField(supportissuecomment.FieldAuthorUserID, field.TypeInt64, value)
	}
	if _u.mutation.AuthorUserIDCleared() {
		_spec.ClearField(supportissuecomment.FieldAuthorUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AuthorRole(); ok {
		_spec.SetField(supportissuecomment.FieldAuthorRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(supportissuecomment.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.RelatedIssueID(); ok {
		_spec.SetField(supportissuecomment.FieldRelatedIssueID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRelatedIssueID(); ok {
		_spec.AddField(supportissuecomment.FieldRelatedIssueID, field.TypeInt64, value)
	}
	if _u.mutation.RelatedIssueIDCleared() {
		_spec.ClearField(supportissuecomment.FieldRelatedIssueID, field.TypeInt64)
	}
	if value, ok := _u.mutation.HiddenAt(); ok {
		_spec.SetField(supportissuecomment.FieldHiddenAt, field.TypeTime, value)
	}
	if _u.mutation.HiddenAtCleared() {
		_spec.ClearField(supportissuecomment.FieldHiddenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HiddenByUserID(); ok {
		_spec.SetField(supportissuecomment.FieldHiddenByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedHiddenByUserID(); ok {
		_spec.AddField(supportissuecomment.FieldHiddenByUserID, field.TypeInt64, value)
	}
	if _u.mutation.HiddenByUserIDCleared() {
		_spec.ClearField(supportissuecomment.FieldHiddenByUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.HideReason(); ok {
		_spec.SetField(supportissuecomment.FieldHideReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportissuecomment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.IssueCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportissuecomment.IssueTable,
			Columns: []string{supportissuecomment.IssueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissue.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IssueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportissuecomment.IssueTable,
			Columns: []string{supportissuecomment.IssueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissue.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SupportIssueComment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportissuecomment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
