// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supportissueview"
)

// SupportIssueViewDelete is the builder for deleting a SupportIssueView entity.
type SupportIssueViewDelete struct {
	config
	hooks    []Hook
	mutation *SupportIssueViewMutation
}

// Where appends a list predicates to the SupportIssueViewDelete builder.
func (_d *SupportIssueViewDelete) Where(ps ...predicate.SupportIssueView) *SupportIssueViewDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SupportIssueViewDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SupportIssueViewDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SupportIssueViewDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(supportissueview.Table, sqlgraph.NewFieldSpec(supportissueview.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SupportIssueViewDeleteOne is the builder for deleting a single SupportIssueView entity.
type SupportIssueViewDeleteOne struct {
	_d *SupportIssueViewDelete
}

// Where appends a list predicates to the SupportIssueViewDelete builder.
func (_d *SupportIssueViewDeleteOne) Where(ps ...predicate.SupportIssueView) *SupportIssueViewDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SupportIssueViewDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{supportissueview.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SupportIssueViewDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
