// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supportissue"
	"github.com/Wei-Shaw/sub2api/ent/supportissueattachment"
	"github.com/Wei-Shaw/sub2api/ent/supportissuecomment"
	"github.com/Wei-Shaw/sub2api/ent/supportissueevent"
	"github.com/Wei-Shaw/sub2api/ent/supportissueview"
)

// SupportIssueUpdate is the builder for updating SupportIssue entities.
type SupportIssueUpdate struct {
	config
	hooks    []Hook
	mutation *SupportIssueMutation
}

// Where appends a list predicates to the SupportIssueUpdate builder.
func (_u *SupportIssueUpdate) Where(ps ...predicate.SupportIssue) *SupportIssueUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPublicID sets the "public_id" field.
func (_u *SupportIssueUpdate) SetPublicID(v string) *SupportIssueUpdate {
	_u.mutation.SetPublicID(v)
	return _u
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillablePublicID(v *string) *SupportIssueUpdate {
	if v != nil {
		_u.SetPublicID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *SupportIssueUpdate) SetTitle(v string) *SupportIssueUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableTitle(v *string) *SupportIssueUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SupportIssueUpdate) SetDescription(v string) *SupportIssueUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableDescription(v *string) *SupportIssueUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetAccountEmail sets the "account_email" field.
func (_u *SupportIssueUpdate) SetAccountEmail(v string) *SupportIssueUpdate {
	_u.mutation.SetAccountEmail(v)
	return _u
}

// SetNillableAccountEmail sets the "account_email" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableAccountEmail(v *string) *SupportIssueUpdate {
	if v != nil {
		_u.SetAccountEmail(*v)
	}
	return _u
}

// SetAccountEmailNormalized sets the "account_email_normalized" field.
func (_u *SupportIssueUpdate) SetAccountEmailNormalized(v string) *SupportIssueUpdate {
	_u.mutation.SetAccountEmailNormalized(v)
	return _u
}

// SetNillableAccountEmailNormalized sets the "account_email_normalized" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableAccountEmailNormalized(v *string) *SupportIssueUpdate {
	if v != nil {
		_u.SetAccountEmailNormalized(*v)
	}
	return _u
}

// SetAccountEmailMasked sets the "account_email_masked" field.
func (_u *SupportIssueUpdate) SetAccountEmailMasked(v string) *SupportIssueUpdate {
	_u.mutation.SetAccountEmailMasked(v)
	return _u
}

// SetNillableAccountEmailMasked sets the "account_email_masked" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableAccountEmailMasked(v *string) *SupportIssueUpdate {
	if v != nil {
		_u.SetAccountEmailMasked(*v)
	}
	return _u
}

// SetOccurredAt sets the "occurred_at" field.
func (_u *SupportIssueUpdate) SetOccurredAt(v time.Time) *SupportIssueUpdate {
	_u.mutation.SetOccurredAt(v)
	return _u
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableOccurredAt(v *time.Time) *SupportIssueUpdate {
	if v != nil {
		_u.SetOccurredAt(*v)
	}
	return _u
}

// SetScreenshotText sets the "screenshot_text" field.
func (_u *SupportIssueUpdate) SetScreenshotText(v string) *SupportIssueUpdate {
	_u.mutation.SetScreenshotText(v)
	return _u
}

// SetNillableScreenshotText sets the "screenshot_text" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableScreenshotText(v *string) *SupportIssueUpdate {
	if v != nil {
		_u.SetScreenshotText(*v)
	}
	return _u
}

// SetScreenshotLanguage sets the "screenshot_language" field.
func (_u *SupportIssueUpdate) SetScreenshotLanguage(v string) *SupportIssueUpdate {
	_u.mutation.SetScreenshotLanguage(v)
	return _u
}

// SetNillableScreenshotLanguage sets the "screenshot_language" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableScreenshotLanguage(v *string) *SupportIssueUpdate {
	if v != nil {
		_u.SetScreenshotLanguage(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *SupportIssueUpdate) SetCategory(v string) *SupportIssueUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableCategory(v *string) *SupportIssueUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *SupportIssueUpdate) SetSeverity(v string) *SupportIssueUpdate {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableSeverity(v *string) *SupportIssueUpdate {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupportIssueUpdate) SetStatus(v string) *SupportIssueUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableStatus(v *string) *SupportIssueUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *SupportIssueUpdate) SetModelName(v string) *SupportIssueUpdate {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableModelName(v *string) *SupportIssueUpdate {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// SetClientName sets the "client_name" field.
func (_u *SupportIssueUpdate) SetClientName(v string) *SupportIssueUpdate {
	_u.mutation.SetClientName(v)
	return _u
}

// SetNillableClientName sets the "client_name" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableClientName(v *string) *SupportIssueUpdate {
	if v != nil {
		_u.SetClientName(*v)
	}
	return _u
}

// SetHTTPStatus sets the "http_status" field.
func (_u *SupportIssueUpdate) SetHTTPStatus(v int) *SupportIssueUpdate {
	_u.mutation.ResetHTTPStatus()
	_u.mutation.SetHTTPStatus(v)
	return _u
}

// SetNillableHTTPStatus sets the "http_status" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableHTTPStatus(v *int) *SupportIssueUpdate {
	if v != nil {
		_u.SetHTTPStatus(*v)
	}
	return _u
}

// AddHTTPStatus adds value to the "http_status" field.
func (_u *SupportIssueUpdate) AddHTTPStatus(v int) *SupportIssueUpdate {
	_u.mutation.AddHTTPStatus(v)
	return _u
}

// ClearHTTPStatus clears the value of the "http_status" field.
func (_u *SupportIssueUpdate) ClearHTTPStatus() *SupportIssueUpdate {
	_u.mutation.ClearHTTPStatus()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *SupportIssueUpdate) SetErrorCode(v string) *SupportIssueUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableErrorCode(v *string) *SupportIssueUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// SetAPIKeySuffix sets the "api_key_suffix" field.
func (_u *SupportIssueUpdate) SetAPIKeySuffix(v string) *SupportIssueUpdate {
	_u.mutation.SetAPIKeySuffix(v)
	return _u
}

// SetNillableAPIKeySuffix sets the "api_key_suffix" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableAPIKeySuffix(v *string) *SupportIssueUpdate {
	if v != nil {
		_u.SetAPIKeySuffix(*v)
	}
	return _u
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_u *SupportIssueUpdate) SetCreatedByUserID(v int64) *SupportIssueUpdate {
	_u.mutation.ResetCreatedByUserID()
	_u.mutation.SetCreatedByUserID(v)
	return _u
}

// SetNillableCreatedByUserID sets the "created_by_user_id" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableCreatedByUserID(v *int64) *SupportIssueUpdate {
	if v != nil {
		_u.SetCreatedByUserID(*v)
	}
	return _u
}

// AddCreatedByUserID adds value to the "created_by_user_id" field.
func (_u *SupportIssueUpdate) AddCreatedByUserID(v int64) *SupportIssueUpdate {
	_u.mutation.AddCreatedByUserID(v)
	return _u
}

// ClearCreatedByUserID clears the value of the "created_by_user_id" field.
func (_u *SupportIssueUpdate) ClearCreatedByUserID() *SupportIssueUpdate {
	_u.mutation.ClearCreatedByUserID()
	return _u
}

// SetResolvedByUserID sets the "resolved_by_user_id" field.
func (_u *SupportIssueUpdate) SetResolvedByUserID(v int64) *SupportIssueUpdate {
	_u.mutation.ResetResolvedByUserID()
	_u.mutation.SetResolvedByUserID(v)
	return _u
}

// SetNillableResolvedByUserID sets the "resolved_by_user_id" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableResolvedByUserID(v *int64) *SupportIssueUpdate {
	if v != nil {
		_u.SetResolvedByUserID(*v)
	}
	return _u
}

// AddResolvedByUserID adds value to the "resolved_by_user_id" field.
func (_u *SupportIssueUpdate) AddResolvedByUserID(v int64) *SupportIssueUpdate {
	_u.mutation.AddResolvedByUserID(v)
	return _u
}

// ClearResolvedByUserID clears the value of the "resolved_by_user_id" field.
func (_u *SupportIssueUpdate) ClearResolvedByUserID() *SupportIssueUpdate {
	_u.mutation.ClearResolvedByUserID()
	return _u
}

// SetResolvedAt sets the "resolved_at" field.
func (_u *SupportIssueUpdate) SetResolvedAt(v time.Time) *SupportIssueUpdate {
	_u.mutation.SetResolvedAt(v)
	return _u
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableResolvedAt(v *time.Time) *SupportIssueUpdate {
	if v != nil {
		_u.SetResolvedAt(*v)
	}
	return _u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (_u *SupportIssueUpdate) ClearResolvedAt() *SupportIssueUpdate {
	_u.mutation.ClearResolvedAt()
	return _u
}

// SetLockedAt sets the "locked_at" field.
func (_u *SupportIssueUpdate) SetLockedAt(v time.Time) *SupportIssueUpdate {
	_u.mutation.SetLockedAt(v)
	return _u
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableLockedAt(v *time.Time) *SupportIssueUpdate {
	if v != nil {
		_u.SetLockedAt(*v)
	}
	return _u
}

// ClearLockedAt clears the value of the "locked_at" field.
func (_u *SupportIssueUpdate) ClearLockedAt() *SupportIssueUpdate {
	_u.mutation.ClearLockedAt()
	return _u
}

// SetHiddenAt sets the "hidden_at" field.
func (_u *SupportIssueUpdate) SetHiddenAt(v time.Time) *SupportIssueUpdate {
	_u.mutation.SetHiddenAt(v)
	return _u
}

// SetNillableHiddenAt sets the "hidden_at" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableHiddenAt(v *time.Time) *SupportIssueUpdate {
	if v != nil {
		_u.SetHiddenAt(*v)
	}
	return _u
}

// ClearHiddenAt clears the value of the "hidden_at" field.
func (_u *SupportIssueUpdate) ClearHiddenAt() *SupportIssueUpdate {
	_u.mutation.ClearHiddenAt()
	return _u
}

// SetHiddenByUserID sets the "hidden_by_user_id" field.
func (_u *SupportIssueUpdate) SetHiddenByUserID(v int64) *SupportIssueUpdate {
	_u.mutation.ResetHiddenByUserID()
	_u.mutation.SetHiddenByUserID(v)
	return _u
}

// SetNillableHiddenByUserID sets the "hidden_by_user_id" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableHiddenByUserID(v *int64) *SupportIssueUpdate {
	if v != nil {
		_u.SetHiddenByUserID(*v)
	}
	return _u
}

// AddHiddenByUserID adds value to the "hidden_by_user_id" field.
func (_u *SupportIssueUpdate) AddHiddenByUserID(v int64) *SupportIssueUpdate {
	_u.mutation.AddHiddenByUserID(v)
	return _u
}

// ClearHiddenByUserID clears the value of the "hidden_by_user_id" field.
func (_u *SupportIssueUpdate) ClearHiddenByUserID() *SupportIssueUpdate {
	_u.mutation.ClearHiddenByUserID()
	return _u
}

// SetHideReason sets the "hide_reason" field.
func (_u *SupportIssueUpdate) SetHideReason(v string) *SupportIssueUpdate {
	_u.mutation.SetHideReason(v)
	return _u
}

// SetNillableHideReason sets the "hide_reason" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableHideReason(v *string) *SupportIssueUpdate {
	if v != nil {
		_u.SetHideReason(*v)
	}
	return _u
}

// SetLastCommentAt sets the "last_comment_at" field.
func (_u *SupportIssueUpdate) SetLastCommentAt(v time.Time) *SupportIssueUpdate {
	_u.mutation.SetLastCommentAt(v)
	return _u
}

// SetNillableLastCommentAt sets the "last_comment_at" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableLastCommentAt(v *time.Time) *SupportIssueUpdate {
	if v != nil {
		_u.SetLastCommentAt(*v)
	}
	return _u
}

// ClearLastCommentAt clears the value of the "last_comment_at" field.
func (_u *SupportIssueUpdate) ClearLastCommentAt() *SupportIssueUpdate {
	_u.mutation.ClearLastCommentAt()
	return _u
}

// SetLastViewedAt sets the "last_viewed_at" field.
func (_u *SupportIssueUpdate) SetLastViewedAt(v time.Time) *SupportIssueUpdate {
	_u.mutation.SetLastViewedAt(v)
	return _u
}

// SetNillableLastViewedAt sets the "last_viewed_at" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableLastViewedAt(v *time.Time) *SupportIssueUpdate {
	if v != nil {
		_u.SetLastViewedAt(*v)
	}
	return _u
}

// ClearLastViewedAt clears the value of the "last_viewed_at" field.
func (_u *SupportIssueUpdate) ClearLastViewedAt() *SupportIssueUpdate {
	_u.mutation.ClearLastViewedAt()
	return _u
}

// SetCommentCount sets the "comment_count" field.
func (_u *SupportIssueUpdate) SetCommentCount(v int) *SupportIssueUpdate {
	_u.mutation.ResetCommentCount()
	_u.mutation.SetCommentCount(v)
	return _u
}

// SetNillableCommentCount sets the "comment_count" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableCommentCount(v *int) *SupportIssueUpdate {
	if v != nil {
		_u.SetCommentCount(*v)
	}
	return _u
}

// AddCommentCount adds value to the "comment_count" field.
func (_u *SupportIssueUpdate) AddCommentCount(v int) *SupportIssueUpdate {
	_u.mutation.AddCommentCount(v)
	return _u
}

// SetHiddenCommentCount sets the "hidden_comment_count" field.
func (_u *SupportIssueUpdate) SetHiddenCommentCount(v int) *SupportIssueUpdate {
	_u.mutation.ResetHiddenCommentCount()
	_u.mutation.SetHiddenCommentCount(v)
	return _u
}

// SetNillableHiddenCommentCount sets the "hidden_comment_count" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableHiddenCommentCount(v *int) *SupportIssueUpdate {
	if v != nil {
		_u.SetHiddenCommentCount(*v)
	}
	return _u
}

// AddHiddenCommentCount adds value to the "hidden_comment_count" field.
func (_u *SupportIssueUpdate) AddHiddenCommentCount(v int) *SupportIssueUpdate {
	_u.mutation.AddHiddenCommentCount(v)
	return _u
}

// SetAttachmentCount sets the "attachment_count" field.
func (_u *SupportIssueUpdate) SetAttachmentCount(v int) *SupportIssueUpdate {
	_u.mutation.ResetAttachmentCount()
	_u.mutation.SetAttachmentCount(v)
	return _u
}

// SetNillableAttachmentCount sets the "attachment_count" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableAttachmentCount(v *int) *SupportIssueUpdate {
	if v != nil {
		_u.SetAttachmentCount(*v)
	}
	return _u
}

// AddAttachmentCount adds value to the "attachment_count" field.
func (_u *SupportIssueUpdate) AddAttachmentCount(v int) *SupportIssueUpdate {
	_u.mutation.AddAttachmentCount(v)
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *SupportIssueUpdate) SetViewCount(v int) *SupportIssueUpdate {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableViewCount(v *int) *SupportIssueUpdate {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *SupportIssueUpdate) AddViewCount(v int) *SupportIssueUpdate {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetSearchText sets the "search_text" field.
func (_u *SupportIssueUpdate) SetSearchText(v string) *SupportIssueUpdate {
	_u.mutation.SetSearchText(v)
	return _u
}

// SetNillableSearchText sets the "search_text" field if the given value is not nil.
func (_u *SupportIssueUpdate) SetNillableSearchText(v *string) *SupportIssueUpdate {
	if v != nil {
		_u.SetSearchText(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportIssueUpdate) SetUpdatedAt(v time.Time) *SupportIssueUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddCommentIDs adds the "comments" edge to the SupportIssueComment entity by IDs.
func (_u *SupportIssueUpdate) AddCommentIDs(ids ...int64) *SupportIssueUpdate {
	_u.mutation.AddCommentIDs(ids...)
	return _u
}

// AddComments adds the "comments" edges to the SupportIssueComment entity.
func (_u *SupportIssueUpdate) AddComments(v ...*SupportIssueComment) *SupportIssueUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentIDs(ids...)
}

// AddAttachmentIDs adds the "attachments" edge to the SupportIssueAttachment entity by IDs.
func (_u *SupportIssueUpdate) AddAttachmentIDs(ids ...int64) *SupportIssueUpdate {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the SupportIssueAttachment entity.
func (_u *SupportIssueUpdate) AddAttachments(v ...*SupportIssueAttachment) *SupportIssueUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// AddEventIDs adds the "events" edge to the SupportIssueEvent entity by IDs.
func (_u *SupportIssueUpdate) AddEventIDs(ids ...int64) *SupportIssueUpdate {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the SupportIssueEvent entity.
func (_u *SupportIssueUpdate) AddEvents(v ...*SupportIssueEvent) *SupportIssueUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// AddViewIDs adds the "views" edge to the SupportIssueView entity by IDs.
func (_u *SupportIssueUpdate) AddViewIDs(ids ...int64) *SupportIssueUpdate {
	_u.mutation.AddViewIDs(ids...)
	return _u
}

// AddViews adds the "views" edges to the SupportIssueView entity.
func (_u *SupportIssueUpdate) AddViews(v ...*SupportIssueView) *SupportIssueUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddViewIDs(ids...)
}

// Mutation returns the SupportIssueMutation object of the builder.
func (_u *SupportIssueUpdate) Mutation() *SupportIssueMutation {
	return _u.mutation
}

// ClearComments clears all "comments" edges to the SupportIssueComment entity.
func (_u *SupportIssueUpdate) ClearComments() *SupportIssueUpdate {
	_u.mutation.ClearComments()
	return _u
}

// RemoveCommentIDs removes the "comments" edge to SupportIssueComment entities by IDs.
func (_u *SupportIssueUpdate) RemoveCommentIDs(ids ...int64) *SupportIssueUpdate {
	_u.mutation.RemoveCommentIDs(ids...)
	return _u
}

// RemoveComments removes "comments" edges to SupportIssueComment entities.
func (_u *SupportIssueUpdate) RemoveComments(v ...*SupportIssueComment) *SupportIssueUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentIDs(ids...)
}

// ClearAttachments clears all "attachments" edges to the SupportIssueAttachment entity.
func (_u *SupportIssueUpdate) ClearAttachments() *SupportIssueUpdate {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to SupportIssueAttachment entities by IDs.
func (_u *SupportIssueUpdate) RemoveAttachmentIDs(ids ...int64) *SupportIssueUpdate {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to SupportIssueAttachment entities.
func (_u *SupportIssueUpdate) RemoveAttachments(v ...*SupportIssueAttachment) *SupportIssueUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// ClearEvents clears all "events" edges to the SupportIssueEvent entity.
func (_u *SupportIssueUpdate) ClearEvents() *SupportIssueUpdate {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to SupportIssueEvent entities by IDs.
func (_u *SupportIssueUpdate) RemoveEventIDs(ids ...int64) *SupportIssueUpdate {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to SupportIssueEvent entities.
func (_u *SupportIssueUpdate) RemoveEvents(v ...*SupportIssueEvent) *SupportIssueUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// ClearViews clears all "views" edges to the SupportIssueView entity.
func (_u *SupportIssueUpdate) ClearViews() *SupportIssueUpdate {
	_u.mutation.ClearViews()
	return _u
}

// RemoveViewIDs removes the "views" edge to SupportIssueView entities by IDs.
func (_u *SupportIssueUpdate) RemoveViewIDs(ids ...int64) *SupportIssueUpdate {
	_u.mutation.RemoveViewIDs(ids...)
	return _u
}

// RemoveViews removes "views" edges to SupportIssueView entities.
func (_u *SupportIssueUpdate) RemoveViews(v ...*SupportIssueView) *SupportIssueUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveViewIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupportIssueUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportIssueUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupportIssueUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportIssueUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportIssueUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportissue.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportIssueUpdate) check() error {
	if v, ok := _u.mutation.PublicID(); ok {
		if err := supportissue.PublicIDValidator(v); err != nil {
			return &ValidationError{Name: "public_id", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.public_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := supportissue.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := supportissue.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountEmail(); ok {
		if err := supportissue.AccountEmailValidator(v); err != nil {
			return &ValidationError{Name: "account_email", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.account_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountEmailNormalized(); ok {
		if err := supportissue.AccountEmailNormalizedValidator(v); err != nil {
			return &ValidationError{Name: "account_email_normalized", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.account_email_normalized": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountEmailMasked(); ok {
		if err := supportissue.AccountEmailMaskedValidator(v); err != nil {
			return &ValidationError{Name: "account_email_masked", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.account_email_masked": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScreenshotText(); ok {
		if err := supportissue.ScreenshotTextValidator(v); err != nil {
			return &ValidationError{Name: "screenshot_text", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.screenshot_text": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScreenshotLanguage(); ok {
		if err := supportissue.ScreenshotLanguageValidator(v); err != nil {
			return &ValidationError{Name: "screenshot_language", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.screenshot_language": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := supportissue.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Severity(); ok {
		if err := supportissue.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.severity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supportissue.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelName(); ok {
		if err := supportissue.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.model_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientName(); ok {
		if err := supportissue.ClientNameValidator(v); err != nil {
			return &ValidationError{Name: "client_name", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.client_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := supportissue.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKeySuffix(); ok {
		if err := supportissue.APIKeySuffixValidator(v); err != nil {
			return &ValidationError{Name: "api_key_suffix", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.api_key_suffix": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HideReason(); ok {
		if err := supportissue.HideReasonValidator(v); err != nil {
			return &ValidationError{Name: "hide_reason", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.hide_reason": %w`, err)}
		}
	}
	return nil
}

func (_u *SupportIssueUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportissue.Table, supportissue.Columns, sqlgraph.NewFieldSpec(supportissue.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PublicID(); ok {
		_spec.SetField(supportissue.FieldPublicID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(supportissue.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(supportissue.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountEmail(); ok {
		_spec.SetField(supportissue.FieldAccountEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountEmailNormalized(); ok {
		_spec.SetField(supportissue.FieldAccountEmailNormalized, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountEmailMasked(); ok {
		_spec.SetField(supportissue.FieldAccountEmailMasked, field.TypeString, value)
	}
	if value, ok := _u.mutation.OccurredAt(); ok {
		_spec.SetField(supportissue.FieldOccurredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ScreenshotText(); ok {
		_spec.SetField(supportissue.FieldScreenshotText, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScreenshotLanguage(); ok {
		_spec.SetField(supportissue.FieldScreenshotLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(supportissue.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(supportissue.FieldSeverity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supportissue.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(supportissue.FieldModelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientName(); ok {
		_spec.SetField(supportissue.FieldClientName, field.TypeString, value)
	}
	if value, ok := _u.mutation.HTTPStatus(); ok {
		_spec.SetField(supportissue.FieldHTTPStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHTTPStatus(); ok {
		_spec.AddField(supportissue.FieldHTTPStatus, field.TypeInt, value)
	}
	if _u.mutation.HTTPStatusCleared() {
		_spec.ClearField(supportissue.FieldHTTPStatus, field.TypeInt)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(supportissue.FieldErrorCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeySuffix(); ok {
		_spec.SetField(supportissue.FieldAPIKeySuffix, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedByUserID(); ok {
		_spec.SetField(supportissue.FieldCreatedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedByUserID(); ok {
		_spec.AddField(supportissue.FieldCreatedByUserID, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByUserIDCleared() {
		_spec.ClearField(supportissue.FieldCreatedByUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ResolvedByUserID(); ok {
		_spec.SetField(supportissue.FieldResolvedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedResolvedByUserID(); ok {
		_spec.AddField(supportissue.FieldResolvedByUserID, field.TypeInt64, value)
	}
	if _u.mutation.ResolvedByUserIDCleared() {
		_spec.ClearField(supportissue.FieldResolvedByUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ResolvedAt(); ok {
		_spec.SetField(supportissue.FieldResolvedAt, field.TypeTime, value)
	}
	if _u.mutation.ResolvedAtCleared() {
		_spec.ClearField(supportissue.FieldResolvedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LockedAt(); ok {
		_spec.SetField(supportissue.FieldLockedAt, field.TypeTime, value)
	}
	if _u.mutation.LockedAtCleared() {
		_spec.ClearField(supportissue.FieldLockedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HiddenAt(); ok {
		_spec.SetField(supportissue.FieldHiddenAt, field.TypeTime, value)
	}
	if _u.mutation.HiddenAtCleared() {
		_spec.ClearField(supportissue.FieldHiddenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HiddenByUserID(); ok {
		_spec.SetField(supportissue.FieldHiddenByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedHiddenByUserID(); ok {
		_spec.AddField(supportissue.FieldHiddenByUserID, field.TypeInt64, value)
	}
	if _u.mutation.HiddenByUserIDCleared() {
		_spec.ClearField(supportissue.FieldHiddenByUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.HideReason(); ok {
		_spec.SetField(supportissue.FieldHideReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastCommentAt(); ok {
		_spec.SetField(supportissue.FieldLastCommentAt, field.TypeTime, value)
	}
	if _u.mutation.LastCommentAtCleared() {
		_spec.ClearField(supportissue.FieldLastCommentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastViewedAt(); ok {
		_spec.SetField(supportissue.FieldLastViewedAt, field.TypeTime, value)
	}
	if _u.mutation.LastViewedAtCleared() {
		_spec.ClearField(supportissue.FieldLastViewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CommentCount(); ok {
		_spec.SetField(supportissue.FieldCommentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCommentCount(); ok {
		_spec.AddField(supportissue.FieldCommentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.HiddenCommentCount(); ok {
		_spec.SetField(supportissue.FieldHiddenCommentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHiddenCommentCount(); ok {
		_spec.AddField(supportissue.FieldHiddenCommentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AttachmentCount(); ok {
		_spec.SetField(supportissue.FieldAttachmentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttachmentCount(); ok {
		_spec.AddField(supportissue.FieldAttachmentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(supportissue.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(supportissue.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SearchText(); ok {
		_spec.SetField(supportissue.FieldSearchText, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportissue.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.CommentsTable,
			Columns: []string{supportissue.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissuecomment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !_u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.CommentsTable,
			Columns: []string{supportissue.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissuecomment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.CommentsTable,
			Columns: []string{supportissue.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissuecomment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.AttachmentsTable,
			Columns: []string{supportissue.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissueattachment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.AttachmentsTable,
			Columns: []string{supportissue.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissueattachment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.AttachmentsTable,
			Columns: []string{supportissue.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissueattachment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.EventsTable,
			Columns: []string{supportissue.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissueevent.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.EventsTable,
			Columns: []string{supportissue.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissueevent.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.EventsTable,
			Columns: []string{supportissue.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissueevent.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ViewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.ViewsTable,
			Columns: []string{supportissue.ViewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissueview.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedViewsIDs(); len(nodes) > 0 && !_u.mutation.ViewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.ViewsTable,
			Columns: []string{supportissue.ViewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissueview.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ViewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.ViewsTable,
			Columns: []string{supportissue.ViewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissueview.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportissue.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupportIssueUpdateOne is the builder for updating a single SupportIssue entity.
type SupportIssueUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupportIssueMutation
}

// SetPublicID sets the "public_id" field.
func (_u *SupportIssueUpdateOne) SetPublicID(v string) *SupportIssueUpdateOne {
	_u.mutation.SetPublicID(v)
	return _u
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillablePublicID(v *string) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetPublicID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *SupportIssueUpdateOne) SetTitle(v string) *SupportIssueUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableTitle(v *string) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SupportIssueUpdateOne) SetDescription(v string) *SupportIssueUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableDescription(v *string) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetAccountEmail sets the "account_email" field.
func (_u *SupportIssueUpdateOne) SetAccountEmail(v string) *SupportIssueUpdateOne {
	_u.mutation.SetAccountEmail(v)
	return _u
}

// SetNillableAccountEmail sets the "account_email" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableAccountEmail(v *string) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetAccountEmail(*v)
	}
	return _u
}

// SetAccountEmailNormalized sets the "account_email_normalized" field.
func (_u *SupportIssueUpdateOne) SetAccountEmailNormalized(v string) *SupportIssueUpdateOne {
	_u.mutation.SetAccountEmailNormalized(v)
	return _u
}

// SetNillableAccountEmailNormalized sets the "account_email_normalized" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableAccountEmailNormalized(v *string) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetAccountEmailNormalized(*v)
	}
	return _u
}

// SetAccountEmailMasked sets the "account_email_masked" field.
func (_u *SupportIssueUpdateOne) SetAccountEmailMasked(v string) *SupportIssueUpdateOne {
	_u.mutation.SetAccountEmailMasked(v)
	return _u
}

// SetNillableAccountEmailMasked sets the "account_email_masked" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableAccountEmailMasked(v *string) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetAccountEmailMasked(*v)
	}
	return _u
}

// SetOccurredAt sets the "occurred_at" field.
func (_u *SupportIssueUpdateOne) SetOccurredAt(v time.Time) *SupportIssueUpdateOne {
	_u.mutation.SetOccurredAt(v)
	return _u
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableOccurredAt(v *time.Time) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetOccurredAt(*v)
	}
	return _u
}

// SetScreenshotText sets the "screenshot_text" field.
func (_u *SupportIssueUpdateOne) SetScreenshotText(v string) *SupportIssueUpdateOne {
	_u.mutation.SetScreenshotText(v)
	return _u
}

// SetNillableScreenshotText sets the "screenshot_text" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableScreenshotText(v *string) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetScreenshotText(*v)
	}
	return _u
}

// SetScreenshotLanguage sets the "screenshot_language" field.
func (_u *SupportIssueUpdateOne) SetScreenshotLanguage(v string) *SupportIssueUpdateOne {
	_u.mutation.SetScreenshotLanguage(v)
	return _u
}

// SetNillableScreenshotLanguage sets the "screenshot_language" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableScreenshotLanguage(v *string) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetScreenshotLanguage(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *SupportIssueUpdateOne) SetCategory(v string) *SupportIssueUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableCategory(v *string) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *SupportIssueUpdateOne) SetSeverity(v string) *SupportIssueUpdateOne {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableSeverity(v *string) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupportIssueUpdateOne) SetStatus(v string) *SupportIssueUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableStatus(v *string) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *SupportIssueUpdateOne) SetModelName(v string) *SupportIssueUpdateOne {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableModelName(v *string) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// SetClientName sets the "client_name" field.
func (_u *SupportIssueUpdateOne) SetClientName(v string) *SupportIssueUpdateOne {
	_u.mutation.SetClientName(v)
	return _u
}

// SetNillableClientName sets the "client_name" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableClientName(v *string) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetClientName(*v)
	}
	return _u
}

// SetHTTPStatus sets the "http_status" field.
func (_u *SupportIssueUpdateOne) SetHTTPStatus(v int) *SupportIssueUpdateOne {
	_u.mutation.ResetHTTPStatus()
	_u.mutation.SetHTTPStatus(v)
	return _u
}

// SetNillableHTTPStatus sets the "http_status" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableHTTPStatus(v *int) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetHTTPStatus(*v)
	}
	return _u
}

// AddHTTPStatus adds value to the "http_status" field.
func (_u *SupportIssueUpdateOne) AddHTTPStatus(v int) *SupportIssueUpdateOne {
	_u.mutation.AddHTTPStatus(v)
	return _u
}

// ClearHTTPStatus clears the value of the "http_status" field.
func (_u *SupportIssueUpdateOne) ClearHTTPStatus() *SupportIssueUpdateOne {
	_u.mutation.ClearHTTPStatus()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *SupportIssueUpdateOne) SetErrorCode(v string) *SupportIssueUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableErrorCode(v *string) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// SetAPIKeySuffix sets the "api_key_suffix" field.
func (_u *SupportIssueUpdateOne) SetAPIKeySuffix(v string) *SupportIssueUpdateOne {
	_u.mutation.SetAPIKeySuffix(v)
	return _u
}

// SetNillableAPIKeySuffix sets the "api_key_suffix" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableAPIKeySuffix(v *string) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetAPIKeySuffix(*v)
	}
	return _u
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_u *SupportIssueUpdateOne) SetCreatedByUserID(v int64) *SupportIssueUpdateOne {
	_u.mutation.ResetCreatedByUserID()
	_u.mutation.SetCreatedByUserID(v)
	return _u
}

// SetNillableCreatedByUserID sets the "created_by_user_id" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableCreatedByUserID(v *int64) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetCreatedByUserID(*v)
	}
	return _u
}

// AddCreatedByUserID adds value to the "created_by_user_id" field.
func (_u *SupportIssueUpdateOne) AddCreatedByUserID(v int64) *SupportIssueUpdateOne {
	_u.mutation.AddCreatedByUserID(v)
	return _u
}

// ClearCreatedByUserID clears the value of the "created_by_user_id" field.
func (_u *SupportIssueUpdateOne) ClearCreatedByUserID() *SupportIssueUpdateOne {
	_u.mutation.ClearCreatedByUserID()
	return _u
}

// SetResolvedByUserID sets the "resolved_by_user_id" field.
func (_u *SupportIssueUpdateOne) SetResolvedByUserID(v int64) *SupportIssueUpdateOne {
	_u.mutation.ResetResolvedByUserID()
	_u.mutation.SetResolvedByUserID(v)
	return _u
}

// SetNillableResolvedByUserID sets the "resolved_by_user_id" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableResolvedByUserID(v *int64) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetResolvedByUserID(*v)
	}
	return _u
}

// AddResolvedByUserID adds value to the "resolved_by_user_id" field.
func (_u *SupportIssueUpdateOne) AddResolvedByUserID(v int64) *SupportIssueUpdateOne {
	_u.mutation.AddResolvedByUserID(v)
	return _u
}

// ClearResolvedByUserID clears the value of the "resolved_by_user_id" field.
func (_u *SupportIssueUpdateOne) ClearResolvedByUserID() *SupportIssueUpdateOne {
	_u.mutation.ClearResolvedByUserID()
	return _u
}

// SetResolvedAt sets the "resolved_at" field.
func (_u *SupportIssueUpdateOne) SetResolvedAt(v time.Time) *SupportIssueUpdateOne {
	_u.mutation.SetResolvedAt(v)
	return _u
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableResolvedAt(v *time.Time) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetResolvedAt(*v)
	}
	return _u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (_u *SupportIssueUpdateOne) ClearResolvedAt() *SupportIssueUpdateOne {
	_u.mutation.ClearResolvedAt()
	return _u
}

// SetLockedAt sets the "locked_at" field.
func (_u *SupportIssueUpdateOne) SetLockedAt(v time.Time) *SupportIssueUpdateOne {
	_u.mutation.SetLockedAt(v)
	return _u
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableLockedAt(v *time.Time) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetLockedAt(*v)
	}
	return _u
}

// ClearLockedAt clears the value of the "locked_at" field.
func (_u *SupportIssueUpdateOne) ClearLockedAt() *SupportIssueUpdateOne {
	_u.mutation.ClearLockedAt()
	return _u
}

// SetHiddenAt sets the "hidden_at" field.
func (_u *SupportIssueUpdateOne) SetHiddenAt(v time.Time) *SupportIssueUpdateOne {
	_u.mutation.SetHiddenAt(v)
	return _u
}

// SetNillableHiddenAt sets the "hidden_at" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableHiddenAt(v *time.Time) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetHiddenAt(*v)
	}
	return _u
}

// ClearHiddenAt clears the value of the "hidden_at" field.
func (_u *SupportIssueUpdateOne) ClearHiddenAt() *SupportIssueUpdateOne {
	_u.mutation.ClearHiddenAt()
	return _u
}

// SetHiddenByUserID sets the "hidden_by_user_id" field.
func (_u *SupportIssueUpdateOne) SetHiddenByUserID(v int64) *SupportIssueUpdateOne {
	_u.mutation.ResetHiddenByUserID()
	_u.mutation.SetHiddenByUserID(v)
	return _u
}

// SetNillableHiddenByUserID sets the "hidden_by_user_id" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableHiddenByUserID(v *int64) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetHiddenByUserID(*v)
	}
	return _u
}

// AddHiddenByUserID adds value to the "hidden_by_user_id" field.
func (_u *SupportIssueUpdateOne) AddHiddenByUserID(v int64) *SupportIssueUpdateOne {
	_u.mutation.AddHiddenByUserID(v)
	return _u
}

// ClearHiddenByUserID clears the value of the "hidden_by_user_id" field.
func (_u *SupportIssueUpdateOne) ClearHiddenByUserID() *SupportIssueUpdateOne {
	_u.mutation.ClearHiddenByUserID()
	return _u
}

// SetHideReason sets the "hide_reason" field.
func (_u *SupportIssueUpdateOne) SetHideReason(v string) *SupportIssueUpdateOne {
	_u.mutation.SetHideReason(v)
	return _u
}

// SetNillableHideReason sets the "hide_reason" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableHideReason(v *string) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetHideReason(*v)
	}
	return _u
}

// SetLastCommentAt sets the "last_comment_at" field.
func (_u *SupportIssueUpdateOne) SetLastCommentAt(v time.Time) *SupportIssueUpdateOne {
	_u.mutation.SetLastCommentAt(v)
	return _u
}

// SetNillableLastCommentAt sets the "last_comment_at" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableLastCommentAt(v *time.Time) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetLastCommentAt(*v)
	}
	return _u
}

// ClearLastCommentAt clears the value of the "last_comment_at" field.
func (_u *SupportIssueUpdateOne) ClearLastCommentAt() *SupportIssueUpdateOne {
	_u.mutation.ClearLastCommentAt()
	return _u
}

// SetLastViewedAt sets the "last_viewed_at" field.
func (_u *SupportIssueUpdateOne) SetLastViewedAt(v time.Time) *SupportIssueUpdateOne {
	_u.mutation.SetLastViewedAt(v)
	return _u
}

// SetNillableLastViewedAt sets the "last_viewed_at" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableLastViewedAt(v *time.Time) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetLastViewedAt(*v)
	}
	return _u
}

// ClearLastViewedAt clears the value of the "last_viewed_at" field.
func (_u *SupportIssueUpdateOne) ClearLastViewedAt() *SupportIssueUpdateOne {
	_u.mutation.ClearLastViewedAt()
	return _u
}

// SetCommentCount sets the "comment_count" field.
func (_u *SupportIssueUpdateOne) SetCommentCount(v int) *SupportIssueUpdateOne {
	_u.mutation.ResetCommentCount()
	_u.mutation.SetCommentCount(v)
	return _u
}

// SetNillableCommentCount sets the "comment_count" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableCommentCount(v *int) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetCommentCount(*v)
	}
	return _u
}

// AddCommentCount adds value to the "comment_count" field.
func (_u *SupportIssueUpdateOne) AddCommentCount(v int) *SupportIssueUpdateOne {
	_u.mutation.AddCommentCount(v)
	return _u
}

// SetHiddenCommentCount sets the "hidden_comment_count" field.
func (_u *SupportIssueUpdateOne) SetHiddenCommentCount(v int) *SupportIssueUpdateOne {
	_u.mutation.ResetHiddenCommentCount()
	_u.mutation.SetHiddenCommentCount(v)
	return _u
}

// SetNillableHiddenCommentCount sets the "hidden_comment_count" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableHiddenCommentCount(v *int) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetHiddenCommentCount(*v)
	}
	return _u
}

// AddHiddenCommentCount adds value to the "hidden_comment_count" field.
func (_u *SupportIssueUpdateOne) AddHiddenCommentCount(v int) *SupportIssueUpdateOne {
	_u.mutation.AddHiddenCommentCount(v)
	return _u
}

// SetAttachmentCount sets the "attachment_count" field.
func (_u *SupportIssueUpdateOne) SetAttachmentCount(v int) *SupportIssueUpdateOne {
	_u.mutation.ResetAttachmentCount()
	_u.mutation.SetAttachmentCount(v)
	return _u
}

// SetNillableAttachmentCount sets the "attachment_count" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableAttachmentCount(v *int) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetAttachmentCount(*v)
	}
	return _u
}

// AddAttachmentCount adds value to the "attachment_count" field.
func (_u *SupportIssueUpdateOne) AddAttachmentCount(v int) *SupportIssueUpdateOne {
	_u.mutation.AddAttachmentCount(v)
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *SupportIssueUpdateOne) SetViewCount(v int) *SupportIssueUpdateOne {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableViewCount(v *int) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *SupportIssueUpdateOne) AddViewCount(v int) *SupportIssueUpdateOne {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetSearchText sets the "search_text" field.
func (_u *SupportIssueUpdateOne) SetSearchText(v string) *SupportIssueUpdateOne {
	_u.mutation.SetSearchText(v)
	return _u
}

// SetNillableSearchText sets the "search_text" field if the given value is not nil.
func (_u *SupportIssueUpdateOne) SetNillableSearchText(v *string) *SupportIssueUpdateOne {
	if v != nil {
		_u.SetSearchText(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportIssueUpdateOne) SetUpdatedAt(v time.Time) *SupportIssueUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddCommentIDs adds the "comments" edge to the SupportIssueComment entity by IDs.
func (_u *SupportIssueUpdateOne) AddCommentIDs(ids ...int64) *SupportIssueUpdateOne {
	_u.mutation.AddCommentIDs(ids...)
	return _u
}

// AddComments adds the "comments" edges to the SupportIssueComment entity.
func (_u *SupportIssueUpdateOne) AddComments(v ...*SupportIssueComment) *SupportIssueUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentIDs(ids...)
}

// AddAttachmentIDs adds the "attachments" edge to the SupportIssueAttachment entity by IDs.
func (_u *SupportIssueUpdateOne) AddAttachmentIDs(ids ...int64) *SupportIssueUpdateOne {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the SupportIssueAttachment entity.
func (_u *SupportIssueUpdateOne) AddAttachments(v ...*SupportIssueAttachment) *SupportIssueUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// AddEventIDs adds the "events" edge to the SupportIssueEvent entity by IDs.
func (_u *SupportIssueUpdateOne) AddEventIDs(ids ...int64) *SupportIssueUpdateOne {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the SupportIssueEvent entity.
func (_u *SupportIssueUpdateOne) AddEvents(v ...*SupportIssueEvent) *SupportIssueUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// AddViewIDs adds the "views" edge to the SupportIssueView entity by IDs.
func (_u *SupportIssueUpdateOne) AddViewIDs(ids ...int64) *SupportIssueUpdateOne {
	_u.mutation.AddViewIDs(ids...)
	return _u
}

// AddViews adds the "views" edges to the SupportIssueView entity.
func (_u *SupportIssueUpdateOne) AddViews(v ...*SupportIssueView) *SupportIssueUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddViewIDs(ids...)
}

// Mutation returns the SupportIssueMutation object of the builder.
func (_u *SupportIssueUpdateOne) Mutation() *SupportIssueMutation {
	return _u.mutation
}

// ClearComments clears all "comments" edges to the SupportIssueComment entity.
func (_u *SupportIssueUpdateOne) ClearComments() *SupportIssueUpdateOne {
	_u.mutation.ClearComments()
	return _u
}

// RemoveCommentIDs removes the "comments" edge to SupportIssueComment entities by IDs.
func (_u *SupportIssueUpdateOne) RemoveCommentIDs(ids ...int64) *SupportIssueUpdateOne {
	_u.mutation.RemoveCommentIDs(ids...)
	return _u
}

// RemoveComments removes "comments" edges to SupportIssueComment entities.
func (_u *SupportIssueUpdateOne) RemoveComments(v ...*SupportIssueComment) *SupportIssueUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentIDs(ids...)
}

// ClearAttachments clears all "attachments" edges to the SupportIssueAttachment entity.
func (_u *SupportIssueUpdateOne) ClearAttachments() *SupportIssueUpdateOne {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to SupportIssueAttachment entities by IDs.
func (_u *SupportIssueUpdateOne) RemoveAttachmentIDs(ids ...int64) *SupportIssueUpdateOne {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to SupportIssueAttachment entities.
func (_u *SupportIssueUpdateOne) RemoveAttachments(v ...*SupportIssueAttachment) *SupportIssueUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// ClearEvents clears all "events" edges to the SupportIssueEvent entity.
func (_u *SupportIssueUpdateOne) ClearEvents() *SupportIssueUpdateOne {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to SupportIssueEvent entities by IDs.
func (_u *SupportIssueUpdateOne) RemoveEventIDs(ids ...int64) *SupportIssueUpdateOne {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to SupportIssueEvent entities.
func (_u *SupportIssueUpdateOne) RemoveEvents(v ...*SupportIssueEvent) *SupportIssueUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// ClearViews clears all "views" edges to the SupportIssueView entity.
func (_u *SupportIssueUpdateOne) ClearViews() *SupportIssueUpdateOne {
	_u.mutation.ClearViews()
	return _u
}

// RemoveViewIDs removes the "views" edge to SupportIssueView entities by IDs.
func (_u *SupportIssueUpdateOne) RemoveViewIDs(ids ...int64) *SupportIssueUpdateOne {
	_u.mutation.RemoveViewIDs(ids...)
	return _u
}

// RemoveViews removes "views" edges to SupportIssueView entities.
func (_u *SupportIssueUpdateOne) RemoveViews(v ...*SupportIssueView) *SupportIssueUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveViewIDs(ids...)
}

// Where appends a list predicates to the SupportIssueUpdate builder.
func (_u *SupportIssueUpdateOne) Where(ps ...predicate.SupportIssue) *SupportIssueUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupportIssueUpdateOne) Select(field string, fields ...string) *SupportIssueUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupportIssue entity.
func (_u *SupportIssueUpdateOne) Save(ctx context.Context) (*SupportIssue, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportIssueUpdateOne) SaveX(ctx context.Context) *SupportIssue {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupportIssueUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportIssueUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportIssueUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportissue.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportIssueUpdateOne) check() error {
	if v, ok := _u.mutation.PublicID(); ok {
		if err := supportissue.PublicIDValidator(v); err != nil {
			return &ValidationError{Name: "public_id", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.public_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := supportissue.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := supportissue.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountEmail(); ok {
		if err := supportissue.AccountEmailValidator(v); err != nil {
			return &ValidationError{Name: "account_email", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.account_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountEmailNormalized(); ok {
		if err := supportissue.AccountEmailNormalizedValidator(v); err != nil {
			return &ValidationError{Name: "account_email_normalized", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.account_email_normalized": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountEmailMasked(); ok {
		if err := supportissue.AccountEmailMaskedValidator(v); err != nil {
			return &ValidationError{Name: "account_email_masked", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.account_email_masked": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScreenshotText(); ok {
		if err := supportissue.ScreenshotTextValidator(v); err != nil {
			return &ValidationError{Name: "screenshot_text", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.screenshot_text": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScreenshotLanguage(); ok {
		if err := supportissue.ScreenshotLanguageValidator(v); err != nil {
			return &ValidationError{Name: "screenshot_language", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.screenshot_language": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := supportissue.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Severity(); ok {
		if err := supportissue.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.severity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supportissue.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelName(); ok {
		if err := supportissue.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.model_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientName(); ok {
		if err := supportissue.ClientNameValidator(v); err != nil {
			return &ValidationError{Name: "client_name", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.client_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := supportissue.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKeySuffix(); ok {
		if err := supportissue.APIKeySuffixValidator(v); err != nil {
			return &ValidationError{Name: "api_key_suffix", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.api_key_suffix": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HideReason(); ok {
		if err := supportissue.HideReasonValidator(v); err != nil {
			return &ValidationError{Name: "hide_reason", err: fmt.Errorf(`ent: validator failed for field "SupportIssue.hide_reason": %w`, err)}
		}
	}
	return nil
}

func (_u *SupportIssueUpdateOne) sqlSave(ctx context.Context) (_node *SupportIssue, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportissue.Table, supportissue.Columns, sqlgraph.NewFieldSpec(supportissue.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupportIssue.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportissue.FieldID)
		for _, f := range fields {
			if !supportissue.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supportissue.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PublicID(); ok {
		_spec.SetField(supportissue.FieldPublicID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(supportissue.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(supportissue.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountEmail(); ok {
		_spec.SetField(supportissue.FieldAccountEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountEmailNormalized(); ok {
		_spec.SetField(supportissue.FieldAccountEmailNormalized, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountEmailMasked(); ok {
		_spec.SetField(supportissue.FieldAccountEmailMasked, field.TypeString, value)
	}
	if value, ok := _u.mutation.OccurredAt(); ok {
		_spec.SetField(supportissue.FieldOccurredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ScreenshotText(); ok {
		_spec.SetField(supportissue.FieldScreenshotText, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScreenshotLanguage(); ok {
		_spec.SetField(supportissue.FieldScreenshotLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(supportissue.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(supportissue.FieldSeverity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supportissue.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(supportissue.FieldModelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientName(); ok {
		_spec.SetField(supportissue.FieldClientName, field.TypeString, value)
	}
	if value, ok := _u.mutation.HTTPStatus(); ok {
		_spec.SetField(supportissue.FieldHTTPStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHTTPStatus(); ok {
		_spec.AddField(supportissue.FieldHTTPStatus, field.TypeInt, value)
	}
	if _u.mutation.HTTPStatusCleared() {
		_spec.ClearField(supportissue.FieldHTTPStatus, field.TypeInt)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(supportissue.FieldErrorCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeySuffix(); ok {
		_spec.SetField(supportissue.FieldAPIKeySuffix, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedByUserID(); ok {
		_spec.SetField(supportissue.FieldCreatedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedByUserID(); ok {
		_spec.AddField(supportissue.FieldCreatedByUserID, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByUserIDCleared() {
		_spec.ClearField(supportissue.FieldCreatedByUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ResolvedByUserID(); ok {
		_spec.SetField(supportissue.FieldResolvedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedResolvedByUserID(); ok {
		_spec.AddField(supportissue.FieldResolvedByUserID, field.TypeInt64, value)
	}
	if _u.mutation.ResolvedByUserIDCleared() {
		_spec.ClearField(supportissue.FieldResolvedByUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ResolvedAt(); ok {
		_spec.SetField(supportissue.FieldResolvedAt, field.TypeTime, value)
	}
	if _u.mutation.ResolvedAtCleared() {
		_spec.ClearField(supportissue.FieldResolvedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LockedAt(); ok {
		_spec.SetField(supportissue.FieldLockedAt, field.TypeTime, value)
	}
	if _u.mutation.LockedAtCleared() {
		_spec.ClearField(supportissue.FieldLockedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HiddenAt(); ok {
		_spec.SetField(supportissue.FieldHiddenAt, field.TypeTime, value)
	}
	if _u.mutation.HiddenAtCleared() {
		_spec.ClearField(supportissue.FieldHiddenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HiddenByUserID(); ok {
		_spec.SetField(supportissue.FieldHiddenByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedHiddenByUserID(); ok {
		_spec.AddField(supportissue.FieldHiddenByUserID, field.TypeInt64, value)
	}
	if _u.mutation.HiddenByUserIDCleared() {
		_spec.ClearField(supportissue.FieldHiddenByUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.HideReason(); ok {
		_spec.SetField(supportissue.FieldHideReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastCommentAt(); ok {
		_spec.SetField(supportissue.FieldLastCommentAt, field.TypeTime, value)
	}
	if _u.mutation.LastCommentAtCleared() {
		_spec.ClearField(supportissue.FieldLastCommentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastViewedAt(); ok {
		_spec.SetField(supportissue.FieldLastViewedAt, field.TypeTime, value)
	}
	if _u.mutation.LastViewedAtCleared() {
		_spec.ClearField(supportissue.FieldLastViewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CommentCount(); ok {
		_spec.SetField(supportissue.FieldCommentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCommentCount(); ok {
		_spec.AddField(supportissue.FieldCommentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.HiddenCommentCount(); ok {
		_spec.SetField(supportissue.FieldHiddenCommentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHiddenCommentCount(); ok {
		_spec.AddField(supportissue.FieldHiddenCommentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AttachmentCount(); ok {
		_spec.SetField(supportissue.FieldAttachmentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttachmentCount(); ok {
		_spec.AddField(supportissue.FieldAttachmentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(supportissue.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(supportissue.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SearchText(); ok {
		_spec.SetField(supportissue.FieldSearchText, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportissue.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.CommentsTable,
			Columns: []string{supportissue.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissuecomment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !_u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.CommentsTable,
			Columns: []string{supportissue.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissuecomment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.CommentsTable,
			Columns: []string{supportissue.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissuecomment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.AttachmentsTable,
			Columns: []string{supportissue.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissueattachment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.AttachmentsTable,
			Columns: []string{supportissue.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissueattachment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.AttachmentsTable,
			Columns: []string{supportissue.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissueattachment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.EventsTable,
			Columns: []string{supportissue.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissueevent.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.EventsTable,
			Columns: []string{supportissue.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissueevent.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.EventsTable,
			Columns: []string{supportissue.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissueevent.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ViewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.ViewsTable,
			Columns: []string{supportissue.ViewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissueview.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedViewsIDs(); len(nodes) > 0 && !_u.mutation.ViewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.ViewsTable,
			Columns: []string{supportissue.ViewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissueview.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ViewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportissue.ViewsTable,
			Columns: []string{supportissue.ViewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportissueview.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SupportIssue{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportissue.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
