// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
	"github.com/Wei-Shaw/sub2api/ent/upstreamconnection"
)

// UpstreamConnection is the model entity for the UpstreamConnection schema.
type UpstreamConnection struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// AuthMode holds the value of the "auth_mode" field.
	AuthMode string `json:"auth_mode,omitempty"`
	// ManagementBaseURL holds the value of the "management_base_url" field.
	ManagementBaseURL string `json:"management_base_url,omitempty"`
	// ForwardingBaseURL holds the value of the "forwarding_base_url" field.
	ForwardingBaseURL string `json:"forwarding_base_url,omitempty"`
	// CredentialEncrypted holds the value of the "credential_encrypted" field.
	CredentialEncrypted string `json:"-"`
	// CredentialFingerprint holds the value of the "credential_fingerprint" field.
	CredentialFingerprint string `json:"-"`
	// LegacyMigrationKey holds the value of the "legacy_migration_key" field.
	LegacyMigrationKey *string `json:"-"`
	// CredentialHint holds the value of the "credential_hint" field.
	CredentialHint string `json:"credential_hint,omitempty"`
	// RemoteUserID holds the value of the "remote_user_id" field.
	RemoteUserID string `json:"remote_user_id,omitempty"`
	// ProxyID holds the value of the "proxy_id" field.
	ProxyID *int64 `json:"proxy_id,omitempty"`
	// Capabilities holds the value of the "capabilities" field.
	Capabilities map[string]interface{} `json:"capabilities,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError string `json:"last_error,omitempty"`
	// SyncEnabled holds the value of the "sync_enabled" field.
	SyncEnabled bool `json:"sync_enabled,omitempty"`
	// SyncIntervalSeconds holds the value of the "sync_interval_seconds" field.
	SyncIntervalSeconds int `json:"sync_interval_seconds,omitempty"`
	// SyncFailures holds the value of the "sync_failures" field.
	SyncFailures int `json:"sync_failures,omitempty"`
	// Version holds the value of the "version" field.
	Version int64 `json:"version,omitempty"`
	// WalletAmount holds the value of the "wallet_amount" field.
	WalletAmount *float64 `json:"wallet_amount,omitempty"`
	// WalletCurrency holds the value of the "wallet_currency" field.
	WalletCurrency string `json:"wallet_currency,omitempty"`
	// WalletUsd holds the value of the "wallet_usd" field.
	WalletUsd *float64 `json:"wallet_usd,omitempty"`
	// WalletUnlimited holds the value of the "wallet_unlimited" field.
	WalletUnlimited bool `json:"wallet_unlimited,omitempty"`
	// WalletSource holds the value of the "wallet_source" field.
	WalletSource string `json:"wallet_source,omitempty"`
	// WalletReliability holds the value of the "wallet_reliability" field.
	WalletReliability string `json:"wallet_reliability,omitempty"`
	// WalletRaw holds the value of the "wallet_raw" field.
	WalletRaw map[string]interface{} `json:"wallet_raw,omitempty"`
	// WalletObservedAt holds the value of the "wallet_observed_at" field.
	WalletObservedAt *time.Time `json:"wallet_observed_at,omitempty"`
	// LastDiscoveredAt holds the value of the "last_discovered_at" field.
	LastDiscoveredAt *time.Time `json:"last_discovered_at,omitempty"`
	// LastSyncedAt holds the value of the "last_synced_at" field.
	LastSyncedAt *time.Time `json:"last_synced_at,omitempty"`
	// NextSyncAt holds the value of the "next_sync_at" field.
	NextSyncAt *time.Time `json:"next_sync_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UpstreamConnectionQuery when eager-loading is set.
	Edges        UpstreamConnectionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UpstreamConnectionEdges holds the relations/edges for other nodes in the graph.
type UpstreamConnectionEdges struct {
	// Proxy holds the value of the proxy edge.
	Proxy *Proxy `json:"proxy,omitempty"`
	// Groups holds the value of the groups edge.
	Groups []*UpstreamGroup `json:"groups,omitempty"`
	// AccountBindings holds the value of the account_bindings edge.
	AccountBindings []*UpstreamAccountBinding `json:"account_bindings,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ProxyOrErr returns the Proxy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UpstreamConnectionEdges) ProxyOrErr() (*Proxy, error) {
	if e.Proxy != nil {
		return e.Proxy, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: proxy.Label}
	}
	return nil, &NotLoadedError{edge: "proxy"}
}

// GroupsOrErr returns the Groups value or an error if the edge
// was not loaded in eager-loading.
func (e UpstreamConnectionEdges) GroupsOrErr() ([]*UpstreamGroup, error) {
	if e.loadedTypes[1] {
		return e.Groups, nil
	}
	return nil, &NotLoadedError{edge: "groups"}
}

// AccountBindingsOrErr returns the AccountBindings value or an error if the edge
// was not loaded in eager-loading.
func (e UpstreamConnectionEdges) AccountBindingsOrErr() ([]*UpstreamAccountBinding, error) {
	if e.loadedTypes[2] {
		return e.AccountBindings, nil
	}
	return nil, &NotLoadedError{edge: "account_bindings"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamConnection) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreamconnection.FieldCapabilities, upstreamconnection.FieldWalletRaw:
			values[i] = new([]byte)
		case upstreamconnection.FieldSyncEnabled, upstreamconnection.FieldWalletUnlimited:
			values[i] = new(sql.NullBool)
		case upstreamconnection.FieldWalletAmount, upstreamconnection.FieldWalletUsd:
			values[i] = new(sql.NullFloat64)
		case upstreamconnection.FieldID, upstreamconnection.FieldProxyID, upstreamconnection.FieldSyncIntervalSeconds, upstreamconnection.FieldSyncFailures, upstreamconnection.FieldVersion:
			values[i] = new(sql.NullInt64)
		case upstreamconnection.FieldName, upstreamconnection.FieldProvider, upstreamconnection.FieldAuthMode, upstreamconnection.FieldManagementBaseURL, upstreamconnection.FieldForwardingBaseURL, upstreamconnection.FieldCredentialEncrypted, upstreamconnection.FieldCredentialFingerprint, upstreamconnection.FieldLegacyMigrationKey, upstreamconnection.FieldCredentialHint, upstreamconnection.FieldRemoteUserID, upstreamconnection.FieldStatus, upstreamconnection.FieldLastError, upstreamconnection.FieldWalletCurrency, upstreamconnection.FieldWalletSource, upstreamconnection.FieldWalletReliability:
			values[i] = new(sql.NullString)
		case upstreamconnection.FieldCreatedAt, upstreamconnection.FieldUpdatedAt, upstreamconnection.FieldWalletObservedAt, upstreamconnection.FieldLastDiscoveredAt, upstreamconnection.FieldLastSyncedAt, upstreamconnection.FieldNextSyncAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamConnection fields.
func (_m *UpstreamConnection) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreamconnection.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upstreamconnection.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case upstreamconnection.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case upstreamconnection.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case upstreamconnection.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case upstreamconnection.FieldAuthMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_mode", values[i])
			} else if value.Valid {
				_m.AuthMode = value.String
			}
		case upstreamconnection.FieldManagementBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field management_base_url", values[i])
			} else if value.Valid {
				_m.ManagementBaseURL = value.String
			}
		case upstreamconnection.FieldForwardingBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field forwarding_base_url", values[i])
			} else if value.Valid {
				_m.ForwardingBaseURL = value.String
			}
		case upstreamconnection.FieldCredentialEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field credential_encrypted", values[i])
			} else if value.Valid {
				_m.CredentialEncrypted = value.String
			}
		case upstreamconnection.FieldCredentialFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field credential_fingerprint", values[i])
			} else if value.Valid {
				_m.CredentialFingerprint = value.String
			}
		case upstreamconnection.FieldLegacyMigrationKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field legacy_migration_key", values[i])
			} else if value.Valid {
				_m.LegacyMigrationKey = new(string)
				*_m.LegacyMigrationKey = value.String
			}
		case upstreamconnection.FieldCredentialHint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field credential_hint", values[i])
			} else if value.Valid {
				_m.CredentialHint = value.String
			}
		case upstreamconnection.FieldRemoteUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remote_user_id", values[i])
			} else if value.Valid {
				_m.RemoteUserID = value.String
			}
		case upstreamconnection.FieldProxyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field proxy_id", values[i])
			} else if value.Valid {
				_m.ProxyID = new(int64)
				*_m.ProxyID = value.Int64
			}
		case upstreamconnection.FieldCapabilities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field capabilities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Capabilities); err != nil {
					return fmt.Errorf("unmarshal field capabilities: %w", err)
				}
			}
		case upstreamconnection.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case upstreamconnection.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		case upstreamconnection.FieldSyncEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field sync_enabled", values[i])
			} else if value.Valid {
				_m.SyncEnabled = value.Bool
			}
		case upstreamconnection.FieldSyncIntervalSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sync_interval_seconds", values[i])
			} else if value.Valid {
				_m.SyncIntervalSeconds = int(value.Int64)
			}
		case upstreamconnection.FieldSyncFailures:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sync_failures", values[i])
			} else if value.Valid {
				_m.SyncFailures = int(value.Int64)
			}
		case upstreamconnection.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		case upstreamconnection.FieldWalletAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field wallet_amount", values[i])
			} else if value.Valid {
				_m.WalletAmount = new(float64)
				*_m.WalletAmount = value.Float64
			}
		case upstreamconnection.FieldWalletCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field wallet_currency", values[i])
			} else if value.Valid {
				_m.WalletCurrency = value.String
			}
		case upstreamconnection.FieldWalletUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field wallet_usd", values[i])
			} else if value.Valid {
				_m.WalletUsd = new(float64)
				*_m.WalletUsd = value.Float64
			}
		case upstreamconnection.FieldWalletUnlimited:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field wallet_unlimited", values[i])
			} else if value.Valid {
				_m.WalletUnlimited = value.Bool
			}
		case upstreamconnection.FieldWalletSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field wallet_source", values[i])
			} else if value.Valid {
				_m.WalletSource = value.String
			}
		case upstreamconnection.FieldWalletReliability:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field wallet_reliability", values[i])
			} else if value.Valid {
				_m.WalletReliability = value.String
			}
		case upstreamconnection.FieldWalletRaw:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field wallet_raw", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.WalletRaw); err != nil {
					return fmt.Errorf("unmarshal field wallet_raw: %w", err)
				}
			}
		case upstreamconnection.FieldWalletObservedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field wallet_observed_at", values[i])
			} else if value.Valid {
				_m.WalletObservedAt = new(time.Time)
				*_m.WalletObservedAt = value.Time
			}
		case upstreamconnection.FieldLastDiscoveredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_discovered_at", values[i])
			} else if value.Valid {
				_m.LastDiscoveredAt = new(time.Time)
				*_m.LastDiscoveredAt = value.Time
			}
		case upstreamconnection.FieldLastSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_synced_at", values[i])
			} else if value.Valid {
				_m.LastSyncedAt = new(time.Time)
				*_m.LastSyncedAt = value.Time
			}
		case upstreamconnection.FieldNextSyncAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_sync_at", values[i])
			} else if value.Valid {
				_m.NextSyncAt = new(time.Time)
				*_m.NextSyncAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamConnection.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamConnection) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProxy queries the "proxy" edge of the UpstreamConnection entity.
func (_m *UpstreamConnection) QueryProxy() *ProxyQuery {
	return NewUpstreamConnectionClient(_m.config).QueryProxy(_m)
}

// QueryGroups queries the "groups" edge of the UpstreamConnection entity.
func (_m *UpstreamConnection) QueryGroups() *UpstreamGroupQuery {
	return NewUpstreamConnectionClient(_m.config).QueryGroups(_m)
}

// QueryAccountBindings queries the "account_bindings" edge of the UpstreamConnection entity.
func (_m *UpstreamConnection) QueryAccountBindings() *UpstreamAccountBindingQuery {
	return NewUpstreamConnectionClient(_m.config).QueryAccountBindings(_m)
}

// Update returns a builder for updating this UpstreamConnection.
// Note that you need to call UpstreamConnection.Unwrap() before calling this method if this UpstreamConnection
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamConnection) Update() *UpstreamConnectionUpdateOne {
	return NewUpstreamConnectionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamConnection entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamConnection) Unwrap() *UpstreamConnection {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpstreamConnection is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamConnection) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamConnection(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("auth_mode=")
	builder.WriteString(_m.AuthMode)
	builder.WriteString(", ")
	builder.WriteString("management_base_url=")
	builder.WriteString(_m.ManagementBaseURL)
	builder.WriteString(", ")
	builder.WriteString("forwarding_base_url=")
	builder.WriteString(_m.ForwardingBaseURL)
	builder.WriteString(", ")
	builder.WriteString("credential_encrypted=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("credential_fingerprint=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("legacy_migration_key=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("credential_hint=")
	builder.WriteString(_m.CredentialHint)
	builder.WriteString(", ")
	builder.WriteString("remote_user_id=")
	builder.WriteString(_m.RemoteUserID)
	builder.WriteString(", ")
	if v := _m.ProxyID; v != nil {
		builder.WriteString("proxy_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("capabilities=")
	builder.WriteString(fmt.Sprintf("%v", _m.Capabilities))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteString(", ")
	builder.WriteString("sync_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.SyncEnabled))
	builder.WriteString(", ")
	builder.WriteString("sync_interval_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.SyncIntervalSeconds))
	builder.WriteString(", ")
	builder.WriteString("sync_failures=")
	builder.WriteString(fmt.Sprintf("%v", _m.SyncFailures))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	if v := _m.WalletAmount; v != nil {
		builder.WriteString("wallet_amount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("wallet_currency=")
	builder.WriteString(_m.WalletCurrency)
	builder.WriteString(", ")
	if v := _m.WalletUsd; v != nil {
		builder.WriteString("wallet_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("wallet_unlimited=")
	builder.WriteString(fmt.Sprintf("%v", _m.WalletUnlimited))
	builder.WriteString(", ")
	builder.WriteString("wallet_source=")
	builder.WriteString(_m.WalletSource)
	builder.WriteString(", ")
	builder.WriteString("wallet_reliability=")
	builder.WriteString(_m.WalletReliability)
	builder.WriteString(", ")
	builder.WriteString("wallet_raw=")
	builder.WriteString(fmt.Sprintf("%v", _m.WalletRaw))
	builder.WriteString(", ")
	if v := _m.WalletObservedAt; v != nil {
		builder.WriteString("wallet_observed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastDiscoveredAt; v != nil {
		builder.WriteString("last_discovered_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastSyncedAt; v != nil {
		builder.WriteString("last_synced_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.NextSyncAt; v != nil {
		builder.WriteString("next_sync_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamConnections is a parsable slice of UpstreamConnection.
type UpstreamConnections []*UpstreamConnection
