// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreamconnection"
	"github.com/Wei-Shaw/sub2api/ent/upstreamgroup"
)

// UpstreamGroupQuery is the builder for querying UpstreamGroup entities.
type UpstreamGroupQuery struct {
	config
	ctx            *QueryContext
	order          []upstreamgroup.OrderOption
	inters         []Interceptor
	predicates     []predicate.UpstreamGroup
	withConnection *UpstreamConnectionQuery
	modifiers      []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UpstreamGroupQuery builder.
func (_q *UpstreamGroupQuery) Where(ps ...predicate.UpstreamGroup) *UpstreamGroupQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *UpstreamGroupQuery) Limit(limit int) *UpstreamGroupQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *UpstreamGroupQuery) Offset(offset int) *UpstreamGroupQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *UpstreamGroupQuery) Unique(unique bool) *UpstreamGroupQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *UpstreamGroupQuery) Order(o ...upstreamgroup.OrderOption) *UpstreamGroupQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryConnection chains the current query on the "connection" edge.
func (_q *UpstreamGroupQuery) QueryConnection() *UpstreamConnectionQuery {
	query := (&UpstreamConnectionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(upstreamgroup.Table, upstreamgroup.FieldID, selector),
			sqlgraph.To(upstreamconnection.Table, upstreamconnection.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, upstreamgroup.ConnectionTable, upstreamgroup.ConnectionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UpstreamGroup entity from the query.
// Returns a *NotFoundError when no UpstreamGroup was found.
func (_q *UpstreamGroupQuery) First(ctx context.Context) (*UpstreamGroup, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{upstreamgroup.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *UpstreamGroupQuery) FirstX(ctx context.Context) *UpstreamGroup {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UpstreamGroup ID from the query.
// Returns a *NotFoundError when no UpstreamGroup ID was found.
func (_q *UpstreamGroupQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{upstreamgroup.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *UpstreamGroupQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UpstreamGroup entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UpstreamGroup entity is found.
// Returns a *NotFoundError when no UpstreamGroup entities are found.
func (_q *UpstreamGroupQuery) Only(ctx context.Context) (*UpstreamGroup, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{upstreamgroup.Label}
	default:
		return nil, &NotSingularError{upstreamgroup.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *UpstreamGroupQuery) OnlyX(ctx context.Context) *UpstreamGroup {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UpstreamGroup ID in the query.
// Returns a *NotSingularError when more than one UpstreamGroup ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *UpstreamGroupQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{upstreamgroup.Label}
	default:
		err = &NotSingularError{upstreamgroup.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *UpstreamGroupQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UpstreamGroups.
func (_q *UpstreamGroupQuery) All(ctx context.Context) ([]*UpstreamGroup, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UpstreamGroup, *UpstreamGroupQuery]()
	return withInterceptors[[]*UpstreamGroup](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *UpstreamGroupQuery) AllX(ctx context.Context) []*UpstreamGroup {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UpstreamGroup IDs.
func (_q *UpstreamGroupQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(upstreamgroup.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *UpstreamGroupQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *UpstreamGroupQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*UpstreamGroupQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *UpstreamGroupQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *UpstreamGroupQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *UpstreamGroupQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UpstreamGroupQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *UpstreamGroupQuery) Clone() *UpstreamGroupQuery {
	if _q == nil {
		return nil
	}
	return &UpstreamGroupQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]upstreamgroup.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.UpstreamGroup{}, _q.predicates...),
		withConnection: _q.withConnection.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithConnection tells the query-builder to eager-load the nodes that are connected to
// the "connection" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UpstreamGroupQuery) WithConnection(opts ...func(*UpstreamConnectionQuery)) *UpstreamGroupQuery {
	query := (&UpstreamConnectionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withConnection = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UpstreamGroup.Query().
//		GroupBy(upstreamgroup.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *UpstreamGroupQuery) GroupBy(field string, fields ...string) *UpstreamGroupGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UpstreamGroupGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = upstreamgroup.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.UpstreamGroup.Query().
//		Select(upstreamgroup.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *UpstreamGroupQuery) Select(fields ...string) *UpstreamGroupSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &UpstreamGroupSelect{UpstreamGroupQuery: _q}
	sbuild.label = upstreamgroup.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UpstreamGroupSelect configured with the given aggregations.
func (_q *UpstreamGroupQuery) Aggregate(fns ...AggregateFunc) *UpstreamGroupSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *UpstreamGroupQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !upstreamgroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *UpstreamGroupQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UpstreamGroup, error) {
	var (
		nodes       = []*UpstreamGroup{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withConnection != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UpstreamGroup).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UpstreamGroup{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withConnection; query != nil {
		if err := _q.loadConnection(ctx, query, nodes, nil,
			func(n *UpstreamGroup, e *UpstreamConnection) { n.Edges.Connection = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *UpstreamGroupQuery) loadConnection(ctx context.Context, query *UpstreamConnectionQuery, nodes []*UpstreamGroup, init func(*UpstreamGroup), assign func(*UpstreamGroup, *UpstreamConnection)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*UpstreamGroup)
	for i := range nodes {
		fk := nodes[i].ConnectionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(upstreamconnection.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "connection_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *UpstreamGroupQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *UpstreamGroupQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(upstreamgroup.Table, upstreamgroup.Columns, sqlgraph.NewFieldSpec(upstreamgroup.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstreamgroup.FieldID)
		for i := range fields {
			if fields[i] != upstreamgroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withConnection != nil {
			_spec.Node.AddColumnOnce(upstreamgroup.FieldConnectionID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *UpstreamGroupQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(upstreamgroup.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = upstreamgroup.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *UpstreamGroupQuery) ForUpdate(opts ...sql.LockOption) *UpstreamGroupQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *UpstreamGroupQuery) ForShare(opts ...sql.LockOption) *UpstreamGroupQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// UpstreamGroupGroupBy is the group-by builder for UpstreamGroup entities.
type UpstreamGroupGroupBy struct {
	selector
	build *UpstreamGroupQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *UpstreamGroupGroupBy) Aggregate(fns ...AggregateFunc) *UpstreamGroupGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *UpstreamGroupGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpstreamGroupQuery, *UpstreamGroupGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *UpstreamGroupGroupBy) sqlScan(ctx context.Context, root *UpstreamGroupQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UpstreamGroupSelect is the builder for selecting fields of UpstreamGroup entities.
type UpstreamGroupSelect struct {
	*UpstreamGroupQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *UpstreamGroupSelect) Aggregate(fns ...AggregateFunc) *UpstreamGroupSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *UpstreamGroupSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpstreamGroupQuery, *UpstreamGroupSelect](ctx, _s.UpstreamGroupQuery, _s, _s.inters, v)
}

func (_s *UpstreamGroupSelect) sqlScan(ctx context.Context, root *UpstreamGroupQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
