// Code generated by ent, DO NOT EDIT.

package supportissueevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldLTE(FieldID, id))
}

// IssueID applies equality check predicate on the "issue_id" field. It's identical to IssueIDEQ.
func IssueID(v int64) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldEQ(FieldIssueID, v))
}

// ActorUserID applies equality check predicate on the "actor_user_id" field. It's identical to ActorUserIDEQ.
func ActorUserID(v int64) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldEQ(FieldActorUserID, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldEQ(FieldEventType, v))
}

// FromStatus applies equality check predicate on the "from_status" field. It's identical to FromStatusEQ.
func FromStatus(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldEQ(FieldFromStatus, v))
}

// ToStatus applies equality check predicate on the "to_status" field. It's identical to ToStatusEQ.
func ToStatus(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldEQ(FieldToStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// IssueIDEQ applies the EQ predicate on the "issue_id" field.
func IssueIDEQ(v int64) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldEQ(FieldIssueID, v))
}

// IssueIDNEQ applies the NEQ predicate on the "issue_id" field.
func IssueIDNEQ(v int64) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldNEQ(FieldIssueID, v))
}

// IssueIDIn applies the In predicate on the "issue_id" field.
func IssueIDIn(vs ...int64) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldIn(FieldIssueID, vs...))
}

// IssueIDNotIn applies the NotIn predicate on the "issue_id" field.
func IssueIDNotIn(vs ...int64) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldNotIn(FieldIssueID, vs...))
}

// ActorUserIDEQ applies the EQ predicate on the "actor_user_id" field.
func ActorUserIDEQ(v int64) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldEQ(FieldActorUserID, v))
}

// ActorUserIDNEQ applies the NEQ predicate on the "actor_user_id" field.
func ActorUserIDNEQ(v int64) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldNEQ(FieldActorUserID, v))
}

// ActorUserIDIn applies the In predicate on the "actor_user_id" field.
func ActorUserIDIn(vs ...int64) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldIn(FieldActorUserID, vs...))
}

// ActorUserIDNotIn applies the NotIn predicate on the "actor_user_id" field.
func ActorUserIDNotIn(vs ...int64) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldNotIn(FieldActorUserID, vs...))
}

// ActorUserIDGT applies the GT predicate on the "actor_user_id" field.
func ActorUserIDGT(v int64) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldGT(FieldActorUserID, v))
}

// ActorUserIDGTE applies the GTE predicate on the "actor_user_id" field.
func ActorUserIDGTE(v int64) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldGTE(FieldActorUserID, v))
}

// ActorUserIDLT applies the LT predicate on the "actor_user_id" field.
func ActorUserIDLT(v int64) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldLT(FieldActorUserID, v))
}

// ActorUserIDLTE applies the LTE predicate on the "actor_user_id" field.
func ActorUserIDLTE(v int64) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldLTE(FieldActorUserID, v))
}

// ActorUserIDIsNil applies the IsNil predicate on the "actor_user_id" field.
func ActorUserIDIsNil() predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldIsNull(FieldActorUserID))
}

// ActorUserIDNotNil applies the NotNil predicate on the "actor_user_id" field.
func ActorUserIDNotNil() predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldNotNull(FieldActorUserID))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldContainsFold(FieldEventType, v))
}

// FromStatusEQ applies the EQ predicate on the "from_status" field.
func FromStatusEQ(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldEQ(FieldFromStatus, v))
}

// FromStatusNEQ applies the NEQ predicate on the "from_status" field.
func FromStatusNEQ(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldNEQ(FieldFromStatus, v))
}

// FromStatusIn applies the In predicate on the "from_status" field.
func FromStatusIn(vs ...string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldIn(FieldFromStatus, vs...))
}

// FromStatusNotIn applies the NotIn predicate on the "from_status" field.
func FromStatusNotIn(vs ...string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldNotIn(FieldFromStatus, vs...))
}

// FromStatusGT applies the GT predicate on the "from_status" field.
func FromStatusGT(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldGT(FieldFromStatus, v))
}

// FromStatusGTE applies the GTE predicate on the "from_status" field.
func FromStatusGTE(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldGTE(FieldFromStatus, v))
}

// FromStatusLT applies the LT predicate on the "from_status" field.
func FromStatusLT(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldLT(FieldFromStatus, v))
}

// FromStatusLTE applies the LTE predicate on the "from_status" field.
func FromStatusLTE(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldLTE(FieldFromStatus, v))
}

// FromStatusContains applies the Contains predicate on the "from_status" field.
func FromStatusContains(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldContains(FieldFromStatus, v))
}

// FromStatusHasPrefix applies the HasPrefix predicate on the "from_status" field.
func FromStatusHasPrefix(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldHasPrefix(FieldFromStatus, v))
}

// FromStatusHasSuffix applies the HasSuffix predicate on the "from_status" field.
func FromStatusHasSuffix(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldHasSuffix(FieldFromStatus, v))
}

// FromStatusIsNil applies the IsNil predicate on the "from_status" field.
func FromStatusIsNil() predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldIsNull(FieldFromStatus))
}

// FromStatusNotNil applies the NotNil predicate on the "from_status" field.
func FromStatusNotNil() predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldNotNull(FieldFromStatus))
}

// FromStatusEqualFold applies the EqualFold predicate on the "from_status" field.
func FromStatusEqualFold(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldEqualFold(FieldFromStatus, v))
}

// FromStatusContainsFold applies the ContainsFold predicate on the "from_status" field.
func FromStatusContainsFold(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldContainsFold(FieldFromStatus, v))
}

// ToStatusEQ applies the EQ predicate on the "to_status" field.
func ToStatusEQ(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldEQ(FieldToStatus, v))
}

// ToStatusNEQ applies the NEQ predicate on the "to_status" field.
func ToStatusNEQ(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldNEQ(FieldToStatus, v))
}

// ToStatusIn applies the In predicate on the "to_status" field.
func ToStatusIn(vs ...string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldIn(FieldToStatus, vs...))
}

// ToStatusNotIn applies the NotIn predicate on the "to_status" field.
func ToStatusNotIn(vs ...string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldNotIn(FieldToStatus, vs...))
}

// ToStatusGT applies the GT predicate on the "to_status" field.
func ToStatusGT(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldGT(FieldToStatus, v))
}

// ToStatusGTE applies the GTE predicate on the "to_status" field.
func ToStatusGTE(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldGTE(FieldToStatus, v))
}

// ToStatusLT applies the LT predicate on the "to_status" field.
func ToStatusLT(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldLT(FieldToStatus, v))
}

// ToStatusLTE applies the LTE predicate on the "to_status" field.
func ToStatusLTE(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldLTE(FieldToStatus, v))
}

// ToStatusContains applies the Contains predicate on the "to_status" field.
func ToStatusContains(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldContains(FieldToStatus, v))
}

// ToStatusHasPrefix applies the HasPrefix predicate on the "to_status" field.
func ToStatusHasPrefix(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldHasPrefix(FieldToStatus, v))
}

// ToStatusHasSuffix applies the HasSuffix predicate on the "to_status" field.
func ToStatusHasSuffix(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldHasSuffix(FieldToStatus, v))
}

// ToStatusIsNil applies the IsNil predicate on the "to_status" field.
func ToStatusIsNil() predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldIsNull(FieldToStatus))
}

// ToStatusNotNil applies the NotNil predicate on the "to_status" field.
func ToStatusNotNil() predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldNotNull(FieldToStatus))
}

// ToStatusEqualFold applies the EqualFold predicate on the "to_status" field.
func ToStatusEqualFold(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldEqualFold(FieldToStatus, v))
}

// ToStatusContainsFold applies the ContainsFold predicate on the "to_status" field.
func ToStatusContainsFold(v string) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldContainsFold(FieldToStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// HasIssue applies the HasEdge predicate on the "issue" edge.
func HasIssue() predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, IssueTable, IssueColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIssueWith applies the HasEdge predicate on the "issue" edge with a given conditions (other predicates).
func HasIssueWith(preds ...predicate.SupportIssue) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(func(s *sql.Selector) {
		step := newIssueStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SupportIssueEvent) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SupportIssueEvent) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SupportIssueEvent) predicate.SupportIssueEvent {
	return predicate.SupportIssueEvent(sql.NotPredicates(p))
}
