// Code generated by ent, DO NOT EDIT.

package subscriptionplanexternalmapping

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the subscriptionplanexternalmapping type in the database.
	Label = "subscription_plan_external_mapping"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldLegacyGroupID holds the string denoting the legacy_group_id field in the database.
	FieldLegacyGroupID = "legacy_group_id"
	// FieldLegacyValidityDays holds the string denoting the legacy_validity_days field in the database.
	FieldLegacyValidityDays = "legacy_validity_days"
	// FieldLegacyValue holds the string denoting the legacy_value field in the database.
	FieldLegacyValue = "legacy_value"
	// FieldPlanID holds the string denoting the plan_id field in the database.
	FieldPlanID = "plan_id"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// EdgeLegacyGroup holds the string denoting the legacy_group edge name in mutations.
	EdgeLegacyGroup = "legacy_group"
	// EdgePlan holds the string denoting the plan edge name in mutations.
	EdgePlan = "plan"
	// Table holds the table name of the subscriptionplanexternalmapping in the database.
	Table = "subscription_plan_external_mappings"
	// LegacyGroupTable is the table that holds the legacy_group relation/edge.
	LegacyGroupTable = "subscription_plan_external_mappings"
	// LegacyGroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	LegacyGroupInverseTable = "groups"
	// LegacyGroupColumn is the table column denoting the legacy_group relation/edge.
	LegacyGroupColumn = "legacy_group_id"
	// PlanTable is the table that holds the plan relation/edge.
	PlanTable = "subscription_plan_external_mappings"
	// PlanInverseTable is the table name for the SubscriptionPlan entity.
	// It exists in this package in order to avoid circular dependency with the "subscriptionplan" package.
	PlanInverseTable = "subscription_plans"
	// PlanColumn is the table column denoting the plan relation/edge.
	PlanColumn = "plan_id"
)

// Columns holds all SQL columns for subscriptionplanexternalmapping fields.
var Columns = []string{
	FieldID,
	FieldSource,
	FieldLegacyGroupID,
	FieldLegacyValidityDays,
	FieldLegacyValue,
	FieldPlanID,
	FieldEnabled,
	FieldPriority,
	FieldNotes,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the SubscriptionPlanExternalMapping queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByLegacyGroupID orders the results by the legacy_group_id field.
func ByLegacyGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLegacyGroupID, opts...).ToFunc()
}

// ByLegacyValidityDays orders the results by the legacy_validity_days field.
func ByLegacyValidityDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLegacyValidityDays, opts...).ToFunc()
}

// ByLegacyValue orders the results by the legacy_value field.
func ByLegacyValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLegacyValue, opts...).ToFunc()
}

// ByPlanID orders the results by the plan_id field.
func ByPlanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanID, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByLegacyGroupField orders the results by legacy_group field.
func ByLegacyGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLegacyGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByPlanField orders the results by plan field.
func ByPlanField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlanStep(), sql.OrderByField(field, opts...))
	}
}
func newLegacyGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LegacyGroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LegacyGroupTable, LegacyGroupColumn),
	)
}
func newPlanStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlanInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PlanTable, PlanColumn),
	)
}
